### PR TITLE
Add behavior to long term capital gain

### PR DESCRIPTION
**Pull request by Amy-Xu**
Per request of issue #226, the behavior effect of capital gain is added in this PR. Taxpayers are assumed to change the timing and amounts of their realized cap gain when facing higher rates. In our code, we define persistent elasticity for long term capital gain as, percentage difference of long term capital gain over percentage difference of after tax rate. Specifically, the marginal tax rate (for the after tax rate) is calculated the combined tax liability change (including both individual income tax and payroll), over one cent margin of net long term cap gain (p23250). Then the capital gain behavior effect, backed out from the after tax rates and user-input elasticity, is added on to p23250 and e01100 (not sure about this part).

Adding this behavior seems to close up the results gap between our calculator and budget option, particularly the option increase long term cap gain and dividends rate by two percentage points. Here's a comparison of results, in billions, starting from year 2015.

master (no behavior):
screen shot 2016-01-11 at 5 23 24 pm

PR (if persistent elasticity == 0.78):
screen shot 2016-01-11 at 6 46 41 pm

PR (if persistent elasticity == 1.2)
screen shot 2016-01-11 at 6 46 51 pm

Would very appreciate any suggestions on assumption/implementation/results or anything for this PR. Thanks a lot. @MattHJensen @feenberg @martinholmer @talumbau

### CODE REVIEW

**Comment by MattHJensen** [comment]
@amy-xu, could you post the code with all of the documentation that you think is helpful (and/or pseudocode and/or an example) to the issue so that @feenberg can easily print and help look over the implementation of this CG elasticity code?

**Comment by MattHJensen** [comment]
I should also say, It's really exciting to get this CG behavior incorporated!

**Comment by Amy-Xu** [comment]
@feenberg Dan, so here's how I implement this cap gain behavior. I'm using one record (RECID == 3452160) as an example to illustrate how the behavior's added in the experiment of increasing long term cap gain and dividend rate by two percentage points. Two calculators are set up here, calc1 the baseline, and calc2 the increased rates.

1)  calculate MTR of each record using `p23250` - net long term gain/loss
     - MTRs are 0.238 and 0.258 respectively under current law and increased rates
     - Both individual income and combined income have the same MTR in this scenario so I used individual income MTR in this example

2) calculate after tax rates and back out delta on realized long term cap gain
    - after tax rate = ((1 - .238) - (1- .258))/(1 - .238) = -.0262
    - tax elasticity is a user-input parameter. In this example I plugged in .78
    - delta on LTCG = after tax rate * tax elasticity * p23250 in calc1 = -.0262 * .78 * 68437239 = -1401049.96

3) then add this delta amount to p23250 and e01100 and calculate tax liabilities again. The resulting tax liabilities would include behavior effects.

What do you think of this procedure?

PS: When I wrote this up, I was wondering whether we need to care about taxpayers with zero initial long term cap gain? Even though they do have a valid MTR on cap gain, they would end up with zero delta due to the zero initial value. Does it make sense for them not changing their cap gain at all?

**Comment by feenberg** [comment]
On Fri, 15 Jan 2016, Amy Xu wrote:

> 
> @feenberg Dan, so here's how I implement this cap gain behavior. I'm using one record
> (RECID == 3452160) as an example to illustrate how the behavior's added in the
> experiment of increasing long term cap gain and dividend rate by two percentage
> points. Two calculators are set up here, calc1 the baseline, and calc2 the increased
> rates.
> 
> 1) calculate MTR of each record using p23250 - net long term gain/loss
> - MTRs are 0.238 and 0.258 respectively under current law and increased rates
> - Both individual income and combined income have the same MTR in this scenario so I
> used individual income MTR in this example

Not sure what combined income is, but this seems correct to me.

> 
> 2) calculate after tax rates and back out delta on realized long term cap gain
> - after tax rate = ((1 - .238) - (1- .258))/(1 - .238) = -.0262
> - tax elasticity is a user-input parameter. In this example I plugged in .78
> - delta on LTCG = after tax rate * tax elasticity * p23250 in calc1 = -.0262 * .78 *
> 68437239 = -1401049.96
>

Yes, correct.

> 3) then add this delta amount to p23250 and e01100 and calculate tax liabilities
> again. The resulting tax liabilities would include behavior effects.
>

It should be enough to add to p23250. Is e01100 used in the calculator? I 
think it is derivable from p23250 and other values.

> What do you think of this procedure?

That is correct.

> 
> PS: When I wrote this up, I was wondering whether we need to care about taxpayers with
> zero initial long term cap gain? Even though they do have a valid MTR on cap gain,

They are unaffected by the change in cg tax rate.

> they would end up with zero delta due to the zero initial value. Does it make sense
> for them not changing their cap gain at all?
>

It doesn't make perfect economic sense, but is a consequence of how the 
models are estimated. If someone publishes two-stage results with 
separate estimates for "participation" and "quantity" we could decide to 
accomodate that, but I don't think anyone has done that, nor do I think it 
would make much difference, nor have I seen anyone ask for it yet.

dan

**Comment by Amy-Xu** [comment]
@feenberg I wasn't sure whether `p23250` is enough or not, cause I was a bit confused by the few lines here:

```
if e01100 > 0.:
       c24510 = float(e01100)
else:
       c24510 = max(0., min(c23650, p23250)) + e01100
```

It seems to me that if the delta's only added to p23250, it might not necessarily get to 24510, which is used in schedule D calculation. What do you think?

**Comment by feenberg** [comment]
In my current sas code there is a line:

   c24510 = max(0,min(c23650,e23250)) + e01100;      /* gain for tax computation */

Perhaps that is a recent correction? If so, I can send you the current 
code.

dan

**Comment by Amy-Xu** [comment]
That would be great! @feenberg Thank you Dan! Could you also copy to Sean as well? 

@GoFroggyRun Could you also confirm this line's been updated? Thanks!

**Comment by GoFroggyRun** [comment]
@feenberg :
I just checked the current version of SAS code on git, it seems that along with the line: 
`c24510 = max(0,min(c23650,e23250)) + e01100;      /* gain for tax computation */ `, 
there's a couple lines followed immediately that read:
```
if _pufmake then c24510 = e24510;
if e01100 gt 0 then c24510 = e01100;      /* from app f 2008 drf */
```
The above should correspond to what Amy has mentioned:
>
```
if e01100 > 0.:
     c24510 = float(e01100)
else:
     c24510 = max(0., min(c23650, p23250)) + e01100
```

Just let me know if there's any updates in the SAS code. Thanks in advance!

cc @Amy-Xu

**Comment by feenberg** [comment]
On Sat, 16 Jan 2016, Sean.Wang wrote:

> 
> @feenberg :
> I just checked the current version of SAS code on git, it seems that along with the
> line:
> c24510 = max(0,min(c23650,e23250)) + e01100; /* gain for tax computation */,
> there's a couple lines followed immediately that read:
> 
> if _pufmake then c24510 = e24510;
> if e01100 gt 0 then c24510 = e01100;      /* from app f 2008 drf */

The _pufmake variable is true when I am at the IRS creating imputations 
for the PUF. SOI gives me more variables than are in the PUF to make the 
imputations. So the assignment of e24510 to c24510 shouldn't occur in 
TaxBrain.

The e01100 assignment will occur. I will try to figure out its 
significance on Tuesday. For the moment I am baffled. The comment suggests 
it was copied from the SOI documentation of their editing program.

Even if the SAS code calculates tax perfectly, it may not be correct for 
the marginal rate.

I have attached the latest version of the capital gains calculations.

dan

> 
> The above should correspond to what Amy has mentioned:
> 
> if e01100 > 0.:
>      c24510 = float(e01100)
> else:
>      c24510 = max(0., min(c23650, p23250)) + e01100
> 
> Just let me know if there's any updates in the SAS code. Thanks in advance!
> 
> cc @Amy-Xu
> 
> —
> Reply to this email directly or view it on
> GitHub.[AHvQVQ6IAPGsunC00U2KyTh6dNjh3tnaks5parYHgaJpZM4HCwK0.gif]
> 
> 
>
/* Tax with gains */
c24515=0;
c24517=0;
c24520=0;
c24530=0;
c24532=0;
c24533=0;
c24540=0;
c24581=0;
_dwks16=0;;

_hascg = e23250 gt 0 or e00650 gt 0 or e01100 gt 0;
if flpdyr ge 2003 then _hascg = _hascg or e00650 gt 0;
if _hascg eq 0 then goto nocg;
if flpdyr in(1997:2002) & _hascg then do;
     c24510 = max(0,min(c23650,e23250)+e01100);         /* schD gain for tax comp */
     c24516 = max(0,c24510 - e58990);            /* gain less invest income */
     _dwks6 =  max(0,min(e22250+e22550 ,e22550));
     _dwks8 = _dwks6 + e24515;                   /* unrecaptured 1250 gain */
     c24517 = max(0,c24516 - _dwks8);            /* gain less 25% income */
     c24520 = max(0,c04800 - c24517);            /* tent TI less schD gain */
     c24530 = min(_brk2(flpdyr,MARS),_taxinc);   /*min TI for bracket*/
     _dwks12 = min(c24520,c24530);
     _dwks13 = max(0,_taxinc - c24516);
     c24540 = max(_dwks12,_dwks13);
      %TAXER(c24540,c24560,MARS);                     /* e24560 non-SchD Tax */
     _dwks16 = c24530 - _dwks12;
     c24581 = _dwks16;
     if flpdyr in(2001,2002) then do;
        _dwks17 = e24583;
        c24585 = max(0,min(c24581,_dwks17));
        c24587 = .08 * c24585;                   /* SchD 8% Tax Amount */
        c24590 = c24581 - c24585;
     end; * 2001:2002;
     if flpdyr le 2000 then c24590 = c24530 - _dwks12;
     c24595 = .1 * c24590;                    /* SchD 10% Tax Amount    */
     _dwks22 = min(_taxinc,c24517);
     if flpdyr ge 2001 then
        c24600 = _dwks22 - c24581;           /* 20% SchD gains */
     else
        c24600 = _dwks22 - c24590;

     c24605 = .20 * c24600;                   /* Tax on 20% gains */
     _dwks26 = min(c24516,e24515);
     _dwks27 = c24516 + c24540;
     _dwks29 = max(0,_dwks27-_taxinc);
     c24610 = max(0,_dwks26-_dwks29);         /* 25% SchD gains */
     c24615 = .25 * c24610;                   /* Tax on 25% gains */

     if flpdyr ge 2001 then                   /* SchD 28% income */
        c24550 = _taxinc - (c24540 + c24581 + c24600 + c24610);
     if flpdyr le 2000 then                 
        c24550 = _taxinc - (c24540 + c24590 +c24600 + c24610);
     c24570 = .28 * c24550;                   /* SchD 28% Tax */

     _taxcg = c24595 + c24605 + c24615 + c24570 +c24560;
     if flpdyr ge 2001 then _taxcg = c24587 + _taxcg;
     c24580 = min(_taxcg,_xyztax);      /* SchD tax  */
end; * 1997:2002;

c24532 = 0;

if flpdyr ge 2003 then do;
   _dwks5 = max(0,e58990-e58980);
   c24505 = max(0,c00650 - _dwks5); 
   c24510 = max(0,min(c23650,e23250)) + e01100;      /* gain for tax computation */
   if _pufmake then c24510 = e24510;
   if e01100 gt 0 then c24510 = e01100;      /* from app f 2008 drf */
   _dwks9 = max(0,c24510-min(e58990,e58980));/* e24516 gain less invest y */
   c24516 = c24505 + _dwks9;
   if _pufmake then c24516 = e24516;
   _dwks12 = min(_dwks9,e24515+e24518);
   c24517 = c24516 - _dwks12;                /* gain less 25% and 28%  */
   if _pufmake then c24517 = e24517;
   c24520 = max(0,_taxinc - c24517);         /* tentative TI less schD gain */
   if _pufmake then c24520 = e24520;
   c24530 = min(_brk2(flpdyr,MARS),_taxinc); /* minimum TIfor bracket */
   if _pufmake then c24530 = e24530;
   _dwks16 = min(c24520,c24530);
   _dwks17 = max(0,_taxinc - c24516);
   c24540 = max(_dwks16,_dwks17);
   if _pufmake and _feided eq 0 then c24540 = e24540;
   if flpdyr eq 2003 then do;
      c24532 = c24530 - _dwks16;            /* 5% limitation amount   */
      c22256 = -min(0,e21606+e21626+e21776);/* net STL (5/5/03)*/
      c22556 = e22306+e22326+e22366+e22376; /* LTG or loss (5/5/03) */
      c23656 = max(0,-c22256 + c22556);     /* net cg before exclusion/loss limit (5/5/03) */
      c24533 = c23656 + c24505;             /* qualifying dividend and schD gain (5/5/03)  */
      c24534 = min(c24532,c24533);          /* income subject to 5% tax */
      if _pufmake then c24534 = e24534;
   end; * 2003;

   if flpdyr ge 2004 then c24534 = c24530 - _dwks16;
   if flpdyr lt 2008 then c24535 = .05 * c24534; else c24535 = 0; /*e24535 Schedule D 5% Tax */;
   
   c24605 = 0;
   if flpdyr eq 2003 then do;
      c24581 = c24532 - c24534;
      c24585 = min(c24581,e24583);         /* income subject to 8% tax  */
      c24587 = .08 * c24585;               /* 8% Tax */
      c24590 = c24581 - c24585;            /* income subject to 10% tax  */
      c24595 = .1 * c24590;                /* 10% Tax */
      _dwks29 = min(_taxinc,c24517);
      _dwks31 = max(0,_dwks29-c24532);
      _dwks34 = c24533 - c24534;
      c24597 = min(_dwks31,_dwks34);       /* income subject to 15% tax  */
      c24598 = .15 * c24597;               /* 15% Tax Amount */
      c24600 = _dwks31 - c24597;           /* income subject to 20% tax */
      c24605 = .2 * c24600;                /* 20% Tax */
      _dwks39 = min(c24516,e24515);
      _dwks40 = c24516 + c24540;
      _dwks42 = max(0,_dwks40-_taxinc);
      c24610 = max(0,_dwks39-_dwks42);     /* income subject to 25% tax */
      c24615 = .25 * c24610;               /* 25% Tax */
     _dwks45 = c24540+c24532+_dwks31+c24610;
      c24550 = max(0,_taxinc - _dwks45);   /* income subject to 28% tax */
      c24570 = .28 * c24550;               /* 28% Tax */
   end; * 2003;

/*start rev*/
   if flpdyr ge 2004 and flpdyr le 2012 then do;
      _dwks21 = min(_taxinc,c24517);
      c24597 = max(0,_dwks21-c24534);      /* income subject to 15% tax */
      c24598 = .15 * c24597;               /* 15% Tax */
      _dwks25 = min(_dwks9,e24515);
      _dwks26 = c24516 + c24540;
      _dwks28 = max(0,_dwks26-_taxinc);
      c24610 = max(0,_dwks25-_dwks28);     /* income subject to 25% tax*/
      c24615 = .25 * c24610;               /* 25% Tax */
      _dwks31 = c24540 + c24534 + c24597 + c24610;
      c24550 = max(0,_taxinc - _dwks31);   /* income subject to 28% tax */
      if _pufmake then c24550 = e24550;
      c24570 = .28 * c24550;               /* 28% Tax */
   end; *2004-2012;
 
   if flpdyr ge 2013  then do;
      _dwks21 = min(_taxinc,c24517);
      _dwks23 = max(0,_dwks21-c24534);      
      _dwks24 = _brk6{flpdyr,MARS};
      _dwks25 = min(_taxinc,_dwks24);
      _dwks26 = c24534 + c24540;
      _dwks27 = max(0,_dwks25 - _dwks26);
      c24597 = min(_dwks23,_dwks27); /* income subject to 15% tax */
      c24598 = .15 * c24597;               /* 15% Tax */
      _dwks30 = c24534 + c24597;
      c24600 = _dwks21 - _dwks30;    /* income subject to 20% tax */
      c24605 = .2*c24600;                  /* 20% Tax */   
      _dwks33 = min(_dwks9,e24515);
      _dwks34 = c24516 + c24540;
      _dwks36 = max(0,_dwks34 - _taxinc);
      c24610 = max(0,_dwks33 - _dwks36); /* income subject to 25% tax */
      c24615 = .25 * c24610;               /* 25% Tax */
      _dwks39 = c24540 + c24534 + c24597 + c24600 + c24610;
      c24550 = _taxinc - _dwks39;      /* income subject to 28% tax */
      c24570 = .28 * c24550;               /* 28% Tax */
   end;  *2013;
   %TAXER(c24540,c24560,MARS);            /* e24560 non-Schedule D Tax Amount */
   if _pufmake and _feided eq 0 then c24560 = e24560;
 
   _taxcg = c24535 + c24598 + c24605 + c24615 + c24570 + c24560;
   if flpdyr eq 2003 then _taxcg = c24587 + c24595 + c24605 + _taxcg;
   c24580 = min(_taxcg,_xyztax);     /* e24580 schedule D tax  */
end; *2003+;

/*end rev*/

nocg: ;

**Comment by feenberg** [comment]
On Sun, 17 Jan 2016, Daniel Feenberg wrote:

>
>
> On Sat, 16 Jan 2016, Sean.Wang wrote:
>
>> 
>
> The e01100 assignment will occur. I will try to figure out its significance 
> on Tuesday. For the moment I am baffled. The comment suggests it was copied 
> from the SOI documentation of their editing program.
>

OK, I find that E01100 is "Capital gains distributions not reported on 
Schedule D", that is mutual fund gains from taxpayers not filing a 
Schedule D. So E01100 is a distinct income source, not part of E23250.

Adding a penny to one or the other should give the same MTR, (except for 
taxpayers with losses). I think we can therefore ignore E01100 when 
calculating the MTR on capital gains for an individual taxpayer. Then we 
get the MTR of long-term gains reported on Schedule D. If we add a penny 
to E01100 we get a very slightly different number - the MTR of gains on 
non-Schedule D gains. Adding half a penny to each, gives us the average of 
the two rates. But the Schedule D rate is much more likely to be of 
interest.

If we want to know the average marginal tax rate on capital gains across 
all taxpayers, then it would be good to increase both E01100 and E23250 by 
1%, and divide the  difference in aggregate tax from that increase in 
aggregate income. But that is a different calculation.

dan

**Comment by Amy-Xu** [comment]
@feenberg Thank you Dan! I just removed `e01100` from this function. Let's get this PR merged first so capital gain behavior's available to other users in need, and think about the marginal tax rate issue across all taxpayers at the same time.

@martinholmer Could you take a glance of my implementation here? Just in case I unconsciously created a trap somewhere. Thanks!

**Comment by martinholmer** [comment]
Amy said:
> @martinholmer Could you take a glance of my implementation here? Just in case I unconsciously created a trap somewhere. Thanks!

I don't see any problems after a quick review, but I'm not that conversant with Behavior logic.

cc @Amy-Xu @MattHJensen @feenberg @GoFroggyRun

**Comment by Amy-Xu** [comment]
Thank you Martin@martinholmer!

@MattHJensen?

**Comment by MattHJensen** [comment]
I'll look through this tomorrow morning.

**Comment by MattHJensen** [comment]
LGTM. Merging. Thanks @Amy-Xu!

**Comment by MattHJensen** [comment]
@Amy-Xu, could you work with @talumbau & co to get this working on TaxBrain? Let's drop the transitory field completely and just keep the persistent field.

**Pull request merged**
