### PR TITLE
add _ID_Benefit_surtax_em

### PR DESCRIPTION
**Pull request by MattHJensen**
Adds an exemption amount to the `BenefitSurtax()` function. My primary intent is to parameterize a dollar cap on itemized deductions:

"In addition, the Trump plan will cap itemized deductions at $200,000 for Married-Joint filers or $100,000 for Single filers."
https://www.donaldjtrump.com/positions/tax-reform

With the surtax rate at 1, then the exemption will serve as a dollar cap on itemized deductions. 

@martinholmer, could you please give me your feedback?

cc @andersonfrailey

### CODE REVIEW

**Comment by MattHJensen** [comment]
pep8 cleanup on its way.

**Comment by martinholmer** [comment]
@MattHJensen,  Pull request #926 looks good to me.  I would make just one minor suggestion regarding documentation.  Now you have this for the new `_ID_BenefitSurtax_em` parameter:
```
... With a 100% surtax rate, it serves as a dollar limit ...
```
It be absolutely clear (and more in line with the documentation of the other `BenefitSurtax` parameters) if it said something like this:
```
... With _ID_BenefitSurtax_crt set to 1.0, it serves as a dollar limit ...
```

**Comment by MattHJensen** [comment]
Thanks a lot @martinholmer. New commits implement your suggestion. I will merge this later today if I receive no other feedback.

**Comment by martinholmer** [comment]
@MattHJensen,  On further reflection, doesn't the documentation need to say this:
```
With _ID_BenefitSurtax_crt set to 0.0 and _ID_BenefitSurtax_trt set to 1.0, it serves as a dollar limit ...
```
instead of what is says now:
```
With _ID_BenefitSurtax_trt set to 1.0, it serves as a dollar limit ...
```

**Comment by MattHJensen** [comment]
> @MattHJensen, On further reflection, doesn't the documentation need to say this:
> 
> With _ID_BenefitSurtax_crt set to 0.0 and _ID_BenefitSurtax_trt set to 1.0, it serves as a dollar limit ...
>  

Yes, I agree. Updated. Thanks @martinholmer.

**Comment by MattHJensen** [comment]
Merging. Thanks for the review Martin.

**Pull request merged**
