### PR TITLE
Add positive spouse earnings to input samples used in validation tests

### PR DESCRIPTION
**Pull request by martinholmer**
The original version of make-in.tcl generated input samples in which all married couples had spouse earnings set to zero.  This was done because at that time the Tax-Calculator did not correctly calculate FICA taxes for couples in which combined earnings were more than roughly $120,000, so spouse earnings would have generated many differences with Internet TAXSIM results that were caused by a known problem that was in the process of being corrected.

Now that the Tax-Calculator computes FICA taxes correctly, the make-in.tcl program has been revised to generate random samples of tax filing units that contain couples with positive taxpayer and positive spouse earnings.  Using these six new input samples, there are a number of significant income tax liability (TAXSIM output variable 4) differences that need to be investigated.  For example, for the a13.in sample there are now 30 (out of 100,000) differences with the largest being $315.75 (for unit with id 3776).  And there are 400 differences in the c13.in sample.  Before adding positive spouse earnings, there were no differences (greater than one cent in absolute value) in any of the six samples.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@GoFroggyRun, could you review this pr?

**Comment by GoFroggyRun** [comment]
Allowing spouse to have positive income would definitely be a more general assumption. There are, however, some differences between two calculators. By taking a brief look at the diff files, I think [ovar] 27 might be able to explain the errors we are having. @martinholmer What do you think? 
@MattHJensen This PR looks good to me, but my concern is: should we merge this PR after #426 being taken care of? If not, then I think we might need to figure out the errors in this PR first before working on #426 .

**Comment by MattHJensen** [comment]
>This PR looks good to me, but my concern is: should we merge this PR after #426 being taken care of? If not, then I think we might need to figure out the errors in this PR first before working on #426 .

@GoFroggyRun, this is up to you. Let us know what you think would be most efficient and we'll merge this when you tell us to.

**Comment by GoFroggyRun** [comment]
@MattHJensen Given that I'm not sure about how long it might take to fix the issues in this PR, and I consider most policy reforms I'm looking at are independent of this earning split issue. I was hoping this PR to be merged after #426 looks good, which hopefully won't take too long if everything goes well.

**Comment by martinholmer** [comment]
@MattHJensen and Sean (@GoFroggyRun) Wang,
If you want to do the reform work in #426 first, OK.  But it seems to me that if we can't even get current law tax liability correct when spouses have earnings, then it is not very convincing to say that several reforms were validated but only under the assumption that there are no spouse earnings.  Seems like the reform tests would have to be redone with samples that contained positive spouse earnings in order for those reform validation tests to be convincing.  So what's the point of doing the reform validation tests twice?

**Comment by GoFroggyRun** [comment]
@martinholmer Yes you are right. We should deal with this issue before working on #426 .
@MattHJensen Please merge this PR.

**Comment by MattHJensen** [comment]
Merging. Thanks @martinholmer and @GoFroggyRun

**Pull request merged**
