### PR TITLE
Update current_law_policy.json

### PR DESCRIPTION
**Pull request by salimfurth**
Clarification of Additional Child Tax Credit purpose.

### CODE REVIEW

**Comment by rickecon** [comment]
Hey, welcome @salimfurth .

**Comment by salimfurth** [comment]
Thanks! Just figuring out how this works.

**Comment by martinholmer** [comment]
@Amy-Xu,
What do you think about these enhancements to the documentation of Child Tax Credit policy parameters?  If these enhancements seem correct to you, I think you ought to merge this pull request into the master branch and thank @salimfurth for his contribution to the Tax-Calculator project.

**Comment by MattHJensen** [comment]
Yes, welcome @salimfurth!

@amy-xu and @salimfurth, one question I have about this is whether we should view the actc and ctc as the same credit or as separate credits. If they are separate credits, better wordings might be: 

"This is the fraction of earning used in calculating the ACTC, which is a partially refundable credit that supplements the CTC for some taxpayers."

rather than

> This is the fraction of earning used in calculating ACTC, which makes CTC a refundable credit for some families.

and

"Families with this number of qualified children or more may qualify for the additional child tax credit, which is a partially refundable credit that supplements the CTC for some taxpayers"

rather than

> Families with this number of qualified children or more may qualify for the additional child tax credit, which makes the CTC refundable

What do you think?

**Comment by MattHJensen** [comment]
@salimfurth, what do you think about the changes to your PR proposed in https://github.com/open-source-economics/Tax-Calculator/pull/523#issuecomment-170252177? If you agree, you could commit these changes on your fork and they will be automatically incorporated in this PR or I could open a PR to your fork suggesting these changes and then you could merge my PR.

**Comment by salimfurth** [comment]
@MattHJensen, I'm not sure how to either make changes or commit at this point. Is that because I committed prematurely when I first made the edits?

**Comment by MattHJensen** [comment]
@salimfurth, if you follow steps 4-6 from the directions I sent by email earlier, I think the changes will be automatically incorporated in this PR after you have completed step 6. Let me know if you have any trouble, in which case we can just go ahead and move forward to getting you set up on the command line or GitHub gui interface, which will make it easier to make changes in the future -- there's just a bit of setup required. You can see what is involved, here: http://taxcalc.readthedocs.org/en/latest/contributor_guide.html. 

> 4) Navigate to https://github.com/YOUR-GITHUB-HANDLE/Tax-Calculator/edit/master/taxcalc/current_law_policy.json. 
5) Find the text that bothered you from from the TaxBrain information ‘i’ hover overs, and change it however you’d like. 
6) At the bottom of the page, add a description of your change, keep the button selected for “commit directly to the master branch”, and click “Commit changes”.

**Comment by salimfurth** [comment]
OK, so I basically did a change from scratch again. Had my initial edits been incorporated into the main stem? If not, I'm a little confused about the sequence here. Thanks for the guidance, @MattHJensen!

**Comment by MattHJensen** [comment]
@salimfurth, looks great! Merging.

**Pull request merged**
