### PR TITLE
Add bootstrap_se_ci utility function and associated test

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request adds a utility function that computes bootstrap a standard error and confidence interval for the specified data and statistic.  The test of the function uses data and bootstrap results from Efron and Tibshirani's classic 1993 book *An Introduction to the Bootstrap*.

### CODE REVIEW

**Comment by feenberg** [comment]
There is a nice analytic formula for the standard error at:

   http://www.itl.nist.gov/div898/software/dataplot/refman2/ch2/weightsd.pdf

but Stata (for one) doesn't offer it as an option. I have always wondered 
if there was some reason it wasn't generally applicable, and if that is 
the case, is it applicable to our TB? It would be a substantial economy 
over bootstrapping.

dan

**Comment by martinholmer** [comment]
@feenberg said with respect to pull request #1547:
> There is a nice analytic formula for the standard error at:
>
>   http://www.itl.nist.gov/div898/software/dataplot/refman2/ch2/weightsd.pdf
>
> but Stata (for one) doesn't offer it as an option. I have always wondered if there was some reason it wasn't generally applicable, and if that is the case, is it applicable to our TB? It would be a substantial economy over bootstrapping.

A formula would always be faster and more accurate than a bootstrap estimate, but the problem is that there are no simple standard-error formulas for statistics other than the sample mean.

Here are some relevant quotes from the Efron and Tibshirani book:

From page 10:
> The bootstrap is a computer-based method for assigning measures of accuracy to statistical estimates.  The basic idea behind the bootstrap is very simple, and goes back at least two centuries.  After reviewing some background material, this book describes the bootstrap method, it implementation on the computer, and its application to some real data analysis problems.  First though, this chapter on the one example of a statistical estimator where we really don't need a computer to assess accuracy: the sample mean.

From page 15:
> Standard errors [of the sample mean] are the simplest measures of statistical accuracy.  Later chapters show how bootstrap methods can assess more complicated accuracy measures, like biases, prediction errors, and confidence intervals.  Bootstrap confidence intervals add another factor of 10 [relative to standard error estimation] to the computational burden.  The payoff for all this computation is an increase in the statistical problems that can be analyzed, a reduction in the [distributional] assumptions of the analysis, and the elimination of the routine but tedious theoretical calculations usually associated with accuracy assessment.

**Comment by feenberg** [comment]
On Wed, 13 Sep 2017, Martin Holmer wrote:

> 
> @feenberg said with respect to pull request #1547:
>
>       There is a nice analytic formula for the standard error at:
>
>       http://www.itl.nist.gov/div898/software/dataplot/refman2/ch2/weightsd.pdf
>
>       but Stata (for one) doesn't offer it as an option. I have always wondered
>       if there was some reason it wasn't generally applicable, and if that is the
>       case, is it applicable to our TB? It would be a substantial economy over
>       bootstrapping.
> 
> A formula would always be faster and more accurate than a bootstrap estimate, but the
> problem is that there are no simple standard-error formulas for statistics other than
> the sample mean.
> 
> Here are some relevant quotes from the Efron and Tibshirani book:
> 
> From page 10:
>
>       The bootstrap is a computer-based method for assigning measures of accuracy
>       to statistical estimates. The basic idea behind the bootstrap is very
>       simple, and goes back at least two centuries. After reviewing some
>       background material, this book describes the bootstrap method, it
>       implementation on the computer, and its application to some real data
>       analysis problems. First though, this chapter on the one example of a
>       statistical estimator where we really don't need a computer to assess
>       accuracy: the sample mean.
> 
> From page 15:
>
>       Standard errors [of the sample mean] are the simplest measures of
>       statistical accuracy. Later chapters show how bootstrap methods can assess
>       more complicated accuracy measures, like biases, prediction errors, and
>       confidence intervals. Bootstrap confidence intervals add another factor of
>       10 [relative to standard error estimation] to the computational burden. The
>       payoff for all this computation is an increase in the statistical problems
>       that can be analyzed, a reduction in the [distributional] assumptions of
>       the analysis, and the elimination of the routine but tedious theoretical
>       calculations usually associated with accuracy assessment.

So you think the formula at

        http://www.itl.nist.gov/div898/software/dataplot/refman2/ch2/weightsd.pdf

is wrong? Or not simple? Or are we calculating "more complicated accuracy 
meansures"? I was afraid it was wrong given the way our sample was 
stratified, it doesn't look that complicated to me. It is available in SAS 
proc means, but nowhere in Stata.


dan

**Comment by martinholmer** [comment]
@feenberg said:
> So you think the formula at
>
>  http://www.itl.nist.gov/div898/software/dataplot/refman2/ch2/weightsd.pdf
>
is wrong?  Or not simple? Or are we calculating "more complicated accuracy 
measures"? 

The formula is correct for the simplest case, but we are calculating "more complicated accuracy measures" (like confidence intervals of count statistics).

**Pull request merged**
