### PR TITLE
Fix policy-parameter-value warning logic

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request fixes problems that were revealed when investigating issue #2004.

The warning logic is complex and difficult to maintain for both Tax-Calculator and TaxBrain.  The warning logic exists **ONLY** because the flaws in the PUF data related to itemized expense amounts have never been fixed (see, for example, [taxdata issue 32](https://github.com/open-source-economics/taxdata/issues/32), which is open but has seen no activity for a year).  The fact that TaxBrain users are (rightfully) complaining about the warning messages suggests that fixing the itemized expense amounts in the PUF data should be a high priority in the taxdata repository.

@MattHJensen @andersonfrailey @hdoupe

### CODE REVIEW

**Comment by hdoupe** [comment]
@martinholmer it's taking me some time to get going this morning. I'm having trouble figuring out what the `_default_value` method is doing. Is it only for the `_STD` or `_STD_dep` variables? If so, what special function is it providing for these parameters?

**Comment by martinholmer** [comment]
@hdoupe asked:
>  I'm having trouble figuring out what the `_default_value` method is doing.  Is it only for the `_STD` or `_STD_dep` variables?

Yes, because those are the only two parameters that we want to warn about when their value falls below what it is in the PUF data, which has (at the moment) no information about itemizable expenses for those who do not itemize.

> If so, what special function is it providing for these parameters?

It produces the indexed 2013 values of either `_STD` or `_STD_Dep` for each year after 2013.  Only if users of PUF data who try to specify a lower value than the 2013 indexed value will experience a warning.

**Comment by hdoupe** [comment]
@martinholmer said

> Yes, because those are the only two parameters that we want to warn about when their value falls below what it is in the PUF data, which has (at the moment) no information about itemizable expenses for those who do not itemize.

That makes sense. Thanks for explaining this. Do you think the `_default_value` method should contain this information in the docstring? 

> It produces the indexed 2013 values of either _STD or _STD_Dep for each year after 2013. Only if users of PUF data who try to specify a lower value than the 2013 indexed value will experience a warning.

Ah, I see. That's the key part that I was missing.

I think I understand what's going on now. Thanks for breaking this down for me.

**Comment by hdoupe** [comment]
@martinholmer [`b6c81cb`](https://github.com/open-source-economics/Tax-Calculator/pull/2005/commits/b6c81cb491c6c1fe74fbffc22817b4b534c81e1b) looks good to me. Thanks for updating this.

**Pull request merged**
