### PR TITLE
Preliminary version of TCJA json

### PR DESCRIPTION
**Pull request by codykallen**
This PR adds a preliminary version of the JSON for the Tax Cuts and Jobs Act, as of the Chairman's mark on November 3. 

This JSON omits many changes to minor credits, exclusions and deductions that we cannot model at this time. Moreover, it is possible that more credits, exclusions and deductions will be limited or repealed in the new version of the bill set to be revealed on Monday, November 6. 

Note that this JSON also does not attempt to model the reduced pass-through rate and associated rules. Once the capability to model those policy changes has been added, I will update this JSON to apply the reduced `_PT_rt` rate parameters and the appropriate definitions of business income eligible for the reduced rates. 

If there are any provisions someone believes I missed (and which we are capable of modeling), please alert us to the needed changes. 

@MattHJensen @martinholmer @andersonfrailey @hdoupe @Amy-Xu @feenberg

### CODE REVIEW

**Comment by MattHJensen** [comment]
Thanks for the contribution, @codykallen. 

> Note that this JSON also does not attempt to model the reduced pass-through rate and associated rules. Once the capability to model those policy changes has been added, I will update this JSON to apply the reduced _PT_rt rate parameters and the appropriate definitions of business income eligible for the reduced rates.

Do you have a sense of timing on this step? 

In the meantime, I'd find it more natural to describe this JSON as not applying to pass thrus at all and leave those rates/brackets set at current law.

**Comment by MattHJensen** [comment]
cc @rickecon @evtedeschi3 @jdebacker

**Comment by codykallen** [comment]
@MattHJensen asked:

> Do you have a sense of timing on this step? In the meantime, I'd find it more natural to describe this JSON as not applying to pass thrus at all and leave those rates/brackets set at current law.

I'm currently working on implementing the PT eligibility rules. However, in the absence of completing that PR, I think the best option is to adjust the PT rates and brackets in tandem with the II rates and brackets.

**Comment by evtedeschi3** [comment]
Two questions and apologies for my ignorance here:

1) Is this JSON readable by taxcalc 0.12?

2) Relatedly, is there an up-to-date list of all the current policy parameters used in tc? Several of the ones here do not appear at [this link](http://open-source-economics.github.io/Tax-Calculator).

**Comment by MattHJensen** [comment]
@evtedeschi3 this JSON is not readable by taxcalc 0.12.0, but it will be readable by the next conda package. It is readable from Tax-Calculator master, which you can use by cloning the github repo and then:

from /tax-calculator run `python setup.py install`

from /tax-calculator/taxcalc/cli run `python tc.py —test` 

Then substitute `python tc.py` for `tc` in your workflow.

**Comment by MattHJensen** [comment]
@evtedeschi3, one other thing, you can see the latest parameters in Tax-Calculator master at https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/current_law_policy.json

**Comment by codykallen** [comment]
@MattHJensen, PR #1620 now adds the capability to apply the main definitions of business income eligible for the 25% maximum rate. If that PR (or a similar one) is merged, I will modify this JSON to reflect the improved capabilities).

**Comment by martinholmer** [comment]
@evtedeschi3 asked:
> Relatedly, is there an up-to-date list of all the current policy parameters used in tc? Several of the ones here do not appear at this link.

To ensure this, taxcalc developers should read issue #1626

**Comment by codykallen** [comment]
@GoFroggyRun asked

> Shouldn't the bracket for separate be 200,000 as well?

No, the text of the bill specifies the brackets for married filing separately as 1/2 of the amount for married filing jointly (or surviving spouse).

**Comment by codykallen** [comment]
Once the testing issue has been dealt with, and PR #1620 has been merged (or something similar), I'll update the `_PT_*` parameters to reflect the new PT taxation rules in the TCJA.

**Comment by codykallen** [comment]
The new commit adds the updates the `_PT_*` schedule parameters and adds the new PT rules from #1620. It also updates RELEASES.md to include the new PT eligibility rules added in #1620.

**Comment by MattHJensen** [comment]
@evtedeschi3 @rickecon @jdebacker: see updated JSON in this PR. This includes the pass thru rate reduction and guardrails, and it is (almost certainly) what we are going to release in taxcalc 0.13.0 tomorrow. You will need to pull master to use the new pass thru parameters.

**Comment by MattHJensen** [comment]
@codykallen, thanks very much for the contribution. Pending test passage, I will merge this PR.

**Comment by evtedeschi3** [comment]
The law calls for the refundable portion of the CTC (the Additional Child Tax Credit) to gradually grow (by chained CPI I believe) until it reaches $1,600 per child. Does this policy file address that in an indirect way that I'm not seeing?

**Comment by codykallen** [comment]
@evtedeschi3 said

> The law calls for the refundable portion of the CTC (the Additional Child Tax Credit) to gradually grow (by chained CPI I believe) until it reaches $1,600 per child. Does this policy file address that in an indirect way that I'm not seeing?

No, this reform file does not include that option, because we don't yet have the precise capability to model it. The closest you could probably come using the existing infrastructure would be to increase `_CTC_c` each year and decrease `_DependentCredit_Child_c` by the same dollar amount.

**Comment by evtedeschi3** [comment]
How hard would it be to add a parameter that controls the maximum refundable ACTC?

**Pull request merged**
