### PR TITLE
Strengthen testing of section-title consistency

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request expands the scope of testing the consistency of section titles in the `current_law_policy.json` and `docs/index.htmx` files.  

Part of these changes respond to the second question asked in issue #1633, which was:
> Also, is there a reason that we don't test that the `index.htmx` section headers conform to the `current_law_policy.json` section headers?

The more thorough testing revealed the need for some changes in section titles in both the `current_law_policy.json` and `docs/index.htmx` files.

There are no changes in tax logic or results in this pull request.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@martinholmer, why did you reverse the changes that I made in #1622 as part of this PR?

**Comment by martinholmer** [comment]
@MattHJensen asked:
> why did you reverse the changes that I made in #1622 as part of this PR?

Exactly which changes?

**Comment by MattHJensen** [comment]
> Exactly which changes?

All of the changes to current_law_policy.json of this PR (and the resulting changes in the docs) are reversals of changes I made in #1622.

**Comment by martinholmer** [comment]
@MattHJensen said:
> All of the changes to `current_law_policy.json` in this PR (and the resulting changes in the docs) are reversals of changes I made in #1622.

Sorry, my mistake was to begin by looking at TaxBrain, and your #1622 changes are not yet reflected there.
I think everything in `current_law_policy.json` is back to where it is on the master branch.

**Comment by MattHJensen** [comment]
Thanks a lot @martinholmer! The new test is great. +1

**Pull request merged**
