### PR TITLE
Add dropq

### PR DESCRIPTION
**Pull request by talumbau**
This pull request is to add all of the relevant code from the `drop-q` repository into Tax-Calculator. Time has shown that there can be problems when Tax-Calculator and dropq get out of sync.

Many Tax-Calculator users would be free to ignore this code, but changes in variable names and other fundamental changes in the Tax-Calculator code would cause the dropq tests to fail, so this will force the two to stay in sync.

This might need some additional work on reasonable tests, but I wanted to get the PR up, as the amount of code is significant.

### CODE REVIEW

**Comment by martinholmer** [comment]
@talumbau,  It's great that you've found time to integrate drop-q code into tax-calculator!

Is there still any need for these untest lines?
```
if groupby == "weighted_deciles":
        df = add_weighted_decile_bins(df2)
    elif groupby == "small_income_bins":
        df = add_income_bins(df2, compare_with="soi")  # <---- UNTESTED
    elif groupby == "large_income_bins":
        df = add_income_bins(df2, compare_with="tpc")  # <---- UNTESTED
    elif groupby == "webapp_income_bins":
        df = add_income_bins(df2, compare_with="webapp")
    else:
        err = ("groupby must be either 'weighted_deciles' or "
               "'small_income_bins' or 'large_income_bins' or "
               "'webapp_income_bins'")
        raise ValueError(err)
```
If there is no use of "small_income_bins" or "large_income_bins", can we just drop those lines?  If they are being used or might be used, then it would be best to add tests so that these two lines of code are covered by the unit tests.

**Comment by martinholmer** [comment]
@talumbau,  The merger of dropq into the Tax-Calculator repository would be very convenient for me this week.  Where do we stand on pending pull request #1015?

**Comment by talumbau** [comment]
I think I need to handle the issues you point out above and I'd also like to add a few additional tests. I can do all of that this week, probably by Wednesday.

**Comment by martinholmer** [comment]
@talumbau said:
> I think I need to handle the issues you point out above and I'd also like to add a few additional tests. I can do all of that this week, probably by Wednesday.

That would be great.  Thanks for this very helpful contribution.

**Comment by talumbau** [comment]
I believe this PR is now complete. I modified the testing to handle the untested lines mentioned by @martinholmer above. I also added a `requires_pufcsv` test to make sure that dropq gets a sane answer. The change in `get_sums` is an example of why it will be good to get these assets within Tax-Calculator! Any additional comments are welcome.

**Comment by martinholmer** [comment]
@talumbau said with respect to PR#1015 that integrates dropq into the Tax-Calculator repo:
> I believe this PR is now complete.  I modified the testing to handle the untested lines mentioned by @martinholmer above.  I also added a `requires_pufcsv` test to make sure that dropq gets a sane answer.  The change in `get_sums` is an example of why it will be good to get these assets within Tax-Calculator!  Any additional comments are welcome.

Thanks for this contribution!  Given this move of dropq logic into Tax-Calculator, are there any other places that Tax-Calculator variables are accessed or functions are called?  For example, does TaxBrain do any of that, or does it access Tax-Calculator indirectly via dropq?

**Comment by martinholmer** [comment]
Pull request #1015 ran just fine on my computer when I downloaded it.  Should I merge it?  @talumbau said it was complete, but #1015 still has an "In progress" label on it so I'm not sure it is complete.

**Comment by talumbau** [comment]
Ah, yes I see. That's due to a tool called [waffle.io](www.waffle.io) which we use to manage issues across all of the different OSPC repositories. The general progression of issues is "backlog", "ready", "in progress", "done." The tool will automatically add these labels sometimes (still working out exactly how that works), but overall it's a nice way to manage issues across repos. So, "in progress" is the last state before "done", and "done" is not applied to PRs until they are merged and closed. I do see how this can be confusing because one might want to indicate "I'm done" prior to merging the PR.

**Comment by martinholmer** [comment]
@talumbau said:
> Ah, yes I see. That's due to a tool called waffle.io which we use to manage issues across all of the different OSPC repositories. The general progression of issues is "backlog", "ready", "in progress", "done." The tool will automatically add these labels sometimes (still working out exactly how that works), but overall it's a nice way to manage issues across repos. So, "in progress" is the last state before "done", and "done" is not applied to PRs until they are merged and closed. I do see how this can be confusing because one might want to indicate "I'm done" prior to merging the PR.

So, should I merge #1015 because you are finished developing the pull request?

**Comment by talumbau** [comment]
yes this is done, let's merge.

**Pull request merged**
