### PR TITLE
Update documentation for pending release 0.20.0

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request includes updates to the `RELEASES.md` file as well as user documentation and cookbook updates for the next Tax-Calculator release.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Is `RELEASES.md` intended to cover downstream changes from C-TAM? For example I don't see https://github.com/open-source-economics/C-TAM/issues/66 in the 0.18.0 release or https://github.com/open-source-economics/C-TAM/issues/65 in the 0.19.0 release. If so, https://github.com/open-source-economics/C-TAM/issues/68 will also affect taxdata/taxcalc once fixed.

**Comment by martinholmer** [comment]
@MaxGhenis asked confusingly in the 0-20-0 branch about the 0.18.0 release:
> Is `RELEASES.md` intended to cover downstream changes from C-TAM? For example I don't see open-source-economics/C-TAM#66 in the 0.18.0 release or open-source-economics/C-TAM#65 in the 0.19.0 release. If so, open-source-economics/C-TAM#68 will also affect taxdata/taxcalc once fixed.

The TANF benefits fix was included in 0.19.0 as part of the CPS age variables fix:
screen shot 2018-04-25 at 7 30 11 pm


From the 0.18.0 release notes:
screen shot 2018-04-25 at 7 15 28 pm

**Comment by MaxGhenis** [comment]
I don't see the TANF PR (https://github.com/open-source-economics/taxdata/pull/178) mentioned in #1962. The housing wording sounded like a logic change rather than a data change (I'd actually forgotten that was the reason behind the low values, but it's been a while now).

It sounds like the answer to my question is yes, that `RELEASES.md` intends to cover taxdata and C-TAM. I find this update really useful to catch up on other issues I'm not following as closely, so I'd guess adding detail on data changes would benefit other users, especially those not subscribed to the taxdata and/or C-TAM repos.

**Comment by martinholmer** [comment]
@martinholmer said:
> The TANF benefits fix was included in 0.19.0 as part of the CPS age variables fix

Actually, it seems as if only part of the TANF benefits fix made it into Tax-Calculator 0.19.0.
The TANF benefits are fixed in the `cps.csv.gz` file but the fix in the `cps_benefits.csv.gz` was not included because that change was not merged into subsequent pending taxdata pull requests.

**Comment by martinholmer** [comment]
@MaxGhenis read this:

screen shot 2018-04-26 at 9 08 18 am

and the said:

> The housing wording sounded like a logic change rather than a data change 

I'm not sure how something listed under Bug Fixes that says the change was "in CPS data" can be interpreted as a "logic change."  If there were any questions in your mind, they would have been answered if you had clicked on the link to pull request #1941.  The links to the pull requests are there to provide more detail.

**Pull request merged**
