### PR TITLE
Use new growfactors.csv file to implement single-target extrapolation of benefits

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request changes Tax-Calculator logic to use the new `growfactors.csv` file generated by [taxdata pull request 271](https://github.com/open-source-economics/taxdata/pull/271).  These changes are part of a series of changes in the taxdata and Tax-Calculator repositories that will simplify the benefit extrapolation logic.  The reasons for undertaking this simplification have been discussed in [taxdata pull request 252](https://github.com/open-source-economics/taxdata/pull/252#issuecomment-405990257).

In this pull request we change the benefit extrapolation logic to be the same as the extrapolation logic for the `other_ben`, social security, unemployment insurance, and all other dollar-denominated Tax-Calculator input variables.  That logic is to assume that in each future year the sample filing units with a zero variable value continue to have a zero value and the sample filing units with a positive variable value continue to have a positive value, which is equal to the prior year's value multiplied by a growth factor (from the `growfactor.csv` file).  This means the unweighted count of filing units that have a positive variable value is unchanged from year to year.  However, the sampling weights (from the `???_weights.csv.gz` files) change from year to year, so that the weighted count of filing units that have a positive variable value does change from year to year.

This pull request also adds the benefit growfactors to the `growdiff.json` file and to the `growdiff.py` code, so that now benefit extrapolation assumptions can be changed by users using a JSON assumption file, which is not something that users could do before this pull request.

@MattHJensen @Amy-Xu @andersonfrailey @hdoupe

### CODE REVIEW

**Comment by martinholmer** [comment]
I'm hoping for some reviews of Tax-Calculator pull request #2041.
If people don't have time to review, I plan to meger #2041 in the afternoon of Friday (Aug 10).

@MattHJensen @Amy-Xu @andersonfrailey @hdoupe

**Comment by hdoupe** [comment]
@martinholmer Just to clarify, if a user wants to make changes to the the benefit parameters, then this PR will not require them to change the way they use Tax-Calculator unless they want to supply their own growfactors for the benefits. Is that correct?

**Comment by martinholmer** [comment]
@hdoupe asked:
> Just to clarify, if a user wants to make changes to the benefit parameters, then this PR will not require them to change the way they use Tax-Calculator unless they want to supply their own growfactors for the benefits. Is that correct?

Not sure I understand what you mean by "make changes to the benefit parameters."

But it is true that "this PR will not require them to change the way they use Tax-Calculator unless they want to supply their own growfactors for the benefits."   You question points out something that hadn't occurred to me: there was no way for a user to change the benefit extrapolation assumptions before this pull request; now there is a way (revise the benefit growfactors using the  `growdiff_baseline` and/or the `growdiff_response`  elements of an assumptions JSON file).

**Comment by hdoupe** [comment]
@martinholmer Sorry for not being clear. By "make changes to the benefits parameters", I was referring to updating them via the `implement_reform` method.

Thanks for clarifying. Everything looks good to me in #2041.

**Comment by martinholmer** [comment]
@hdoupe said:
> By "make changes to the benefits parameters", I was referring to updating them via the `implement_reform` method [of the Policy class].

Are there any benefit-related policy parameters?
There certainly are benefit-related assumption parameters, and you question made me notice I need to make more code changes to add the them to the GrowDiff class.  So, thanks for the review.  It was very helpful.

**Comment by hdoupe** [comment]
> Are there any benefit-related policy parameters?

That's what these are, right?
screen shot 2018-08-10 at 11 27 40 am

https://github.com/open-source-economics/Tax-Calculator/blob/0.20.1/taxcalc/current_law_policy.json#L6557-L6819

**Comment by hdoupe** [comment]
> So, thanks for the review. It was very helpful.

Sure, I'm glad I could help.

**Comment by hdoupe** [comment]
Great, thanks @martinholmer

**Pull request merged**
