### PR TITLE
Add parameter to exclude taxable interest income from AGI

### PR DESCRIPTION
**Pull request by Amy-Xu**
In this PR, one more haircut parameter is added for taxable interest income to exclude it from AGI and therefore regular tax. There're two relevant issues:

- Currently this parameter is named as `_ALD_Interest_HC`, which means above-the-line deduction haircut for interest income. But obviously interest income is not a deduction. On top of that, I'm not quite sure whether this is technically a haircut. Algebra is pretty simple for this parameter, but asking for naming advice. @MattHJensen @martinholmer @feenberg 

- @MattHJensen mentioned that all this kind of parameters would influence AGI amount. We want to maintain the AGI decile/bins the same as current law for easy comparison. To make sure our tables use the same set of AGI results, I'm going to create a new function calculating and storing current law AGI in a separate PR. Have not started to implement it yet. Welcome any comments/suggestions.

### CODE REVIEW

**Comment by martinholmer** [comment]
@Amy-Xu,  Pull request #435 passes all the unit test, but how about the validation/tests?  Is there no change in federal income tax liability when you run the validation/tests?  If not, are Tax-Calculator-versus-Internet-TAXSIM differences to be expected as a result of these changes?

**Comment by feenberg** [comment]
On Mon, 2 Nov 2015, Amy Xu wrote:

> 
> In this PR, one more haircut parameter is added for taxable interest income to exclude
> it from AGI and therefore regular tax. There're two relevant issues:
>
>  * 
>
>     Currently this parameter is named as _ALD_Interest_HC, which means above-the-line
>     deduction haircut for interest income. But obviously interest income is not a
>     deduction. On top of that, I'm not quite sure whether this is technically a
>     haircut. Algebra is pretty simple for this parameter, but asking for naming
>     advice. @MattHJensen @martinholmer @feenberg

I would call it an "exclusion". A haircut with a 100% rate would be an 
exclusion.

>
>  * 
>
>     @MattHJensen mentioned that all this kind of parameters would influence AGI
>     amount. We want to maintain the AGI decile/bins the same as current law for easy
>     comparison. To make sure our tables use the same set of AGI results, I'm going to
>     create a new function calculating and storing current law AGI in a separate PR.
>     Have not started to implement it yet. Welcome any comments/suggestions.
>

Aren't all current law parameters available already? How else do we 
calculate changes?

dan

**Comment by martinholmer** [comment]
@Amy-Xu,  OK, I now see that this is a REFORM parameter, so there will be no effect on results from the validation/tests, which all assume current-law tax policy.  Sorry for the confusion.

**Comment by MattHJensen** [comment]
> I would call it an "exclusion". A haircut with a 100% rate would be an
exclusion.

In this case, the user has the ability to apply a haircut with a 100% rate or a haircut with < 100% rate, so I believe using 'haircut' is more appropriate than 'exclusion'. 

What is confusing, however, is that in the other cases we apply a haircut to limit the benefit from an adjustment. E.g., setting the 'adjustment for student loan interest haircut' to 1 *increases* the taxpayer's liability. In the case of this interest haircut, however, increasing the haircut *reduces* the taxpayer's liability.

**Comment by MattHJensen** [comment]
@feenberg, is this a sensible sentence:  "50% of interest income is excluded"?, or more generally, "x% of interest income is excluded", where x<100?  

If those are sensible maybe we should call this an exclusion after all.

**Comment by feenberg** [comment]
On Tue, 3 Nov 2015, Matt Jensen wrote:

> 
> @feenberg, is this a sensible sentence: "50% of interest income is
> excluded"?, or more generally, "x% of interest income is excluded", where
> x<100?
> 
> If those are sensible maybe we should call this an exclusion after all.

I do think those are clear constructs. There is precident in the phrase 
"Foreign Income Exclusion" calculated on form 2555. There is some 
ambiguity about the difference between an exclusion and a deduction, and 
the FIE is now more like a credit, but still called an exclusion. Insiders 
talk about "above the line deductions" when they mean adjustments and 
exclusions, but that is rather a long bit of text when "exclusion" is 
available.

dan

**Comment by feenberg** [comment]
On Tue, 3 Nov 2015, Matt Jensen wrote:

>
>       I would call it an "exclusion". A haircut with a 100% rate
>       would be an
>       exclusion.
> 
> In this case, the user has the ability to apply a haircut with a 100% rate
> or a haircut with < 100% rate, so I believe using 'haircut' is more
> appropriate than 'exclusion'.

I would use "haircut" to signify the reduction in a credit based on 
income. So there might be a 1000 dollar child credit reduced by 100 for 
each 600 of AGI. The reduction would be called a "haircut".

Recall that long term gains were partially included in income, that was 
called the "capital gains deduction". I think we should reserve 
"deduction" for Schedule A items, though.

Credits with "clawbacks" are a new thing. "Clawback" is a good (if 
British) word for any reduction in a credit based on income. "Haircut" 
could be a synonym or we could reserve it for a percentage reduction in a 
credit (as opposed to a linear reduction).

dan

**Comment by MattHJensen** [comment]
@amy-xu, it seems like 'exclusion' is the right word to use for this PR. 

-----

On the usage of "haircut": 

@feenberg, we currently are using the term "haircut" to describe the "HC" parameters in the following snippet. 

    c02900 = (e03150 + (1 - ALD_StudentLoan_HC) * e03210 + e03600 +
              (1 - ALD_SelfEmploymentTax_HC) * e03260 +
              (1 - ALD_SelfEmp_HealthIns_HC) * e03270 +
              (1 - ALD_KEOGH_SEP_HC) * e03300 + (1 - ALD_EarlyWithdraw_HC) *
              e03400 + (1 - ALD_Alimony_HC) * e03500 + e03280 + e03900 +
              e04000 + e03700 + e03220 + e03230 + e03240 + e03290)

This does not conform with your suggestion above:

> I would use "haircut" to signify the reduction in a credit based on
income. So there might be a 1000 dollar child credit reduced by 100 for
each 600 of AGI. The reduction would be called a "haircut".

Do you have a suggestion for how we might rename the "HC" parameters in this snippet? 

cc @martinholmer @aviard

**Comment by feenberg** [comment]
On Tue, 3 Nov 2015, Matt Jensen wrote:

> 
> @amy-xu, it seems like 'exclusion' is the right word to use for this PR.
> 
> ______________________________________________________________________________________
> 
> On the usage of "haircut":
> 
> @feenberg, we currently are using the term "haircut" to describe the "HC" parameters
> in the following snippet.
> 
> c02900 = (e03150 + (1 - ALD_StudentLoan_HC) * e03210 + e03600 +
>           (1 - ALD_SelfEmploymentTax_HC) * e03260 +
>           (1 - ALD_SelfEmp_HealthIns_HC) * e03270 +
>           (1 - ALD_KEOGH_SEP_HC) * e03300 + (1 - ALD_EarlyWithdraw_HC) *
>           e03400 + (1 - ALD_Alimony_HC) * e03500 + e03280 + e03900 +
>           e04000 + e03700 + e03220 + e03230 + e03240 + e03290)
> 
> This does not conform with your suggestion above:
>
>       I would use "haircut" to signify the reduction in a credit based on
>       income. So there might be a 1000 dollar child credit reduced by 100 for
>       each 600 of AGI. The reduction would be called a "haircut".
> 
> Do you have a suggestion for how we might rename the "HC" parameters in this snippet?


I am stuck. I can't think of anything more suitable than HC.

dan

**Comment by MattHJensen** [comment]
@Amy-Xu, the right way to think about this parameter is that it allows the user to exclude all or part of interest income from taxable income, but interest income will still be taxed under NIIT if the user doesn't explicitly set the NIIT rate to zero and interest income will still be used in the determination of eitc eligibility. Are there any other quirks? Could you add this sort of info to the meta data in current_law_policy.json?

**Comment by feenberg** [comment]
What is NIIT?

dan

**Comment by Amy-Xu** [comment]
@feenberg NIIT is Net Investment Income Tax aka Unearned Income Medicare contribution

**Comment by Amy-Xu** [comment]
@MattHJensen Just changed the name and added a few notes. Could you take a look?

**Comment by MattHJensen** [comment]
Thanks @Amy-Xu, merging!

**Pull request merged**
