### PR TITLE
[WIP] Jit itemizer

### PR DESCRIPTION
**Pull request by talumbau**
This PR is a work in progress.

The first step has been completed, which is to replace the `@vectorize` implementation with an implementation that works with `@jit`. The next step is to provide a dummy implementation with `@jit` when it's not available (that is, numba is not installed). This is not too difficult. When this is done, `taxcalc` will have no hard dependency on numba, which is the goal of #659

### CODE REVIEW

**Comment by martinholmer** [comment]
T.J. (@talumbau),
Now that pull request #754 has been merged into the master branch, I think the Tax-Calculator code does not depend on the numba package.  That is because the cmbtp_itemizer code has been moved out of the Records class into the taxdata repository.  This move of cmbtp-calc logic seems to have two implications:

(1) This pull request #713 is no longer necessary.  If I'm right about that, you should close #713.

(2) Some cleanup work needs to be done.  When I grep for numba (after #754 is merged), I get this:
```
tax-calculator$ grep -r --include="*py" numba .
./docs/source/conf.py:MOCK_MODULES = ['numba', 'numba.jit', 'numba.vectorize', 'numba.guvectorize']
./taxcalc/decorators.py:from numba import jit, vectorize, guvectorize
./taxcalc/decorators.py:    to guvectorized numba functions
./taxcalc/decorators.py:    to vectorized numba functions
./taxcalc/decorators.py:            # print ("This should only be seen in RTD, if not install numba!")
./taxcalc/tests/test_decorators.py:from numba import jit, vectorize, guvectorize
./taxcalc/utils.py:    A sanity check decorator. When combined with numba.vectorize
```
Is there a need for any of this now?  If not, do you want to do the cleanup?  If you want me to do the cleanup, please give me some guidance so I don't do anything stupid.

@MattHJensen

**Comment by MattHJensen** [comment]
@martinholmer said:

> Now that pull request #754 has been merged into the master branch, I think the Tax-Calculator code does not depend on the numba package. 

@talumbau, is that your take as well? If so, does it mean this PR should be closed?

**Comment by talumbau** [comment]
yes. this PR is no longer needed. Closing.

**Comment by talumbau** [comment]
@martinholmer said:
> Is there a need for any of this now? If not, do you want to do the cleanup? If you want me to do the cleanup, please give me some guidance so I don't do anything stupid.

that code will still be needed. When there is no numba dependency, the code will just do a check for its existence and not use numba features if it's not there. Out of curiosity, do you know of a use case where someone is unable to use the Tax-Calculator right now because of its dependency on `numba`?

**Comment by MattHJensen** [comment]
I have wondered whether it could be useful to use Tax-Calculator with `numba` turned off to get nicer error messages.

**Comment by talumbau** [comment]
oh yes, that is a nice use case.

**Pull request closed without merging**
