### PR TITLE
Fixes tests failures for pr 563

### PR DESCRIPTION
**Pull request by MattHJensen**
@talumbau, could you review and merge if everything looks good? Where @Amy-Xu left off was good except for the test failure.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@Amy-Xu or @talumbau, please feel free to merge once you've checked that I didn't undermine any of @Amy-Xu's work.

**Comment by Amy-Xu** [comment]
`reform = {2015:{"_CTC_additional": [2500]}}` The results remain the same after this reform. Both _iitax and _combined decreased by 101.1 billion, and _fica remains the same.

Other than the typo T.J. pointed out in the previous PR. This looks good to me.

**Comment by MattHJensen** [comment]
@Amy-Xu and @talumbau, this one should be ready to go.

**Comment by talumbau** [comment]
LGTM. merging.

**Pull request merged**
