### PR TITLE
Add set_current_year method to Records class

### PR DESCRIPTION
**Pull request by martinholmer**
Also revise and add documentation for Records class.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@Amy-Xu, could you review this?

**Comment by Amy-Xu** [comment]
LGTM!

**Comment by martinholmer** [comment]
@Amy-Xu said:
> LGTM! Do we need to add a test for this new set_current_year() function to verify extrapolation's off?

I'm very bid on testing, but the simplicity of the set_current_year() method --- three lines of code --- seems to make it very clear that there is no step 1 or step 2 extrapolation as there is in the increment_year() method just above.  Seems as if adding a test is a bit of overkill, but maybe I'm missing something.
cc @MattHJensen

**Comment by MattHJensen** [comment]
@Amy-Xu, could you merge when you are ready?

**Comment by Amy-Xu** [comment]
LGTM. Merging.

**Pull request merged**
