### PR TITLE
Modifying the Imputation for Numextra 

### PR DESCRIPTION
**Pull request by GoFroggyRun**
Previously, before the cps matched version of 09 puf being available, we partially rely on `p04470` for the imputation of numextra, which sometimes yields unexpected values (more than 2, or non-integer, see #577 for details). 
`AGERANGE` variable itself is quite powerful in deciding whether a unit's elder or not. When it's not available (i.e. 0, which indicates Not Present according to 09 puf booklet), we use the `age` variable obtained from cps to determine whether filers are considered as elder or not. 

@MattHJensen @martinholmer @feenberg 
Any comments, concerns or remarks would be appreciated.

### CODE REVIEW

**Comment by martinholmer** [comment]
Sean,
How is it possible that this change in the ```_numextra``` imputation logic causes no changes in any of the tests?  If it doesn't cause a change in any test results, why are we making this change?

cc @GoFroggyRun @MattHJensen @feenberg

**Comment by GoFroggyRun** [comment]
@martinholmer Thanks for the reminder. I forgot to update the diff files.

**Comment by martinholmer** [comment]
Sean,  Adding the revisions in the ```requires_puf_csv``` tests makes the pull request look more sensible.

Are others comfortable with the new ```_numextra``` imputation logic?  If so, someone should merge this pull request into the master branch.   [We can't tell whether one member of a couple is elderly and the other is not, but that is because of a fundamental shortcoming of the data with which we are working.]

cc @GoFroggyRun @MattHJensen @feenberg

**Comment by martinholmer** [comment]
I verified the pull request #588 logic change in imputing ```_numextra``` as follows:
```
$ python
Python 2.7.11 |Anaconda 2.3.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
>>> from taxcalc import *
>>> ppo = Policy()
>>> rec = Records()
>>> calc = Calculator(policy=ppo, records=rec)
You loaded data for 2009.
Your data have been extrapolated to 2013.
>>> import numpy as np
>>> nelist = list(calc.records._numextra)
>>> len(nelist)
219814
>>> nelist.count(0)
191018
>>> nelist.count(1)
13675
>>> nelist.count(2)
15121
>>> nelist.count(3)
0
>>> quit()
$ 
```
Notice that the sum of the number of filing units with 0, 1, or 2 ```_numextra``` values is equal to the total number of filing units (219814).  This shows the incorrect values greater than two that were imputed by the prior logic have been eliminated.

Thanks for this contribution, Sean.

cc @GoFroggyRun @MattHJensen @feenberg

**Pull request merged**
