### PR TITLE
Add a nonrefundable credit for charitable giving

### PR DESCRIPTION
**Pull request by derrickchoe**
This pull request adds a number of parameters to `current_law_policy.json` related to the tax treatment of charitable giving. These parameters are designed to match the reforms detailed in the [2011 CBO report](https://www.cbo.gov/sites/default/files/112th-congress-2011-2012/reports/charitablecontributions.pdf) "Options for Changing the Tax Treatment of Charitable Giving."   We used these parameters in our [paper](http://www.aei.org/publication/charitable-giving-and-the-tax-cuts-and-jobs-act/) "Charitable Giving and the Tax Cuts and Jobs Act."

`"_CR_Charity_rt"` is a nonrefundable credit for charitable giving; taxpayers receive a credit equal to this rate multiplied by their total giving.

 I also added options for a "floor" on charitable giving eligible for a tax subsidy. This applies in both the case of an itemized deduction and a credit. This minimum threshold can be a fraction of AGI, or a dollar value. The option for a floor as a fraction of AGI was already available for the charitable deduction. 

The relevant parameters are:
`"_CR_Charity_frt"`: the charity credit floor rate
`"_CR_Charity_f"`: the charity credit dollar floor
`"_ID_Charity_f"`: the charity deduction dollar floor

### CODE REVIEW

**Comment by martinholmer** [comment]
@derrickchoe,
Thanks for contributing pull request #2037.  I'm currently involved in a move, so I will not be able to give #2037 a close review until sometime (early, hopefully) in August.  But right now I have a question and a request:

**Question:** why is "compatible_data" for "cps" equal to `false` for the new `_CR_Charity_rt` parameter?  Seems like changes in this parameter would affect income tax liability when using either PUF or CPS data.  Or am I missing something?

**Request:** can you exclude from your pull request the changes in `docs/index.html`?  We change the user documentation only when a new Tax-Calculator release is issued (not with each pull request).

**Comment by martinholmer** [comment]
@derrickchoe,  Also, could you add some tests that activate the new parameters introduced in #2037?

I know #2037 maintains (even slightly increases) the coverage rate, but it would be good to add one or more simple tests that exercise the new policy parameters.  A good place to do this would be at the end of the `taxcalc/tests/reforms.json` file, which is read by the `pre_release` `test_reform` function in the `test_reforms.py` file.

**Comment by martinholmer** [comment]
@derrickchoe said:
> I'll look into the `taxcalc/tests/reforms.json` file and add some tests for the charity credit parameters.

When you do this, there are ways to speed up your work.  Say you want to add a new test numbered 63: to execute just that new reform test (and not all the other tests), temporarily edit the `test_reform.py` file so it looks like this:
```
@pytest.mark.one
@pytest.mark.requires_pufcsv
# @pytest.mark.parametrize('rid', [i for i in range(1, NUM_REFORMS + 1)])
@pytest.mark.parametrize('rid', [63])
def test_reform(rid, baseline_2017_law, reforms_dict, puf_subsample):
```
Then execute just the new reform test 63 this way from the top-level directory in the repo:
```
$ cd taxcalc
$ pytest -m one
```
Also, be sure to reference the CBO results (that you mention earlier -- can't find the link) for one of the reforms you add.  See other tests for which there are comparison results.

Let me know if you have any questions.  I'd like do a final review and merge of your PR#2037 this week.

**Comment by derrickchoe** [comment]
@martinholmer 

Thanks for the tips regarding `test_reform.py`. I'm writing in the tests using the new charity reforms and I'm hoping to commit the changes for your review in the next couple of days.

In response to: 
> Also, be sure to reference the CBO results (that you mentioned earlier -- can't find the link) for one of the reforms you add.

The [CBO](https://www.cbo.gov/sites/default/files/112th-congress-2011-2012/reports/charitablecontributions.pdf) paper I've referenced contains estimates for the charitable giving responses to a number of reforms. While the paper was released in 2011, the estimates are for 2006 data. As such, we won't be able to make a direct comparison with taxcalc. Additionally, because we now estimate charitable giving responses using the `quantity_response` function, I'm not entirely sure how to incorporate this function into the `reforms.json`-- I imagine it'd require changing the `reform_results` function in `test_reforms.py`. If this is something you'd be interested in, I'm happy to help with modifying this file. I may also be mistaken, so please correct me if I'm wrong.

I appreciate all of your help as I acquaint myself with these files in tax calculator! Looking forward to getting your thoughts.

**Comment by martinholmer** [comment]
@derrickchoe said:
> The [CBO](https://www.cbo.gov/sites/default/files/112th-congress-2011-2012/reports/charitablecontributions.pdf) paper I've referenced contains estimates for the charitable giving responses to a number of reforms. While the paper was released in 2011, the estimates are for 2006 data. As such, we won't be able to make a direct comparison with taxcalc. Additionally, because we now estimate charitable giving responses using the `quantity_response` function, I'm not entirely sure how to incorporate this function into the `reforms.json` -- I imagine it'd require changing the reform_results function in `test_reforms.py`. If this is something you'd be interested in, I'm happy to help with modifying this file. I may also be mistaken, so please correct me if I'm wrong.

Are the CBO results from **static** analysis?  Or did they use some kind of charitable-giving response assumption?  If CBO did a static analysis with no behavioral responses, then your new test in `reforms.json` can do the same analysis and the results would be comparable to the CBO results (other than the year difference).

You're absolutely correct about the current version of the `test_reforms.py` logic not being able to handle behavioral responses via the `quantity_response` function, so the solution is to make all your new tests perform static (no response) analysis.  It's not fancy like the analysis in your paper, but it does exercise the new policy parameters.  Try to minimize the number of new tests because the reforms tests take quite a while to execute.

**Comment by derrickchoe** [comment]
@martinholmer 
In response to:
>Are the CBO results from static analysis? Or did they use some kind of charitable-giving response assumption? If CBO did a static analysis with no behavioral responses, then your new test in reforms.json can do the same analysis and the results would be comparable to the CBO results (other than the year difference).

The CBO paper uses behavioral assumptions (in this case, the price elasticity of charitable giving) in their analysis-- so it seems that we won't be able to make a direct comparison. 
>...so the solution is to make all your new tests perform static (no response) analysis. It's not fancy like the analysis in your paper, but it does exercise the new policy parameters. Try to minimize the number of new tests because the reforms tests take quite a while to execute.

Thanks for your input! I'll add a limited number of tests (one or two) that utilize the new parameters, and include them in my next commit.

**Comment by derrickchoe** [comment]
@martinholmer 

I just committed changes to my branch-- I fixed the issue with the `compatible_data` CPS field in one of the reform parameters I added.

Additionally, I've added a test to `taxcalc/tests/reforms.json` that replaces the charitable deduction with a nonrefundable 30% credit, subject to a floor of 0.5% of one's AGI. This is similar to one of the reforms included in the paper. So far, it looks like it's running as expected. A quick question-- should I be adding enough tests so that I activate every parameter I've added in this pull request? If so, I'm happy to quickly add those in.

Looking forward to getting your thoughts-- please let me know if there's anything else I can do to prepare this pull request for merging.

**Comment by martinholmer** [comment]
@derrickchoe said:
> Additionally, I've added a test to`taxcalc/tests/reforms.json` that replaces the charitable deduction with a nonrefundable 30% credit, subject to a floor of 0.5% of one's AGI. This is similar to one of the reforms included in the paper. So far, it looks like it's running as expected. A quick question-- should I be adding enough tests so that I activate every parameter I've added in this pull request? If so, I'm happy to quickly add those in.

I think this one extra test is just fine.  Thanks for adding it.
I'll do a final review when you're finished.  Let me know when the PR is ready for review.

**Comment by derrickchoe** [comment]
@martinholmer 

I've just looked over the pull request again, and I think everything is good to go on my end. If anything stands out to you, please let me know and I'll fix the code. Thanks for your help-- I'm glad that our paper's analysis led to these small additions to taxcalc (aside from your extremely helpful `quantity_response` function).

**Comment by martinholmer** [comment]
@derrickchoe,  When I make a local copy of your PR#2037, I get the following error when I run the new reform test (by doing `cd taxcalc ; pytest -m one ; cd ..`):
```
    @pytest.mark.one
    @pytest.mark.requires_pufcsv
    # @pytest.mark.parametrize('rid', [i for i in range(1, NUM_REFORMS + 1)])
    @pytest.mark.parametrize('rid', [63])
    def test_reform(rid, baseline_2017_law, reforms_dict, puf_subsample):
        """
        Compare actual and expected results for specified reform in reforms_dict.
        """
        reform_id = str(rid)
        actual = reform_results(reforms_dict[reform_id],
                                puf_subsample,
                                baseline_2017_law)
>       assert actual == reforms_dict[reform_id]['expected']
E       AssertionError: assert 'Tax-Calculat...2.5,-2.4,-2.2' == 'Tax-Calculato...1.3,-0.9,-0.7'
E         - Tax-Calculator,-2.8,-2.5,-2.4,-2.2
E         ?                 ^    ^ ^  ^ ^  ^ ^
E         + Tax-Calculator,-1.8,-1.3,-0.9,-0.7
E         ?                 ^    ^ ^  ^ ^  ^ ^
```
I don't understand why your expected results decline (in absolute value) as the years advance?
What's up?  Can you pass all the tests when you do `make pytest`?

**Comment by derrickchoe** [comment]
@martinholmer 
Thanks for bringing this up! I've just re-run the tests and I'm getting the same error. I think my problem was not including the `@pytest.mark.one` line originally.

I suspect that my issue stems from the fact that I'm using current law (rather than the 2017 law JSON) in my local notebook where I calculate the difference in total tax liability. I assumed that since the test runs from 2013-2016, there'd be no difference. 

I'll make some changes to my taxcalc notebook and see if it generates the expected results. I appreciate your patience! Sorry for missing this.

**Comment by martinholmer** [comment]
@derrickchoe said:
> I suspect that my issue stems from the fact that I'm using current law (rather than the 2017 law JSON) in my local notebook where I calculate the difference in total tax liability. I assumed that since the test runs from 2013-2016, there'd be no difference.

Why are you using a notebook?  Just run the one new test the way I explained.
We don't have time to do things inefficiently, so forget the notebook business.

**Comment by martinholmer** [comment]
@derrickchoe,  Can you edit the first comment to PR#2037 so that it includes a link to your paper using the new policy parameters?   Thanks.

**Comment by derrickchoe** [comment]
@martinholmer 

In response to:

> Why are you using a notebook? Just run the one new test the way I explained.

I should have clarified: I'm running the test from the terminal-- but I was using a notebook to compute the original difference in tax liability for years 2013-2016. I assumed that we get the `"expected"` results in `reforms.json` by manually generating calculator objects and comparing a baseline calculator to our reform calc. I was using a notebook for this purpose; I'm more than open to suggestion if there's a faster way to do this.

> @derrickchoe, Can you edit the first comment to PR#2037 so that it includes a link to your paper using the new policy parameters? Thanks.

I'm happy to edit the first comment-- thanks for the suggestion!

**Comment by martinholmer** [comment]
@derrickchoe said:
>  I assumed that we get the "expected" results in `reforms.json` by manually generating calculator objects and comparing a baseline calculator to our reform calc. I was using a notebook for this purpose; I'm more than open to suggestion if there's a faster way to do this.

Just run test 63 the way I showed you.

**Comment by derrickchoe** [comment]
@martinholmer 

Got it-- I'm getting the same error as you. Is the solution just to change the `expected` string to "Tax-Calculator,-2.8,-2.5,-2.4,-2.2"? I'm a bit confused as to why I'm not able to replicate these results using tax calculator itself, but I'm happy to make the changes and update the pull request!
image

**Comment by martinholmer** [comment]
@derrickchoe,  We have a policy of not including any notebooks in the repository.  Can you remove the notebook you just added to PR#2037?  Thanks.  I will not be able to merge it until your remove the notebook.

**Comment by martinholmer** [comment]
@derrickchoe said:
> I was using a notebook to compute the original difference in tax liability for years 2013-2016. 

That was your mistake because your specification of the new test 63 includes a `start_year` of 2017.  This means the test results are for 2017-2020.

**Comment by derrickchoe** [comment]
@martinholmer 

In response to: 
>@derrickchoe, We have a policy of not including any notebooks in the repository. Can you remove the notebook you just added to PR#2037? Thanks. I will not be able to merge it until your remove the notebook.

Sorry about that, I've removed it now! Thanks for letting me know.
>That was your mistake because your specification of the new test 63 includes a start_year of 2017. This means the test results are for 2017-2020.

That's my fault-- I changed the year from 2013 to 2017 to test if I was still getting an error. The test will still fail. I'm pushing the final changes where everything works.

**Comment by derrickchoe** [comment]
@martinholmer 

I appreciate your patience as I've figured my way around `test_reforms.py` and `reforms.json`. I believe everything is in working order now. The test year starts at 2013 and the expected (and actual) tax-calculator results are "Tax-Calculator,-2.8,-2.5,-2.4,-2.2"

I'll be sure not to fiddle around with the parameters so much in the future. I'm still having trouble recreating the results on my own in a separate notebook, but I'll raise that in a separate issue in the future.

**Comment by martinholmer** [comment]
@derrickchoe,  We're almost ready to merge #2037.  Just a couple of things to do:

1. As I said before, don't include in #2037 any changes to `docs/index.html`.  We do that for every release, not for every pull request.

2. Add a docstring to your new CharityCredit function in the `functions.py` file.  The `make cstest` is failing because the new function doesn't have a docstring.

3. In the `tests/test_reforms.py` file, make it say `NUM_REFORMS = 63` (not 62) so that your new reform test will be executed.

**Comment by martinholmer** [comment]
@derrickchoe,  Let's slow down a bit.  Please change the start_year for your new reform test 63 back to 2017.  
I never asked you to change it to 2013.  All the other reform tests start in 2017.

**Comment by derrickchoe** [comment]
@martinholmer 
In response to:
>@derrickchoe, Let's slow down a bit. Please change the start_year for your new reform test 63 back to 2017.
I never asked you to change it to 2013. All the other reform tests start in 2017.

In my original code, I had set the year to 2013-- the corresponding results from `test_reforms.py` were "Tax-Calculator,-2.8,-2.5,-2.4,-2.2" This was the original test that had failed.

Then I set the year to 2017, and the results were "Tax-Calculator,-2.0,-2.0,-2.0,-2.0"

I just wanted to give you a heads up as I change the year to 2017 and the `expected` string to "Tax-Calculator,-2.0,-2.0,-2.0,-2.0." On my machine, the test is passing now. 

>As I said before, don't include in #2037 any changes to docs/index.html. We do that for every release, not for every pull request.

Sorry about that-- I'm having trouble untracking that file. `git rm --cached docs/index.html` isn't working. Is there a better way to remove those changes?

I'll make the other changes you detail (along with changing the test year to 2017) and commit/push the new files.

**Comment by martinholmer** [comment]
@derrickchoe,  Thanks for all the work on this pull request.
These new charitable-giving policy parameters are a nice addition to Tax-Calculator.

I'll merge this after the tests finish on GitHub.

**Comment by derrickchoe** [comment]
@martinholmer 

I've removed the changes to `docs/index.html`. Sorry I didn't take care of it the first time-- I'll remember not to make any changes to the file in future pull requests.

Additionally, the test year for test 63 in `reforms.json` is set to 2017, and the test is passing on my machine. 

I've added a docstring to the `CharityCredit` function in `functions.py`.

I also set `NUM_REFORMS` to 63 in `test_reforms.py`. 

I appreciate your help throughout this PR! I've made note so that these mistakes don't slow down the process with future contributions to taxcalc.

**Comment by derrickchoe** [comment]
@martinholmer 
>@derrickchoe, Thanks for all the work on this pull request.
These new charitable-giving policy parameters are a nice addition to Tax-Calculator.
I'll merge this after the tests finish on GitHub.

Thanks very much! It probably isn't fun having to walk me through the ins-and-outs of these files, but it certainly is helpful to me. Happy to contribute-- hopefully my future work with tax calculator will yield more additions to the repo.

**Pull request merged**
