### PR TITLE
fix pandas import error by locking it and numpy versions

### LINKED ISSUE #661: ImportError: No module named 'pandas.compat.numpy_compat' when running tests
Following the [getting started guide](http://taxcalc.readthedocs.org/en/latest/contributor_guide.html), upon running `py.test -m "not requires_pufcsv"` a user is presented with 13 errors, all:

```
...\Miniconda3\envs\taxcalc-dev\lib\site_packages\pandas\__init.py:22: in (module)
     from pandas.compat.numpy_compat import *
E   ImportError: No module named 'pandas.compat.numpy_compat'
```

`pandas.compat.numpy_compat.py` was added to pandas in January 2016, whereas the version of pandas specified in `environment.yml` was released in June 2015. Why/how a pandas release from 2015 is requiring code that wasn't added until 2016, I have no idea. Hopefully someone can improve my understanding of the package distribution on this point.

However, if I remove the version constraint in environment.yml, pandas 0.18.0 installs successfully and all the tests pass (besides the unrelated one mentioned in #660). Is there current reason for the `<=0.16.2` constraint?

### PR DESCRIPTION
**Pull request by zrisher**
Fixes #661

### CODE REVIEW

**Comment by zrisher** [comment]
@talumbau Hold up on including this - it passes all the normal tests, but the pufcsv tests (run using the latest version of puf.csv) fail due to an error thrown from pandas. `ValueError: operands could not be broadcast together with shapes (219814
,) (249552,)`:


```
================================== FAILURES ===================================
__________________________________ test_agg ___________________________________

    @pytest.mark.requires_pufcsv
    def test_agg():
        """
        Test Tax-Calculator aggregate taxes with no policy reform using puf.csv
        """
        # create a Policy object (clp) containing current-law policy parameters
        clp = Policy()
        # create a Records object (puf) containing puf.csv input records
        puf = Records(data=PUFCSV_PATH)
        # create a Calculator object using clp policy and puf records
        calc = Calculator(policy=clp, records=puf)
        # create aggregate diagnostic table (adt) as a Pandas DataFrame object
>       adt = calc.diagnostic_table(num_years=10)

taxcalc\tests\test_pufcsv.py:45:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
taxcalc\calculate.py:368: in diagnostic_table
    calc.diagnostic_table_items(table)
taxcalc\calculate.py:294: in diagnostic_table_items
    agi = (self.records.c00100 * self.records.s006).sum()
C:\Dev\Miniconda3\envs\taxcalc-dev\lib\site-packages\pandas\core\ops.py:649: in
wrapper
    return left._constructor(wrap_results(na_op(lvalues, rvalues)),
C:\Dev\Miniconda3\envs\taxcalc-dev\lib\site-packages\pandas\core\ops.py:580: in
na_op
    raise_on_error=True, **eval_kwargs)
C:\Dev\Miniconda3\envs\taxcalc-dev\lib\site-packages\pandas\computation\expressi
ons.py:209: in evaluate
    **eval_kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

op = <built-in function mul>, op_str = '*'
a = array([   9.51567029,    9.91026208,    9.91026208, ...,  431.155307  ,
        245.910214  ,  469.040869  ])
b = array([  2.12557313e+05,   3.12281196e+07,   6.12817548e+07, ...,
         0.00000000e+00,   8.60475867e+03,   5.70845309e+03])
raise_on_error = True, eval_kwargs = {'reversed': True}

    def _evaluate_standard(op, op_str, a, b, raise_on_error=True, **eval_kwargs)
:
        """ standard evaluation """
        if _TEST_MODE:
            _store_test_result(False)
>       return op(a, b)
E       ValueError: operands could not be broadcast together with shapes (219814
,) (249552,)
```

And then of course we receive a later test failure since our results are not equal to those expected.

It seems we are not actually ready for the latest version of Pandas.

I'll be looking into this, but mostly trying to work around it for now. With my low level of familiarity with this repo and `pandas`, it seems like it will be slow going.

**Comment by zrisher** [comment]
@talumbau Ignore the additional bug I mentioned in my previous post - that turned out to be unrelated to pandas version. I'm guessing that if master runs the puf.csv tests for you fine now, it should also work well with this PR.

**Comment by zrisher** [comment]
@talumbau @martinholmer Could we merge this PR? Works great for me still, no conflicts and all tests passing.

**Comment by martinholmer** [comment]
@zrisher, Thanks for the contribution.  These are the numpy and pandas versions I'm using and they seem to be the most recent versions of those packages.

**Pull request merged**
