### PR TITLE
No numba dependency

### PR DESCRIPTION
**Pull request by talumbau**

### CODE REVIEW

**Comment by talumbau** [comment]
I need another commit here to deal with Codecov issues, but I wanted to point out that running the tests w/o `numba` makes the test cycle with Travis CI about 13 minutes along, instead of about 3 with `numba`. I don't consider this a big deal but I thought I should point it out as something to consider for this PR.

cc @Amy-Xu @GoFroggyRun @MattHJensen @martinholmer

**Comment by martinholmer** [comment]
T.J. said:
> I need another commit here to deal with Codecov issues, but I wanted to point out that running the tests w/o numba makes the test cycle with Travis CI about 13 minutes along, instead of about 3 with numba. I don't consider this a big deal but I thought I should point it out as something to consider for this PR.

This is a VERY HIGH COST to pay.  Can you explain why all six versions of the tests need to be run after every commit to a pull request?  Maybe the BENEFITS from this enhancement are greater than this high cost.  Can you provide us a benefit-cost analysis that shows why this should be the way things should be in the future?

@MattHJensen @talumbau @GoFroggyRun @Amy-Xu @zrisher

**Comment by martinholmer** [comment]
@talumbau, Pull request #799 also has a noticeable decline in code coverage.  What caused this?

@MattHJensen

**Comment by talumbau** [comment]
Not all combinations of Python {3.4, 3.5, 2.7} X {with numba, without numba} have to be run. It's just the default. It can be changed to whatever we want. However, all the versions typically start within a few seconds of each other, so even if we just picked one to run with each PR, say "Python 2.7 w/o numba", that one would take about 12-13 minutes, so the overall Travis CI run time would not be reduced by much, if any. 

I thought this was a desired feature - that is, to make the code runnable without numba. Is that incorrect? The alternative would be to not test the code without numba, but that seems like a bad idea. Consider the case of debugging some issue that is giving a numba error. A developer would like to understand if the issue is really a problem in numba or in their own code. So, the developer runs their latest code without numba. If we are not testing without numba, you could not have the expectation of what should happen at that point. In other words, you might hit an error, but you wouldn't know if the error was already sitting in master, or if it is because of your code changes.

**Comment by talumbau** [comment]
@martinholmer Code coverage is good to go. There were initially 4 untested lines in utils.py, but that function is no longer used so I removed it. The two package-level .py files (utils.py and decorators.py) both remain at 100% coverage, as you can see in the updated report:


https://codecov.io/gh/open-source-economics/Tax-Calculator/compare/8314d09bb989c105b0da6a33fc5f597b71ff52b9...ea5f4b39b939a134178ec71e1920d330dfe1e6c0

(the Codecov report at the top of this PR is based on the initial commits)

**Comment by martinholmer** [comment]
@talumbau said:
> Not all combinations of Python {3.4, 3.5, 2.7} X {with numba, without numba} have to be run. It's just the default. It can be changed to whatever we want. However, all the versions typically start within a few seconds of each other, so even if we just picked one to run with each PR, say "Python 2.7 w/o numba", that one would take about 12-13 minutes, so the overall Travis CI run time would not be reduced by much, if any.

So, you're saying the six tests run in parallel, right?  And the 12-13 minutes is just the Tax-Calculator running at normal Python-interpreted speed, right?

If my understanding above is correct, then I would hope the without-numba tests could be made optional.  Your point about needing the without-numba tests when debugging is valid, but most of the pull-request commits are not doing debugging.  I don't know enough about how Travis-CI works to know if the without-numba tests can be run only when requested.

@MattHJensen @GoFroggyRun @Amy-Xu @zrisher

**Comment by talumbau** [comment]
> So, you're saying the six tests run in parallel, right? And the 12-13 minutes is just the Tax-Calculator running at normal Python-interpreted speed, right?

Yes and yes.

> If my understanding above is correct, then I would hope the without-numba tests could be made optional. Your point about needing the without-numba tests when debugging is valid, but most of the pull-request commits are not doing debugging. I don't know enough about how Travis-CI works to know if the without-numba tests can be run only when requested.

The point about debugging is more about how one would reason about the code if a problem occurred at some point in the future. So for example, when debugging https://github.com/open-source-economics/Tax-Calculator/issues/405, a first step would have been to run the code w/o numba (if such a feature had been available at the time), hoping to get a clean test report. This would prove that the real trouble in that issue was numba behavior. However, unless we test w/o numba in each merge to master, we would not know what to expect when running the tests w/o numba in the future.

But, there is always a balance to be struck on these issues. This is a good problem to have (deciding time per testing cycle vs. amount of testing per PR). 

I have a suggestion on how to proceed based on a brand new Travis CI feature - [cron jobs](https://docs.travis-ci.com/user/cron-jobs/)! This was just launched last month and it seems like the right answer for our issue. My suggestion is that we run the "without numba" tests every night and keep the current tests on all PRs the same. So, if something got in to master that makes the test fail w/o numba, we would know by the next morning that something bad happened the previous day. How does that sound?

**Comment by martinholmer** [comment]
@talumbau said:
> But, there is always a balance to be struck on these issues. This is a good problem to have (deciding time per testing cycle vs. amount of testing per PR).
>
> I have a suggestion on how to proceed based on a brand new Travis CI feature - cron jobs! This was just launched last month and it seems like the right answer for our issue. My suggestion is that we run the "without numba" tests every night and keep the current tests on all PRs the same. So, if something got in to master that makes the test fail w/o numba, we would know by the next morning that something bad happened the previous day. How does that sound?

Your suggestion is brilliant!   I'm all in favor of that approach.

@MattHJensen

**Comment by Amy-Xu** [comment]
Sounds great! 👍

**Comment by MattHJensen** [comment]
@martinholmer said: 

> Your suggestion is brilliant!

@Amy-Xu said:

> Sounds great! 👍

Agreed!

**Comment by martinholmer** [comment]
T.J., While you're working in the `test_decorators.py` file, don't forgot issue #780.

@talumbau  @MattHJensen

**Comment by talumbau** [comment]
OK, this PR does as follows now:

 - removes Numba as a hard dependency from Tax-Calculator
 - tests w/o Numba in Travis CI cron jobs which run daily and not connected to a PR so we will get a notification if they fail but PRs still test fast
 - adds test coverage to `decorators.py` (not 100% but a marked improvement)

**Comment by MattHJensen** [comment]
Thanks @talumbau! This looks good to me. 

cc @martinholmer @GoFroggyRun

**Comment by martinholmer** [comment]
@talumbau,  Thanks for finding a solution to the long no-numba test run times.
Shall I go ahead and merge this pull request #799 into the master branch?

@MattHJensen

**Comment by talumbau** [comment]
I'll merge now. It appears that cron jobs are running at 10am Central time daily, so I'm curious to see if this will run as expected.

**Comment by martinholmer** [comment]
@talumbau said:
> I'll merge [#799] now. It appears that cron jobs are running at 10am Central time daily, so I'm curious to see if this will run as expected.

What?  I thought your idea was to run the cron jobs in the middle of the night?  Why run them during the business day?

@MattHJensen

**Comment by talumbau** [comment]
The interface for this new Travis CI feature is minimal. the options for how to run the cron jobs are just "monthly, weekly, daily". When I turned the feature on, I picked "daily". I assumed there would be an additional config to set the time. Apparently, it uses the current time when the job is created as the start time for the daily job. There is no interface element to pick the time of day. It's been running this way for the last week, although obviously the cron job was running exactly the same way as our normal PRs. This will be the first time it is doing something differently.

**Comment by martinholmer** [comment]
@talumbau said:
> The interface for this new Travis CI feature is minimal. the options for how to run the cron jobs are just "monthly, weekly, daily". When I turned the feature on, I picked "daily". I assumed there would be an additional config to set the time. Apparently, it uses the current time when the job is created as the start time for the daily job. There is no interface element to pick the time of day. It's been running this way for the last week, although obviously the cron job was running exactly the same way as our normal PRs. This will be the first time it is doing something differently.

Thanks for the explanation.  Maybe they will add more flexibility sometime in the future.

**Pull request merged**
