### PR TITLE
Add iPython notebooks on Better Way reform (Ryan-Brady plan)

### PR DESCRIPTION
**Pull request by codykallen**
If agi - ided > 0, delta_income = delta_wage + delta_oinc - delta_ided. I corrected the assert statement to reflect that. 
If agi > 0 but agi_m_ided < 0, then delta_wage=delta_oinc=delta_ided=0 but delta_income != 0. I changed the order of commands and set delta_income=np.where(agi_m_ided>0, taxinc_change, 0.)

These changes eliminate the assertion errors in this function.

### CODE REVIEW

**Comment by Amy-Xu** [comment]
@martinholmer @MattHJensen Cody found this assertion error when he used the substitution and cap gain behavior functions. Could you review?

@martinholmer Just in case you haven't met Cody yet, he's a new RA at AEI, mainly focusing on tax policy.

**Comment by martinholmer** [comment]
@codykallen,  Thanks for your proposed fix of logic in the behavior.py _update_ordinary_income function.  Also, welcome to the OSPC team!

What we need is a new test in taxcalc/tests/test_behavior.py that fails on the master branch and passes with your fix of the behavior.py code.  Your notebook will never be run by the Travis-CI system that runs our unit tests with ever GitHub commit.  So, drop the notebook from this pull request and add the simplest code that triggers the assertion error you came across as a new test in test_behavior.py.

Does that make sense?  If not, feel free to ask questions here.

@MattHJensen @Amy-Xu

**Comment by martinholmer** [comment]
@codykallen,  I have fixed in pull request #846 the two bugs you reported in pull request #824.

Thanks again for reporting these two bugs and suggesting coding changes that would fix them.

What you need to do with your intro1 branch is to (1) revert the changes in behavior.py and (2) merge the newest master branch (after syncing with GitHub) into your intro1 branch.  Doing those two things will give you #846 and many other recent improvements on the master branch.

Do step (1) with the following command:
```
git checkout -- taxcalc/behavior.py
```
Do step (2) with the following command:
```
git merge master
```

@MattHJensen @Amy-Xu @GoFroggyRun

**Comment by martinholmer** [comment]
@codykallen, Now that pull request #846 has been merged into the master branch, you should change the name of pull request #824.  Perhaps something like: "Add iPython notebook on Better Way reform".

@MattHJensen

**Pull request closed without merging**
