### PR TITLE
Add FIPS State Codes to CPS

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR complements PR [#126](https://github.com/open-source-economics/taxdata/pull/126) in the TaxData repo. It adds the FIPS state code associated with each tax unit in the CPS file.

cc @MattHJensen

### CODE REVIEW

**Comment by MattHJensen** [comment]
LGTM and merging once checks complete. Thanks @andersonfrailey.

Needs caveated documentation in `index.html` @andersonfrailey.

**Comment by andersonfrailey** [comment]
Fixing those tests.

**Comment by andersonfrailey** [comment]
Seems like the test failure is due to rounding error. I looked and each error was .1, which is why it failed on 2.7 but not 3.6. I updated the CPS expected text file so that it would pass both.

**Comment by MattHJensen** [comment]
> Seems like the test failure is due to rounding error. I looked and each error was .1, which is why it failed on 2.7 but not 3.6. I updated the CPS expected text file so that it would pass both.

Do you know why the results changed at all? I would have thought there'd be no change.

**Comment by MattHJensen** [comment]
Merging, but would still like a followup on why the tests changed at all.

**Pull request merged**
