### PR TITLE
Reorganize parameters -- will facilitate TaxBrain updates

### PR DESCRIPTION
**Pull request by MattHJensen**
In #1074, I described several disconnects between TaxBrain and current_law_policy.json:

> 
> 1. Sections and subsections
> - TB is organized by sections and subsections, (e.g Refundable Credits: EITC), whereas `current_law_policy.json` parameters are only informally grouped into sections by reference in the title name. 
> 
> 2. Order of the parameters. 
>   - TB is ordered roughly by where the params appear in the tax forms, while TC's `current_law_policy.json` is roughly ordered by where the parameters appear in `taxcalc/functions.py.`
> 
> 3. "Principle" parameters 
> - The TB input page does not include every parameter from `current_law_policy.json`, rather it only includes parameters of principle importance. 
> 
> 4. 1-2 relationships between TB fields and TC params
> - Two sets of fields on the TaxBrain input page have a 1-2 relationship with parameters in Tax-Calculator. 
>     - The personal income tax rate and brackets fields on TaxBrain govern both `II_rt`s and `II_brk`s as well as `PT_rt`s and `PT_brk`s
>     - the long term capital gains and qualified dividends fields on TaxBrain govern both `CG_rt`s and `CG_bk`s as well as `AMT_CG_rt`s and `AMT_CG_brk`s.
> 

This PR resolves those disconnects by 

1. Adding `section_1`, `section_2`, and in some cases `section_3` fields that specify the conceptual relationship among parameters and therefore how they ought to be grouped on TaxBrain. 

2. Sorting the parameters in current_law_policy.json to be easier to use.  (I have not written down/formalized this schema, but I hope it will be fairly easy to stick to by looking at the examples). 

3. Specifying which parameters *should not* be included in TaxBrain by leaving off the section fields. My intent was to include every parameter on TaxBrain, but some have not received any attention for a long time, and I figure they might need to be dusted off. 

4. Updating the names and descriptions of parameters such as II_rts and PT_rts to make their relationships more obvious and thereby allow us to do away with the 1-2 relationships between TaxBrain inputs and Tax-Calculator parameters.

One of the core motivations for this project is to get to the point where we can fully specify the content and layout of the TaxBrain input page's tax-law parameters with the information in current_law_policy.json plus a set of translation rules. Once that is done, then the tax-calculator team should be able to trigger changes (whether manual or automated) to the TaxBrain input page by making a change to `current_law_policy.json`. @talumbau @PeterDSteinberg @brendancol  I'd particularly appreciate feedback on that aspect of the project and which additional steps might be needed. 

cc, @martinholmer, @feenberg, @GoFroggyRun, @zrisher, @codykallen, @andersonfrailey, @Amy-Xu

### CODE REVIEW

**Comment by MattHJensen** [comment]
The standard deduction max for dependents used to be tacked on to _STD. I just added a commit to separate it into its own parameter that can be displayed on TaxBrain.

**Comment by MattHJensen** [comment]
@talumbau told me on the phone that TB updates would be easier if we point out parameter name changes whenever they occur:

This PR renames `_KT_c_Age` as `_AMT_KT_c_Age` and modifies `_STD` by separating _STD[6] into a new parameter `_STD_Dep`. 

I believe that neither `_KT_c_Age` nor `_STD[6]` are currently used on TaxBrain.

**Comment by MattHJensen** [comment]
This contains no breaking changes and does not influence tax logic. I hope to merge at the end of the day tomorrow.

**Comment by talumbau** [comment]
Just a quick note to say that the Appveyor 'X' here is not a problem. Now that Appveyor is turned on, it will try to build all PRs. Until #1111 is merged, it won't have the proper scripts (or the fix that makes the tests fail on Windows)

**Comment by martinholmer** [comment]
@MattHJensen, pull request #1109 look good to me.
Thanks for these changes that promise to make it easier for TaxBrain to keep up with changes in Tax-Calculator.

**Comment by MattHJensen** [comment]
Thanks @zrisher, @martinholmer, @feenberg (for comments on the original issue), and @talumbau (for comments on the phone). Merging.

**Pull request merged**
