### PR TITLE
Added Marginal Tax Rate Plotting Function

### PR DESCRIPTION
**Pull request by GoFroggyRun**
This PR extracted and modified the mtr plotting function inside a notebook wrote by @MattHJensen. 

The `create_mtr_graph` function allows users to customize the mtr plots with various options: 

1. Plotting one mtr graph or two mtr graphs, where a legend will be created in this case .
2. Choosing from MARS groups.
3. Choosing from weight measures.
4. Choosing from income measures. 
5. Specifying the ceiling of number of kid for each record.
6. Specifying the floor of number of kid for each record.
7. Choosing from mtr measures. 

The following plots show how the graph would look like, with or without a legend: 
screen shot 2016-03-31 at 2 30 58 pm
screen shot 2016-03-31 at 2 30 50 pm

Any comments, concerns or remarks would be appreciated. 
@martinholmer @MattHJensen @Amy-Xu @talumbau

### CODE REVIEW

**Comment by martinholmer** [comment]
@GoFroggyRun,

It would be helpful to have on the graph an indication of the specified mtr concept, income type, MARS group, etc.

Also, might want to label the two axes to clarify the meaning of the graph for anybody other than the person who generated the graph.

**Comment by GoFroggyRun** [comment]
@martinholmer,

Thank you for your comments. I have modified the function, and now the plots look like this:

screen shot 2016-03-31 at 9 16 42 pm
screen shot 2016-03-31 at 9 16 29 pm

Does this seem like something you have in your mind? Let me know what your thoughts are.

**Comment by martinholmer** [comment]
@GoFroggyRun said:
> Does this seem like something you have in your mind? Let me know what your thoughts are.

Yes, this is now much clearer for people who didn't make the graph and clearer to the maker of several graphs who comes back to a collection of graphs made days or weeks ago.

I would suggest one more minor change: instead of "Income bins (xxxxx)" why not "Income percentiles (xxxxx)"?  That makes it clear how the bins are defined.

**Comment by GoFroggyRun** [comment]
@martinholmer:

I just changed "Income bins (xxxxx)" to "Income percentiles  (xxxxx)":
screen shot 2016-04-01 at 10 12 45 am
screen shot 2016-04-01 at 10 12 38 am

I am, however, somewhat confused by the Travis CI test. Although all tests passed on my end, I'm having the error messages on the remote saying that:
```
   import matplotlib
E   ImportError: No module named matplotlib
```
Do you have any ideas why this is happening? Please advice.

**Comment by martinholmer** [comment]
@GoFroggyRun said:
> I am, however, somewhat confused by the Travis CI test. Although all tests passed on my end, I'm having the error messages on the remote saying that:
>
> ```
>import matplotlib
>E   ImportError: No module named matplotlib
> ```
>
> Do you have any ideas why this is happening? Please advise.

I don't know about this.  Probably best to ask T.J.

On my (Mac) computer the ```conda list | grep plot``` command shows this:
```matplotlib                1.4.3                np19py27_2    defaults```

So, maybe T.J. needs to specify the inclusion of ```matplotlib``` as part of the conda environment on Git Hub that runs the Travis CI check-in tests.  This is just a guess.

@talumbau @MattHJensen

**Comment by GoFroggyRun** [comment]
Closing this PR as we will be using Bokeh package, instead of matplotlib package, for plotting.

**Pull request closed without merging**
