### PR TITLE
Modified to allow separate taxation of pass-through income

### PR DESCRIPTION
**Pull request by codykallen**
Created a new function ptTaxer to separate taxable income into pass-through (Schedule C sole proprietorship and Schedule E partnership and S-corporation) income from other income and tax them separately. 

Modified XYZD to call ptTaxer instead of Taxer_i if pt_special != 0

Created 2 new parameters in current_law_policy.json for pass-through taxation.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@codykallen, thank you very much for the contribution! This is a very important feature.  

The instructions in Tax-Calculator's README file will help you get the tests passing. Once they are, I'm hoping @martinholmer will offer his feedback on your work. 

I am interested in others' opinion on whether there should be a whole new set of brackets for the pass thru rate structure. Currently in this PR, there is not.

**Comment by MattHJensen** [comment]
@codykallen, I'm aware that you made some back of the envelope calculations for another project. How do these micro-simulated estimates compare?

**Comment by codykallen** [comment]
This implementation increased the annual cost of the entire reform by about $4 billion. This seems pretty reasonable to me.

**Comment by MattHJensen** [comment]
> This implementation increased the annual cost of the entire reform by about $4 billion. This seems pretty reasonable to me.

Thanks @codykallen. Do you have the cost of the single provision before and after?

**Comment by codykallen** [comment]
No, I just included it in the income tax rate reform. But I can calculate that separately if you prefer.

**Comment by MattHJensen** [comment]
> No, I just included it in the income tax rate reform. But I can calculate that separately if you prefer. 

I think that would be helpful. It would allow us to know how different the microsimulation is form the back of the envelope in percent terms.  But why don't you work on getting the tests passing first so that others can review and offer feedback on the implementation in the meantime.

**Comment by codykallen** [comment]
Three of the tests fail.

test_force_no_numba refers to something that does not exist and is not relevant to taxcalc’s functionality.

test_function_args_usage fails because pTaxer is never called. This is intentional in my design, so that a user who want to change income tax rates does not have to change them for regular and pass-through income.

test_var_labels_contents fails because I added 10 variables to the list VALID_READ_VARS. These are necessary because the taxcalc fails if these variables are not included in that list. They were removed in a recent pull request.

**Comment by MattHJensen** [comment]
@codykallen, for the PEP8 errors, I use [this package](https://github.com/SublimeLinter/SublimeLinter-pep8) to highlight PEP8 errors in Sublime.

Note that you will need to install SublimeLinter as well (see the readme from SublimeLinter-pep8)

You will also want to add project settings to ignore PEP8 error E402 — directions also in the readme. 

I did this recently and am happy to help if you run into any trouble.

**Comment by MattHJensen** [comment]
> test_var_labels_contents fails because I added 10 variables to the list VALID_READ_VARS. These are necessary because the taxcalc fails if these variables are not included in that list. They were removed in a recent pull request.

I believe this problem stems from us not getting you the latest version of the PUF. Sorry about that! Just sent a link via email. (we don't share those links here because the data are highly sensitive). 

I believe this PR to your fork and active branch will resolve the other test failures: https://github.com/open-source-economics/Tax-Calculator/pull/858

**Pull request merged**
