### PR TITLE
add under5 bonus to ctc_new

### LINKED ISSUE #1054: expand CTC_new to include an under5_bonus
Samuel Hammond and Robert Orr have a recent Niskanen Center paper, "[Toward a Universal Child Benefit](https://niskanencenter.org/wp-content/uploads/2016/10/UniversalChildBenefit_final.pdf)", that analyzes two CTC proposals. 

> Our first estimate is our preferred structure: a fully refundable $2000 child tax credit for any child under 18. Our second estimate is also fully refundable, but matches the rates of Clinton’s proposal: $2000 children ages 0 to 4, and $1000 for children ages 5 to 17.

To analyze the first proposal, I'll use the CTC_new capabilities that @martinholmer contributed recently. In order to accomodate the full refundability, I plan to set CTC_new_refund_limit_rt, which is the percentage of payroll taxes the credit can be refunded against, to infinity. 

To analyze the second proposal, I also plan to use the CTC_new capabilities, but I will need to add an under5_bonus to the credit amount.

### PR DESCRIPTION
**Pull request by MattHJensen**
fixes #1054 

Leaving WIP tag until I have a chance to generate and post reform results.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@martinholmer, could you please review these changes that address your recent [comment](https://github.com/open-source-economics/Tax-Calculator/issues/1054#issuecomment-259979645) on #1054: 
image

I added a boolean for applying a refund limit to ctc_new in order to allow users to turn off the refund limit. An alternative approach would have been to add a tiny amount to payroll taxes when the limit is calculated, but I think that would have been counterintuitive for users who are savvy enough to expect the refund_limit_payroll_rt to have no effect on taxpayers with no payroll tax liability. 

The boolean approach also allows for other forms of limits to be added in the future. 

I renamed `_CTC_new_refund_limit_rt` to `_CTC_new_refund_limit_payroll_rt` to account for that possibility as well and generally to be more explicit about the purpose of the param. 

I also turned  `_CG_nodiff` into a boolean to match `_ID_BenefitSurtax_Switch`. I'm not aware of any strong benefits of using booleans versus 1/0 indicators in these cases. 

cc @talumbau in case he has some input on the boolean vs. 1/0 indicator issue.

**Comment by MattHJensen** [comment]
Here are a few reform results

# Test CTC_new Expansion Capabilities

### Import taxcalc package and other useful packages


```python
import sys
sys.path.append("../../")
from taxcalc import *
```

### Create Plan X and Plan Y  Policy objects containing current law policy and then implement reforms


```python
# The baseline includes AMT repeal. 
p_xx = Policy()

p_y1 = Policy()
reform1 = {2016: {
'_CTC_new_rt': [1],
'_CTC_new_c': [2000],
'_CTC_new_prt': [0.05],
'_CTC_new_ps': [[75000, 110000, 55000, 75000, 75000, 55000]]
}}
p_y1.implement_reform(reform1)

p_y2 = Policy()
reform2 = {2016: {
'_CTC_new_rt': [1],
'_CTC_new_c_under5_bonus': [1000],
'_CTC_new_c': [1000],
'_CTC_new_prt': [0.05],
'_CTC_new_ps': [[75000, 110000, 55000, 75000, 75000, 55000]]
}}
p_y2.implement_reform(reform2)

p_y3 = Policy()
reform3 = {2016: {
'_CTC_c': [0],
'_CTC_new_rt': [1],
'_CTC_new_c': [2000],
'_CTC_new_prt': [0.05],
'_CTC_new_ps': [[75000, 110000, 55000, 75000, 75000, 55000]]
}}
p_y3.implement_reform(reform3)
```

### Create calculator objects with default tax data and advance the calculator to 2020


```python
c_xx = Calculator(policy=p_xx, records=Records("../../puf.csv"))
c_xx.advance_to_year(2020)
c_y1 = Calculator(policy=p_y1, records=Records("../../puf.csv"))
c_y1.advance_to_year(2020)
c_y2 = Calculator(policy=p_y2, records=Records("../../puf.csv"))
c_y2.advance_to_year(2020)
c_y3 = Calculator(policy=p_y3, records=Records("../../puf.csv"))
c_y3.advance_to_year(2020)
```

    You loaded data for 2009.
    Your data include the following unused variables that will be ignored:
      filer
    Your data have been extrapolated to 2013.
    You loaded data for 2009.
    Your data include the following unused variables that will be ignored:
      filer
    Your data have been extrapolated to 2013.
    You loaded data for 2009.
    Your data include the following unused variables that will be ignored:
      filer
    Your data have been extrapolated to 2013.
    You loaded data for 2009.
    Your data include the following unused variables that will be ignored:
      filer
    Your data have been extrapolated to 2013.


### Calculate taxes under the baseline and under the reform. 


```python
c_xx.calc_all()
c_y1.calc_all()
c_y2.calc_all()
c_y3.calc_all()
```

### Calculate the change in combined payroll and individual income tax revenue between the baseline and reform

### Reform 1

```python
((c_y1.records._combined - c_xx.records._combined)*c_xx.records.s006).sum() /1000000000
```




    -115.39106270768052



### Reform 2

```python
((c_y2.records._combined - c_xx.records._combined)*c_xx.records.s006).sum() /1000000000
```




    -69.016541081597936



### Reform 3 

```python
((c_y3.records._combined - c_xx.records._combined)*c_xx.records.s006).sum() /1000000000
```




    -66.470615899204333




```python

```


```python

```

**Comment by martinholmer** [comment]
@MattHJensen,  I like the use of boolean policy parameters in the `current_law_policy.json` file.  But some of your new descriptions should probably use `true` (rather than `True`) and `false` (rather than `False`) because in order to eliminate possible confusion between how JSON booleans are named and how Python booleans are named.

**Comment by MattHJensen** [comment]
> But some of your new descriptions should probably use true (rather than True) and false (rather than False) in order to eliminate possible confusion between how JSON booleans are named and how Python booleans are named.

Thanks, resolved by https://github.com/open-source-economics/Tax-Calculator/pull/1055/commits/3693ce819be77fe263d31e9aa290f951fbf0c8c0

**Comment by martinholmer** [comment]
@MattHJensen said:
> Thanks, resolved by 3693ce8

Pull request #1055 looks good to me.

**Comment by MattHJensen** [comment]
Thanks a lot @martinholmer. Merging.

**Pull request merged**
