### PR TITLE
Add Benefit Information to Tables

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR adds columns for total cost of benefits and total benefit value to the distribution and difference tables.

cc @martinholmer @MattHJensen @Kpinkelman

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey said in pull request #1925:
> This PR adds columns for total cost of benefits and total benefit value to the diagnostic and difference tables.

That's not what the code changes do.  Did you mean to say "to the distribution and difference tables"?

**Comment by andersonfrailey** [comment]
>That's not what the code changes do. Did you mean to say "to the distribution and difference tables"?

Ah yes. Sorry about that. Got the tables mixed up in my head.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Got the tables mixed up in my head.

OK.  Please edit your initial comment so that it accurately describes the code changes.  Thanks.

**Comment by andersonfrailey** [comment]
@martinholmer, done.

**Pull request merged**
