### PR TITLE
Add tcbeh.py script that conducts static+behavior tax analysis

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request adds another script to the Tax-Calculator command-line interface (CLI) that operates on a local computer without any access to TaxBrain.  But there is, of course, the option to upload the JSON reform and assumptions files used by the CLI tools to TaxBrain.
Here's the current CLI tool line-up:

| CLI tool | Tax analysis type | Status | TaxBrain equivalent |
| :-- | :-- | :-- | :-- |
| `tc.py` | static | completed | basic first-step analysis |
| `tcbeh.py` | static+behavior | completed | partial equilibrium simulation |
| `tcdyn.py` | dynamic | incomplete | Solow growth model not a DSGE model |

All three CLI tools support the following:
- use of any CSV-formatted input file containing the variables for each filing unit
- optional use of JSON reform and assumption files (no use implies current-law policy):
  * reform files can specify complex reforms as shown in [these examples](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/REFORMS.md)
  * assumption files can specify combinations of consumption and behavioral responses
  * assumption files can also specify changes in baseline economic assumptions
- choice of minimal or full (dump) results for each filing unit in CSV-formatted output file:
  * minimal results include only RECID, YEAR, WEIGHT, INCTAX, LSTAX, PAYTAX
  * dump results include all (aged) input and all calculated variables using their internal names
- option of automatic generation of graphs in HTML files (viewable/printable with any browser):
   * average tax rate by income percentile
   * marginal tax rate on taxpayer earnings by income percentile
- option of normative welfare analysis of reform (currently available only in static analysis)
- option to do exact tax calculations (with no "stair-step" smoothing) for validation purposes

There are plans to add some output tabulation scripts to automate common tasks.

There are plans to develop extensive HTML documentation and help that can be viewed, searched or printed from any browser.  

And finally there are plans to make all this available to people via a simple download from a website to their computer.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen @zrisher

### CODE REVIEW

**Comment by MattHJensen** [comment]
On TaxBrain we've categorized partial equilibrium analysis (and macro elasticity analysis) as "dynamic" because they affect GNP. This follows the somewhat hazy definition of dynamic adopted by other revenue estimators:

Here's the Tax Policy Center on ["What are dynamic scoring and dynamic analysis"](http://www.taxpolicycenter.org/briefing-book/what-are-dynamic-scoring-and-dynamic-analysis)

> For many years, however, CBO and JCT budget scores did not account for the secondary impact on employment, gross domestic product, and other macroeconomic measures. The agencies often analyzed those macroeconomic impacts separately in what is called dynamic analysis, but did not include their feedback effects in official scores. An exception is immigration reform scoring: the effects on population and labor force are so direct that CBO and JCT did account for them.

The implicit definition of dynamic scoring, by my reading, is "a score that incorporates macroeconomic feedbacks". 

The JCT also highlights this issue when they are [describing](https://www.jct.gov/other-questions.html) their conventional estimates [emphasis added]:

> JCT estimates include many micro-dynamic behavioral effects that economists anticipate would result from changes to taxation; for example, a proposal to increase excise taxes on cigars would be assumed to reduce demand for cigars while potentially increasing demand for cigarettes. **In providing conventional estimates, the Joint Committee Staff assumes that a proposal will not change total income and therefore holds Gross National Product fixed.**

We touched on these issues in https://github.com/OpenSourcePolicyCenter/webapp-public/issues/130 and https://github.com/OpenSourcePolicyCenter/webapp-public/issues/260 as well.

In one comment, Dan (@feenberg) offered the more common economics definition of dynamic as "forward looking", but then the JCT's own MEG model would not comply, which they commonly refer to as producing dynamic estimates. 

What do you think about calling tcbeh.py something like `tcpe.py` and calling `tcdyn.py` something like `tcsolow.py`?

**Comment by MattHJensen** [comment]
@martinholmer, what's your thinking on separating out the modeling capabilities into three separate CLIs? I don't have any experience writing CLIs and am interested in the tradeoffs.

**Comment by martinholmer** [comment]
@MattHJensen asked:
> What's your thinking on separating out the modeling capabilities into three separate CLIs? I don't have any experience writing CLIs and am interested in the trade-offs.

The main considerations are ease of use and ease of development.

I suppose it would be possible to write one command-line interface (CLI) script that had `--static` and `--behavior` and `-dynamic` option flags, but that would be more difficult to use and much more difficult to code and support (because other options can be used only in certain of the three cases).

I think tax analysts who might want to use the CLI scripts are likely to be comfortable with the notion that one uses different tools for different kinds of tax analysis.  The fact that the CLI tools all have the same basic inputs (input data, reform file and assumption file) means that it is easy to analyze the same reform in different ways.

**Comment by martinholmer** [comment]
@MattHJensen asked:
> What do you think about calling `tcbeh.py` something like `tcpe.py` and calling `tcdyn.py` something like `tcsolow.py`?

I think the current names for the CLI tools are better than these alternatives.

It seems to me that the current names are consistent with most of the tax analysis literature in their usage of terms like static analysis, dynamic analysis and behavioral response.

The quotes you cite use the behavioral response terminology and so does the Tax-Calculator source code.  Why go away from that accepted usage and adopt the partial-equilibrium terminology?  While not incorrect, the use of the term partial equilibrium is potentially confusing.  It certainly is confusing to me because it immediately suggests that we are going to offer a general-equilibrium CLI tool. Nobody is talking about that in the tax analysis community, are they? What would an Arrow-Debreu general-equilibrium tax analysis look like?

The goal of the `tcdyn.py` CLI tool is dynamic tax analysis with feedback.  Different tax analysts conduct dynamic analysis with different types of models and assumptions, but they are all doing dynamic analysis of some sort.  So, I don't understand why you seem to think the dynamic-analysis CLI tool should be named something other than `tcdyn.py`.  Certainly, `tcsolow.py` is too narrow because our stated goal is to develop a CLI tool that has roughly the same capabilities as CBO's dynamic analysis (see CBO citation in #1240), which determines growth through an interaction of aggregate demand modeled with Keynesian concepts and aggregate supply modeled with Solow growth model concepts.

**Comment by MattHJensen** [comment]
> because [certain] options can be used only in certain of the three cases

@martinholmer, thanks for explaining the advantages of splitting up the different types of analyses. At first  I thought `tc.py` might be treated as a special case of `tcbeh.py`, but I can see how the normative analysis option might complicate that.

**Comment by MattHJensen** [comment]
> Why go away from that accepted usage and adopt the partial-equilibrium terminology? 

> The quotes you cite use the behavioral response terminology and so does the Tax-Calculator source code.

The quotes I cite use the behavioral response terminology uniformly in the context of fixed-GNP analysis. If you discuss `micro-behavioral`, `micro-dynamic`, or `conventional` estimating with someone in the revenue-estimating world, s/he will assume you are also adopting a fixed-GNP assumption. 

Someone might be able to 'hack' tax-calculator's behavior class to conduct fixed-GNP analysis by, for example, assuming a taxable income elasticity captures only income shifting and recharacterization, but that is definitely not the focus of Tax-Calculator development and I don't know of anyone who has used Tax-Calculator for this purpose. 

Instead, Tax-Calculator is designed for users to be able to apply behavioral elasticities in the context of partial equilibrium analysis where elasticities might capture labor supply, investment, or other aspects of real economic activity as well as income shifting and recharacterization. These capabilities have been used extensively. 

> While not incorrect, the use of the term partial equilibrium is potentially confusing. It certainly is confusing to me because it immediately suggests that we are going to offer a general-equilibrium CLI tool. Nobody is talking about that in the tax analysis community, are they?

OG-USA is a DGE model. The Joint Committee on Taxation [also uses](https://www.jct.gov/publications.html?func=startdown&id=4969 ) a DSGE model. 

> The goal of the tcdyn.py CLI tool is dynamic tax analysis with feedback. Different tax analysts conduct dynamic analysis with different types of models and assumptions, but they are all doing dynamic analysis of some sort. So, I don't understand why you seem to think the dynamic-analysis CLI tool should be named something other than tcdyn.py.

A long-time goal of Tax-Calculator is to provide a bridge between policy analysts and macroeconomists. TC inputs are policy levers that policy analysts understand, and TC outputs can serve as inputs to macroeconomic models. The tcdyn.py name implies that there is only one type of dynamic analysis as part of the tax-calculator project, whereas a goal is to encourage the development (and competition) of many approaches.  Already, the partial equilibrium is dynamic in the revenue-estimating usage of the term because it does not require a fixed-gnp assumption. OG-USA and is dynamic. 

Others, I hope, will want to contribute dynamic models in the future or at least use Tax-Calculator as the input for dynamic modeling. 

Note that the Joint Committee on Taxation, which is the primary tax revenue estimating resource for congress, [uses at least three dynamic models](https://www.jct.gov/publications.html?func=startdown&id=4969 ).

--
Overall, I feel more strongly about tcdyn than tcbeh given that tcbeh could potentially be used for fixed-gnp analysis.

**Comment by martinholmer** [comment]
Close Tax-Calculator pull request #1250 in order to pursue a different approach to providing a command-line interface (CLI) to the taxcalc package.

**Pull request closed without merging**
