### PR TITLE
fix record description

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR simply corrects an error in the `records_variables.json` I just noticed. `nu18`, `n1821`, and `n21` we're previously described as the number of _dependents_ in those age ranges when they actually represent the number of people in the tax units. There is no change to the tax logic in this PR.

@martinholmer @MattHJensen

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Fixing the Travis CI and Appveyor failures. I'll comment again when they're ready.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Fixing the Travis CI and Appveyor failures. I'll comment again when they're ready.

PR #1356 is fixing those; just wait a few moments for me to merge.

**Comment by andersonfrailey** [comment]
@martinholmer said
> PR #1356 is fixing those; just wait a few moments for me to merge.

Gotcha. Thanks for the heads up.

**Comment by martinholmer** [comment]
@andersonfrailey, You should be able to proceed now.
1. Synchronize your master branch with GitHub master (so as to get #1356 changes).
2. Merge the update master branch into your descfix branch.
3. Push the updated branch to your GitHub account.
4. Confirm that your #1357 passes all the tests on GitHub.

Thanks for this improvement in the documentation.

**Comment by martinholmer** [comment]
@andersonfrailey,
Consider instead of adding "in the tax unit" adding either
"in the filing unit"  or  "in the tax filing unit".
Either of those would be more consistent with all the rest of the documentation.

**Comment by andersonfrailey** [comment]
@martinholmer, I believe the reason the number of files changing is becuase I let my master branch fall a behind while working on another project so when I caught everything up it all got pushed together, but I'm not sure. Is there a way to confirm this? Otherwise I have no problem opening a different PR that only has the one file change.

**Comment by martinholmer** [comment]
@andersonfrailey, Thanks for the documentation improvement in #1357!   Merging now.

**Pull request merged**
