### PR TITLE
Extrapolation Factor Modified for Capital Gain 

### PR DESCRIPTION
**Pull request by GoFroggyRun**
The taxable net capital gain for 2013 is approximately $439 billion on current master, while the data from SOI suggests that the real net capital gain for 2013 should be about $504 billion. This indicates that we might want to modify the extrapolation factor of capital gain for year 2013 and afterwards.  
This PR modifies the extrapolation factor of capital gain in 2013 to match the SOI data on capital gain, that is setting the factor to be `2.198301`. Factors for years later on are also modified iteratively, by applying the growth rate to previous year's factor. And we have:
```
[2013] 2.198301 2.964478 3.450607 3.508749 3.619760 3.746481 3.899808 4.058296 4.222059 4.396487 4.576191 4.766445 4.964612 5.171036
```

The diagnostic table for this PR:
screen shot 2016-01-12 at 6 58 20 pm

Please note that applying the CBO option that increases capital gains and dividends rate by 2% on top of this PR would amplify the previous difference we have by roughly $2 billion, instead of the $1 billion that I might have mentioned by mistake: 
screen shot 2016-01-12 at 8 25 48 pm

@MattHJensen @Amy-Xu Any comments, concerns or remarks would be appreciated.

### CODE REVIEW

**Comment by martinholmer** [comment]
This pull request is **incomplete** because ```python testagg.py``` has not been executed to produce the  ```testagg-results.txt``` file.  This aggregate diagnostic table results file will be different, and so the new version needs to be committed to this branch because it is under git version control.  Doing this will provide information about which elements of the diagnostic table change and by how much they change.  The above conversation only says what the new diagnostic table results would be after merging the pull request, but says nothing about what is changing and by how much.

Perhaps the development team needs to think about whether we can automate, and make manditory for the development team who have access to the proprietary puf.csv file, the execution of testagg.py program.  And the same goes for the testmtr.py program (and perhaps some of the other test programs that use puf.csv input).

T.J., as our resident Python-project-management expert, what can you suggest as a strategy?  I'm assuming that because the puf.csv file is not publicly available, we cannot include tests that use puf.csv in the py.tests suite.  What other options are available?

cc @MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by MattHJensen** [comment]
Great suggestions, @martinholmer. Agreed that we should be more rigorous in our examination of changes when making commits!

On Jan 13, 2016, at 7:54 AM, Martin Holmer <notifications@github.com<mailto:notifications@github.com>> wrote:


This pull request is incomplete because python testagg.py has not been executed to produce the testagg-results.txt file. This aggregate diagnostic table results file will be different, and so the new version needs to be committed to this branch because it is under git version control. Doing this will provide information about which elements of the diagnostic table change and by how much they change. The above conversation only says what the new diagnostic table results would be after merging the pull request, but says nothing about what is changing and by how much.

Perhaps the development team needs to think about whether we can automate, and make manditory for the development team who have access to the proprietary puf.csv file, the execution of testagg.py program. And the same goes for the testmtr.py program (and perhaps some of the other test programs that use puf.csv input).

T.J., as our resident Python-project-management expert, what can you suggest as a strategy? I'm assuming that because the puf.csv file is not publicly available, we cannot include tests that use puf.csv in the py.tests suite. What other options are available?

cc @MattHJensen<https://github.com/MattHJensen> @feenberg<https://github.com/feenberg> @talumbau<https://github.com/talumbau> @Amy-Xu<https://github.com/Amy-Xu> @GoFroggyRun<https://github.com/GoFroggyRun>

**Comment by feenberg** [comment]
PUF files for 1993 and earlier are available from the national archives 
and are in the public domain. Could we make a test file from one of them? 
We could use the basic data (wages, deductions)  as is, and recompute the 
calculated values (agi, tax, etc).

dan

**Comment by martinholmer** [comment]
Dan @feenberg said:
> PUF files for 1993 and earlier are available from the national archives and are in the public domain. Could we make a test file from one of them?  We could use the basic data (wages, deductions)  as is, and recompute the calculated values (agi, tax, etc).

Isn't that what we are already doing (with the 1991 PUF) in the py.tests suite?

Seems like we really need some kind of systematic testing with the current puf.csv file as used by TaxBrain.  Using other faux puf.csv files will not provide answers to questions like how much will tax liabilities (as simulated by TaxBrain) change if this pull request were to be merged into the master branch.

cc @MattHJensen @talumbau @Amy-Xu @GoFroggyRun

**Comment by martinholmer** [comment]
PROBLEM: How to include more tests in the py.test suite, but only when puf.csv is present?

SOLUTION: What about using [the skip test feature](http://pytest.org/latest/skipping.html#marking-a-test-function-to-be-skipped) built into py.test?  We can include tests in the py.test suite (located in the test_*.py files in the taxcalc/tests directory) that require puf.csv input as follows:
```
@pytest.mark.skipif(os.path.isfile(PUF_CSV_PATH),
                    reason='requires propriatary puf.csv file')
def test_using_puf_csv_file():
    # conditional test code goes here
```

Perhaps there is a better approach.  I'm open to suggestions.

After discussion here, I would be happy to prepare a pull request that tries this (or a better) approach to conditional testing.  I think that pull request should have a limited scope focusing only on conditional inclusion of the testagg.py logic.  If that works well, the approach could be broadened to include other aggregate tests that require the puf.csv file.

ONE WEAKNESS: In addition to the fact that there may be a better approach to solving this problem, the solution proposed above relies on all the OSPC developers keeping the puf.csv file at the PUF_CSV_PATH location.  If a developer does not have their computer set up this way, then (in the above example) the ```test_using_puf_csv_file``` test will be skipped.

cc @MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by martinholmer** [comment]
Typo in my earlier discussion of @pytest.mark.skipif():
Should be something like this:
```
@pytest.mark.skipif(os.path.isfile(PUF_CSV_PATH) is False,
                    reason='requires propriatary puf.csv file')
def test_using_puf_csv_file():
    # conditional test code goes here
```
cc @MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by GoFroggyRun** [comment]
@martinholmer Thanks for your comments! I just updated the `testagg-results.txt`. Please find the file for detailed changes. 
I was actually wondering why the `py.test` is passing on my local computer while fails here on git. Do you have any ideas why this is the case?
Failures on git:
```
=================================== FAILURES ===================================
__________________________ PEP8-check(ignoring E402) ___________________________
/home/travis/build/open-source-economics/Tax-Calculator/taxcalc/tests/test_calculate.py:324:42: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
    assert np.array_equal(mtr, mtr_FICA) == False
                                         ^
/home/travis/build/open-source-economics/Tax-Calculator/taxcalc/tests/test_calculate.py:325:46: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
    assert np.array_equal(mtr_FICA, mtr_IIT) == False
                                             ^
```
My local computer: 
```
============================= test session starts ==============================
platform darwin -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /Users/Sean.Wang/Documents/OSPC/tax-calculator, inifile: setup.cfg
collected 99 items 

tests/test_behavior.py ...
tests/test_calculate.py ...............
tests/test_decorators.py .................
tests/test_growth.py ......
tests/test_incometaxio.py ..
tests/test_policy.py .................
tests/test_records.py ......
tests/test_simpletaxio.py ...
tests/test_utils.py ..............................

========================= 99 passed in 113.40 seconds ==========================
```

**Comment by martinholmer** [comment]
Sean @GoFroggyRun said:
> I was wondering why the py.test is passing on my local computer while fails here on GitHubg. Do you have any ideas why this is the case?

I've noticed this in the past few days myself.  One guess is that the OSE GitHub repo has just started using a newer version of pytest than we have on our computers.  T.J. @talumbau, is this possible?

I guess we could experiment by doing ```conda update pytest``` to see if there is a newer version and if it flags issues like the following:
```
=================================== FAILURES ===================================
__________________________ PEP8-check(ignoring E402) ___________________________
/home/travis/build/open-source-economics/Tax-Calculator/taxcalc/tests/test_calculate.py:324:42: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
    assert np.array_equal(mtr, mtr_FICA) == False
                                         ^
/home/travis/build/open-source-economics/Tax-Calculator/taxcalc/tests/test_calculate.py:325:46: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
    assert np.array_equal(mtr_FICA, mtr_IIT) == False
                                             ^
```

cc @MattHJensen @Amy-Xu

**Comment by martinholmer** [comment]
Meant to say pep8 (not pylint) in my previous comment.  The errors are pep8 errors, not pylint errors.

cc @MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by martinholmer** [comment]
Sean @GoFroggyRun said:
> I was actually wondering why the py.test is passing on my local computer while fails here on git.  Do you have any ideas why this is the case?

> Failures on GitHub:
>================================FAILURES================================
>__________________________ PEP8-check(ignoring E402) ___________________________
>/home/travis/build/open-source-economics/Tax-Calculator/taxcalc/tests/test_calculate.py:324:42: E712 >comparison to False should be 'if cond is False:' or 'if not cond:'
>    assert np.array_equal(mtr, mtr_FICA) == False
>
>/home/travis/build/open-source-economics/Tax-Calculator/taxcalc/tests/test_calculate.py:325:46: E712 >comparison to False should be 'if cond is False:' or 'if not cond:'
>    assert np.array_equal(mtr_FICA, mtr_IIT) == False
>
>My local computer:
=========================== test session starts ============================
platform darwin -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /Users/Sean.Wang/Documents/OSPC/tax-calculator, inifile: setup.cfg
collected 99 items 
tests/test_behavior.py ...
tests/test_calculate.py ...............
tests/test_decorators.py .................
tests/test_growth.py ......
tests/test_incometaxio.py ..
tests/test_policy.py .................
tests/test_records.py ......
tests/test_simpletaxio.py ...
tests/test_utils.py ..............................
======================= 99 passed in 113.40 seconds ========================

Sean,  Sorry about my earlier confusion, but I'm also puzzled by this.  First, the GitHub pull request is doing two things: (1) running the same pytest suite that you ran on your computer using the ```py.test``` command, and (2) running pep8 tests on each *.py file in the repository.  The two errors you got back from your GitHub pull-request submission are PEP8 errors, not pytest errors.  Originally I was going to say that perhaps you forgot to run pep8 on the test_calculate.py file, but that is not the source of the problem.  I checked on my computer that I have the most recent version of pep8 (that is, 1.6.2) and when I execute ```pep8 test_calculate.py``` there are no error messages.  So I don't have any idea why the pep8 on the GitHub server is generating these error messages.  Sounds like a question for T.J.

cc @MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by GoFroggyRun** [comment]
@martinholmer Thanks for the updates. On my machine I also have the latest pep8, and I haven't modified any pep8-related stuff I believe. We might want to wait and see what T.J. says.

**Comment by talumbau** [comment]
Sorry I neglected the conversation here yesterday. It seems like there are two issues to resolve here:

1. Why are there PEP8 violations in the Travis CI builds that you are not seeing on your local machine?

2. How do we enforce tests that involve the PUF when we can't check the PUF into the repo?

For the first question, it helps to know more precisely what is happening with the automated tests that are run on pull requests. At the top of the repo, there is a filed called `.travis.yml`. This file is used to set up and run the automated test suite using a web service called Travis CI (which stands for Continuous Integration). As an open-source project, we can use this service for free. At the bottom of the file you will see this:

```
coverage run -m py.test --pep8 taxcalc/tests/
```

The first part (`coverage run -m`) is something relevant to creating a test coverage report, so that can be safely ignored for this conversation. The rest shows how `py.test` is invoked on Travis CI to run the tests. In particular, the command:

```
py.test --pep8 taxcalc/tests/
```

indicates that the pep8 plugin for pytest is turned on during the test run. If you install the pytest-pep8 plugin you can then execute this same line. To install the pytest-pep8 plugin, do as follows:

```
pip install pytest-pep8
```

then you will have the ability to invoke pytest with the `--pep8` flag. If you do this, you should see the same result as Travis CI.

let me respond to item 2 above in a separate comment.

**Comment by martinholmer** [comment]
T.J. said:
> Sorry I neglected the conversation here yesterday. It seems like there are two issues to resolve here:
>
>Why are there PEP8 violations in the Travis CI builds that you are not seeing on your local machine?
>
>How do we enforce tests that involve the PUF when we can't check the PUF into the repo?
>
>For the first question, it helps to know more precisely what is happening with the automated tests that are run on pull requests. At the top of the repo, there is a filed called .travis.yml. This file is used to set up and run the automated test suite using a web service called Travis CI (which stands for Continuous Integration). As an open-source project, we can use this service for free. At the bottom of the file you will see this:
>```coverage run -m py.test --pep8 taxcalc/tests/```
>The first part (coverage run -m) is something relevant to creating a test coverage report, so that can be safely ignored for this conversation. The rest shows how py.test is invoked on Travis CI to run the tests. In particular, the command:
>```py.test --pep8 taxcalc/tests/```
>indicates that the pep8 plugin for pytest is turned on during the test run. If you install the pytest-pep8 plugin you can then execute this same line. To install the pytest-pep8 plugin, do as follows:
>```pip install pytest-pep8```
>then you will have the ability to invoke pytest with the --pep8 flag. If you do this, you should see the same result as Travis CI.
>
>Let me respond to item 2 above in a separate comment.

T.J. thanks for the background information.  I tried to follow your suggestions, but still didn't get the PEP8 error generated by Travis-CI.   But maybe I did something wrong.  Here is what I did:
```conda update pytest```   ==> upgrade from 2.7.1 to 2.8.1
```conda install pytest-pep8```   ==> install pytest-pep8 1.0.6
And then I did this:
```
iMac2:tax-calculator mrh$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
iMac2:tax-calculator mrh$ py.test --pep8 taxcalc/tests
============================= test session starts ==============================
platform darwin -- Python 2.7.11, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /Users/mrh/work/OSPC/tax-calculator, inifile: setup.cfg
plugins: pep8-1.0.6
collected 110 items 
taxcalc/tests/accuracy.py .
taxcalc/tests/graphtest.py .
taxcalc/tests/test_behavior.py ....
taxcalc/tests/test_calculate.py ................
taxcalc/tests/test_decorators.py ..................
taxcalc/tests/test_growth.py .......
taxcalc/tests/test_incometaxio.py ...
taxcalc/tests/test_policy.py ..................
taxcalc/tests/test_records.py .......
taxcalc/tests/test_simpletaxio.py ....
taxcalc/tests/test_utils.py ...............................
========================= 110 passed in 144.54 seconds =========================
```
And just to check that the above command is running pep8 on the test_calculate.py file, I moved to the taxcalc/tests directory and did this:
```
iMac2:tests mrh$ pep8 --ignore=E402 test_calculate.py 
iMac2:tests mrh$ 
```
All the above results are for the following in test_calculate.py:
```
def test_Calculator_mtr():
    policy = Policy()
    puf = Records(TAX_DTA, weights=WEIGHTS, start_year=2009)
    calc = Calculator(policy=policy, records=puf)
    (mtr_FICA, mtr_IIT, mtr) = calc.mtr()
    assert type(mtr) == np.ndarray
    assert np.array_equal(mtr, mtr_FICA) == False        # <=== Travis-CI PEP8 error
    assert np.array_equal(mtr_FICA, mtr_IIT) == False    # <=== Travis-CI PEP8 error
```
So, I'm still confused about the discrepancy between what I get on my computer and what Travis-CI gets.

**Comment by martinholmer** [comment]
@talumbau @GoFroggyRun,
See my experience following T.J.'s suggestions in the conversation of pull request #527.
I still cannot generate the PEP8 errors (in tests_calculate.py) that Travis-CI generates.

cc @MattHJensen @Amy-Xu

**Comment by GoFroggyRun** [comment]
@martinholmer @talumbau, 
Same here. Following T.J.'s suggestion on top of the commit that yields pep8 error on git, I still wasn't able to replicate the pep8 error locally:
```
ITs-MacBook-Air:taxcalc Sean.Wang$ py.test --pep8 tests
================================================ test session starts =================================================
platform darwin -- Python 2.7.11, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /Users/Sean.Wang/Documents/OSPC/tax-calculator, inifile: setup.cfg
plugins: pep8-1.0.6
collected 110 items 

tests/accuracy.py .
tests/graphtest.py .
tests/test_behavior.py ....
tests/test_calculate.py ................
tests/test_decorators.py ..................
tests/test_growth.py .......
tests/test_incometaxio.py ...
tests/test_policy.py ..................
tests/test_records.py .......
tests/test_simpletaxio.py ....
tests/test_utils.py ...............................

============================================ 110 passed in 154.65 seconds ============================================
ITs-MacBook-Air:taxcalc Sean.Wang$ git status
On branch Extrapo_Factor_CG
```

**Comment by Amy-Xu** [comment]
Let's keep this pep8 issue in mind. The PR looks good to me. Merging. Thanks @GoFroggyRun @martinholmer!

cc @MattHJensen @talumbau

**Pull request merged**
