### PR TITLE
Add two requires_pufcsv tests to the pytest suite

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request implements the strategy discussed in issue #528. It moves two tests (testagg.py and testmtr.py) that were formerly in the top-level tax-calculator directory into the pytest suite in the tax-calculator/taxcalc/tests/test_pufcsv.py file.  The two new pytest tests are marked as ```requires_pufcsv``` and the new tax-calculator/TESTING.md file documents the whole Tax-Calculator testing procedure.  A link to this TESTING.md documentation has been added in a revised Getting Started section in tax-calculator/README.md.  Also, the output of the tax-calculator/taxcalc/vatidation/tests has been revised to be more similar to pytest output.

This pull request does not change any output generated by the Tax-Calculator.  It only strengthens and simplifies Tax-Calculator testing procedures.  For details on the testing procedures read the revised Getting Started section in README.md and follow the link to the new testing-procedures documentation.

The other part of the strategy laid out in issue #528 will be implemented by T.J. when he adds the capability for Travis-CI to automatically run the two ```requires_pufcsv``` tests when each pull request is submitted to the GitHub Tax-Calculator repository.

There are at least two issues that could be handled differently in this pull request:

(1) Location of the puf.csv file.  I asked for suggestions in issue #528, but no suggestions were offered.  So, I wrote the ```requires_pufcsv``` tests assuming that file (which is never under version control) is located in the top-level tax-calculator directory.  Is there a better location?

(2) Location of expected test results.  I wrote the test_pufcsv.py tests so that the expected output of the two tests are strings in the test_pufcsv.py file.  This is fine for the marginal tax rates test, but the ten-year diagnostic table produced by the other test has very long lines that need to be broken up (in order to avoid PEP8 errors).  An alternative approach is to put each set of expected results in a text file in the tax-calculator/taxcalc/tests directory and have the test read its expected results from the text file.  I would be interested in hearing opinions about which approach is thought to be better.

cc @MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

### CODE REVIEW

**Comment by martinholmer** [comment]
The Travis-CI pytests failed for the two new ```requires_pufcsv``` tests included in pull request #537 because T.J. has not yet had time to set up Travis-CI to handle the two new tests.  As he said in issue #528, there is a temporary stop-gap approach that would have Travis-CI execute ```py.test -m "not requires_pufcsv"``` which skips the two new tests.  But eventually, it seems we are all agreed that Travis-CI should never skip the ```requires_pufcsv``` tests and should execute them by temporarily copying ```puf.csv``` from AWS S3 storage to the computer that is executing the pytest suite.

cc @MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by talumbau** [comment]
OK, @martinholmer, I will quickly add a PR to this PR that you can then merge and get Travis CI testing again. Then, when I have more time, I will add the code so that Travis CI can get the proper data and run these tests. Please hold merging until I post the PR.

**Comment by martinholmer** [comment]
T.J. said:
> OK, @martinholmer, I will quickly add a PR to this PR that you can then merge and get Travis CI testing again. Then, when I have more time, I will add the code so that Travis CI can get the proper data and run these tests. Please hold merging until I post the PR.

T.J., thanks for the quick service!  I didn't think I could do a merge (even if I wanted to) with the pytest failures.  I'm happy to wait for your guidance on how to make Travis-CI skip the two ```requires_pufcsv``` tests, which is our interim solution.  Meanwhile, the core development team can execute the full pytest suite (including the two new ```requires_pufcsv``` tests) on their local computers.

cc @MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by talumbau** [comment]
OK @martinholmer please merge this PR:

https://github.com/martinholmer/Tax-Calculator/pull/5

Doing so will add my commit to your `add_tests0` branch, which will then re-trigger running the tests on this PR and we should see that Travis CI will skip the tests that require the PUF.

**Comment by martinholmer** [comment]
T.J. (@talumbau), thanks for the help on pull request 537.  Everything seem to work now, but Matt is having concerns.  Turns out that it is complicated to run an open-source project when the project is using proprietary data.

**Comment by talumbau** [comment]
Ok great. I don't think there's a danger in merging this now because we would be in the situation where developers are running a couple additional tests that Travis CI is not running. More info on the other issue.

**Comment by MattHJensen** [comment]
@martinholmer, this looks great. Agree with @talumbau that we can sort out how to get the tests running safely on GH through further discussion in #528.

**Comment by martinholmer** [comment]
Matt said:
> @martinholmer, this looks great.  Agree with @talumbau that we can sort out how to get the tests running safely on GitHub through further discussion in #528.

OK, I'll do the merge now.  This means that core developers (who have access to the ```puf.csv``` file) now will need to have a copy of it in the top-level directory (above taxcalc) when they run py.test, but ```puf.csv``` should never be put under Git version control.

@Amy-Xu @GoFroggyRun

**Pull request merged**
