### PR TITLE
[WAIT] Correct names of several policy parameters

### PR DESCRIPTION
**Pull request by martinholmer**
These changes bring the parameter names into closer alignment with the project's [parameter naming conventions](http://taxcalc.readthedocs.io/en/latest/parameter_naming.html).  The need for these changes arose in the discussion of pull request #1029.

@MattHJensen @talumbau @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen @jdebacker

### CODE REVIEW

**Comment by MattHJensen** [comment]
Thanks @martinholmer. Let's not merge this until after #1039, #1028, and #1027  are merged and a new release is issued as it will require changes to downstream users of Tax-calculator.

**Comment by martinholmer** [comment]
@MattHJensen said:
> Thanks @martinholmer. Let's not merge this until after #1039, #1028, and #1027 are merged and a new release is issued as it will require changes to downstream users of Tax-calculator.

But if we don't include this in the new TaxBrain version, the reform file upload capability won't work, will it?  Why don't you get everybody on the same page now, so we can fix this?

**Comment by MattHJensen** [comment]
> But if we don't include this in the new TaxBrain version, the reform file upload capability won't work, will it?
 
#1040 will only cause breaking changes for downstream users once it is included in a release. If we don't merge it now, then we can have release immediately w #1039, #1028, #1027, and the other changes since our last release. This first release won't break anything for anyone and can be deployed immediately. Then we can follow up with a second release that only includes #1040. The second release _will_ contain breaking changes for downstream users (renamed parameters), but we'll be able to get the fixes in place in a deliberate and careful manner without worrying about holding anything up.

**Comment by MattHJensen** [comment]
+1

**Pull request merged**
