### PR TITLE
Update factors and weights with Jan 16 CBO economic projections

### PR DESCRIPTION
**Pull request by Amy-Xu**
With the new factors and weights in this PR, the reform results almost stay at the same place but the baseline drops significantly, mainly due to the two following reasons.

- In PR #527, capital gain extrapolation factor was updated by @GoFroggyRun, by comparing our 2013 weighted cap gain and SOI 2013 stats. It was partially my fault that I forgot to tell Sean we should be using the net gain, which is the weighted positive part of either `e01100` or `p23250 + p22250`, instead of the total weighted sum. Thus after this PR, the net gain (2015) was over blown to 907b from previously 791b, about 116b increase, and baseline in 2015 was increased from 1410b to 1440b. Two takeaway points: 1) current baseline in 2015 should still stay at 1410b, and 2) 116b net capital gain diff leads to a 30b individual income tax jump.

- Switching from 2014 economic projection to the latest Jan 2016 version, the biggest difference still comes from capital gain section. CBO ([Detailed Revenue Projections, realized capital gain](https://www.cbo.gov/about/products/budget_economic_data#3)) changed their estimates for 13-15 significantly in this version, increasing 2013 realized gain from 416b to 511b, and 15 gain from 657b to 679b. As we are only using the growth rate instead of the actual values from CBO, our targets for 2015 drops by about 101b. Thus, this cap gain drop results in another decrease on individual income tax for about 25 billion.

This updates seems to drag our baseline further away from CBO's number, which is sad, but it still seems reasonable enough to update it anyways. Any feedback/questions on the reasoning above @feenberg @martinholmer @MattHJensen @GoFroggyRun?

There's still a small problem on the line of test I comment out in test_policy.py. I'll keep working on that.

### CODE REVIEW

**Comment by Amy-Xu** [comment]
Before my latest commit, I'm not sure whether I messed anything up or not, but policy keeps giving me 41702 for the value of that parameter, but the actually manually-calculated result is 41702.695.

@martinholmer @talumbau Was wondering when we expanded parameters using CPI, are we rounding all numbers downward? If so, where's the code?

**Comment by martinholmer** [comment]
@Amy-Xu said:
> Before my latest commit, I'm not sure whether I messed anything up or not, but policy keeps giving me 41702 for the value of that parameter, but the actually manually-calculated result is 41702.695.
>
> @martinholmer @talumbau Was wondering when we expanded parameters using CPI, are we rounding all numbers downward? If so, where's the code?

Amy,  Just let the test_policy.py code stay the way it is, and after this pull request is merged into the master branch, I'll review all the tests in test_policy.py to see which need to be updated to reflect the recent addition of historical 2015 values for policy parameters.

cc @MattHJensen @GoFroggyRun

**Comment by martinholmer** [comment]
What do people think about pull request #575?  It seems ready for merging into the master branch.  Do others agree or not?  If no objections, I'll merge later today.

cc @MattHJensen @GoFroggyRun @Amy-Xu

**Comment by talumbau** [comment]
Hi @Amy-Xu just to answer your question, currently when we expand parameters, it looks to me like we are not rounding down per year. The code for this is in `parameters_base.py` in the `expand_1D` and `expand_2D` functions. So here:

expand_2D:
https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters_base.py#L456

expand_1D:
https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters_base.py#L405

So each value stays as a floating point value as we expand and build the new values. Then before returning, we cast to the `dtype` of what we were given. So if it was originally `int`, at the end, just before returning from the function, we would round down (or really, just truncate) to integer values. As shown in this line:

https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters_base.py#L412

**Comment by MattHJensen** [comment]
This looks good to me, too, @martinholmer. Thanks @Amy-Xu! Merging.

**Pull request merged**
