### PR TITLE
add a py.test module to test docs/notebooks

### LINKED ISSUE #1151: Testing jupyter notebooks
The bug in our `10_min` notebook (#1150) has me thinking about how to test Jupyter notebooks. 

My first instinct was to add a test to `test_calculate.py` that does the same thing as the notebook. The problem with that approach is that whenever a contributor updates the notebook, s/he would have to remember to update the test as well. 

My second instinct was to search google, and I found this: [nbval](https://github.com/computationalmodelling/nbval). It seems to be designed for exactly the purpose we need, but it would require us adding another dependency, and one that looks somewhat immature. 

Does anyone have any experience working with `nbval` or have experience with other solutions for testing notebooks?  

cc @PeterDSteinberg @talumbau

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Work in progress.  Adds a test that automatically runs the notebooks in `docs/notebooks` and asserts that they have no exception.

Fixes #1151

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
Currently there is an error in `Behavioral_example.ipynb`:

```
$ py.test -k test_Behavioral_example
============================= test session starts ==============================
platform darwin -- Python 2.7.13, pytest-3.0.5, py-1.4.31, pluggy-0.4.0
rootdir: /Users/psteinberg/Documents/AEI/Tax-Calc2, inifile: setup.cfg
plugins: django-3.0.0, pep8-1.0.6
collected 319 items

taxcalc/tests/test_notebooks.py F

=================================== FAILURES ===================================
___________________________ test_Behavioral_example ____________________________

    def test_Behavioral_example():
>       assert notebook_run(NB1) == 0

taxcalc/tests/test_notebooks.py:74:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
taxcalc/tests/test_notebooks.py:64: in notebook_run
    return subprocess.check_call(args, cwd=TEST_DIR)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['python', '/Users/psteinberg/Documents/AEI/Tax-Calc2/taxcalc/tests/10_minutes_script.py'],)
kwargs = {'cwd': '/Users/psteinberg/Documents/AEI/Tax-Calc2/taxcalc/tests'}
retcode = 1
cmd = ['python', '/Users/psteinberg/Documents/AEI/Tax-Calc2/taxcalc/tests/10_minutes_script.py']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the Popen constructor.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           CalledProcessError: Command '['python', '/Users/psteinberg/Documents/AEI/Tax-Calc2/taxcalc/tests/10_minutes_script.py']' returned non-zero exit status 1

../../../anaconda3/envs/taxcalc-dev/lib/python2.7/subprocess.py:186: CalledProcessError
----------------------------- Captured stdout call -----------------------------
You loaded data for 2009.
Instantiation of the calculator automatically extrapolated your data to 2013.
You loaded data for 2009.
Instantiation of the calculator automatically extrapolated your data to 2013.
0.396
0.496
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/Users/psteinberg/Documents/AEI/Tax-Calc2/taxcalc/tests/10_minutes_script.py", line 50, in <module>
    behavior_y.update_behavior({2013: {'_BE_inc': [0.15], '_BE_sub': [0.4]}})
  File "/Users/psteinberg/Documents/AEI/Tax-Calc2/taxcalc/behavior.py", line 80, in update_behavior
    self._validate_elasticity_values()
  File "/Users/psteinberg/Documents/AEI/Tax-Calc2/taxcalc/behavior.py", line 193, in _validate_elasticity_values
    raise ValueError(msg.format(elast, pos, year, val))
ValueError: _BE_inc elasticity cannot be positive in year (0,); value is 0.15
```

**Comment by PeterDSteinberg** [comment]
Currently this test module just runs each of the notebooks in `docs/notebooks`.  If you know of any specific assertions I should add to the end of the auto-generated scripts, let me know, @MattHJensen .

**Comment by PeterDSteinberg** [comment]
@MattHJensen - Should we merge this and then deal with the Behavioral_example.ipynb problem in separate PR if needed?  Also I think the codecov/project decline of coverage of 0.01 % is not a big deal - some artifact of how it is calculated.

**Comment by martinholmer** [comment]
@PeterDSteinberg said about #1198:
> Add a test that automatically runs the notebooks in docs/notebooks and asserts that they have no exception.

How long do these new tests take to run?  The py.test suite already takes so long to run that it is a hindrance to development work on Tax-Calculator.  

Why are we adding what look to be long-running tests that just check if the notebooks are up to date?  If the authors of the notebooks want to have help maintaining their documentation, then why not put the new tests in #1198 in a separate docs test suite?

@MattHJensen @PeterDSteinberg

**Comment by PeterDSteinberg** [comment]
@martinholmer I think including tests in taxcalc/tests as done in this PR makes it easy for both the docs and develop teams to check for consistency.  We could update docs regarding usage of `py.test` to include help on excluding certain tests with `pytest.mark`.  These notebook tests in this PR are [marked as `requires_pufcsv` and `notebook`](https://github.com/open-source-economics/Tax-Calculator/pull/1198/files#diff-f6adfa05aec0ecf8d880276e8adfc367R45), so any of the following will *skip* them:

```
py.test -m "not requires_pufcsv"
py.test -m "not notebook"
py.test -m "not notebook and requires_pufcsv"
```

**Comment by martinholmer** [comment]
@PeterDSteinberg said:
> I think including tests in taxcalc/tests as done in this PR makes it easy for both the docs and develop teams to check for consistency. We could update docs regarding usage of py.test to include help on excluding certain tests with pytest.mark. These notebook tests in this PR are marked as requires_pufcsv and notebook, so any of the following will skip them:
> ```
> py.test -m "not requires_pufcsv"
> py.test -m "not notebook"
> py.test -m "not notebook and requires_pufcsv"
> ```

Thanks for explaining that the new tests in #1198 are optional.  I missed that in the proposed code.
Given their optionality, I'm comfortable with including these new notebook tests in the main taxcalc py.test suite.

**Comment by PeterDSteinberg** [comment]
I think we should merge this PR, @MattHJensen @martinholmer .  It is passing all tests except the code coverage dropped -0.01 % which I think is unavoidable.

**Comment by MattHJensen** [comment]
@PeterDSteinberg, thanks a lot for the contribution! Merging.

**Pull request merged**
