### PR TITLE
Add _cpi_offset parameter and associated logic and tests

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request attempts to add the CPI-offset capability discussed in issue #1621.

The required changes in `current_law_policy.json` have been made except for the section titles.  @MattHJensen, presumably this parameter will be available to TaxBrain users, so I'd like to hear from you what the `section_1` and `section_2` titles should be, and also where on the TaxBrain input page you intend to show this new parameter (presumably at the very top, right?).

Any suggestions or comments are welcome.

@Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun @codykallen @evtedeschi3

### CODE REVIEW

**Comment by MattHJensen** [comment]
> @MattHJensen, presumably this parameter will be available to TaxBrain users, so I'd like to hear from you what the section_1 and section_2 titles should be, and also where on the TaxBrain input page you intend to show this new parameter (presumably at the very top, right?).

Yes, top of page makes sense to me. 

How about:

_section_1: Parameter Indexing
_section_2: Offsets

**Comment by martinholmer** [comment]
@MattHJensen asked:
> what do you think about adding a test that checks that a reform with an _ACPIU growdiff response produces the same result as a reform cpi offset?
>
> "growdiff_response": {"_ACPIU": {"2017": [-0.0025]}

Thanks for the good suggestion.  The test has been added.

**Comment by MattHJensen** [comment]
LGTM. Thanks @martinholmer!

**Comment by martinholmer** [comment]
Does anybody else want to review the code and tests in #1667 that add a new `_cpi_offset` policy parameter?
@MattHJensen seems to be in a hurry to create release 0.13.2

Speaking of 0.13.2, why do we have multiple House TCJA reform files in taxcalc/reforms when the House has passed a bill.  Don't we want **one** `TCJA_House.json` file that represents the best Tax-Calculator can do at modeling the House-passed bill?  Presumably that would include use of the new `_cpi_offset` parameter (see pending pull request #1667) and a new parameter to implement the logic discussed in issue #1671.

@MattHJensen @codykallen 
@Amy-Xu @andersonfrailey @hdoupe @GoFroggyRun

**Comment by codykallen** [comment]
@martinholmer asked

> Speaking of 0.13.2, why do we have multiple House TCJA reform files in taxcalc/reforms when the House has passed a bill. Don't we want one TCJA_House.json file that represents the best Tax-Calculator can do at modeling the House-passed bill? 

We made multiple versions to account for how the bill evolved. This allowed the comparison of multiple versions, although this is less useful now that it has been passed by the House.

**Comment by martinholmer** [comment]
@codykallen said:
> We made multiple versions to account for how the bill evolved.  This allowed the comparison of multiple versions ...

I think that approach was very sensible.

> although this is less useful now that it has been passed by the House.

That's my point.  Going forward the evolution of the House bill is pretty academic.
Why not focus on the evolution of the Senate bill and have one JSON reform file for the House-passed bill?

@MattHJensen

**Comment by MattHJensen** [comment]
> That's my point. Going forward the evolution of the House bill is pretty academic.
Why not focus on the evolution of the Senate bill and have one JSON reform file for the House-passed bill?

I'd prefer to keep these because some of our users have wanted to compare different versions of the bill and see how priorities shifted as it evolved over time. I also don't see much a maintenance cost to keeping them. We will need a better and more-consistent naming scheme though.

**Comment by MattHJensen** [comment]
> would include use of the new _cpi_offset parameter (see pending pull request #1667) and a new parameter to implement the logic discussed in issue #1671.

I agree that the json files should be updated to include the new _cpi_offset parameter. I'm not sure about #1671 -- the legislative text really is ambiguous as far as I can tell. @codykallen, what do you think?

**Comment by codykallen** [comment]
@MattHJensen, there certainly is at least some ambiguity. Perhaps we should open a separate issue to discuss any potential notes and comments to add to each of the TCJA json files.

**Comment by MattHJensen** [comment]
Merging. Thanks again @martinholmer 

cc @GoFroggyRun

**Pull request merged**
