### PR TITLE
Trump2016

### PR DESCRIPTION
**Pull request by MattHJensen**
Adds a reform file for Trump 2016. 

Here are the static effects in 2022:

Trump payroll taxes: 1338.82
Trump income taxes: 1543.09
Current law payroll taxes: 1338.82
Current law income taxes: 1849.58

```
python ../../inctax.py ../../puf.csv 2022 --blowup --weights --reform 'Trump2016.json'
awk '{r+=$6*$29}END{print r*1e-9}' ../../puf-22.out-inctax-Trump2016
awk '{r+=$4*$29}END{print r*1e-9}' ../../puf-22.out-inctax-Trump2016
awk '{r+=$6*$29}END{print r*1e-9}' ../../puf-22.out-inctax
awk '{r+=$4*$29}END{print r*1e-9}' ../../puf-22.out-inctax
```

@martinholmer, could you take a look as this is my first reform file contribution?

@codykallen, does the reform itself match up with what you've been using from Trump2016? 

(Note that this contains a couple of _STD related commits from #1134 -- see an explanation over there)

### CODE REVIEW

**Comment by codykallen** [comment]
For the standard deduction, the entry for widows should be raised to either $30,000 or $15,000. Since tax law typically treats a newly widowed person as though still a joint filer, so I believe that standard deduction should be kept in line with the tax treatment for married couples filing jointly. Otherwise, it looks fine to me.

**Comment by MattHJensen** [comment]
Thanks @codykallen. fixed.

**Comment by martinholmer** [comment]
@MattHJensen asked me:
> Could you take a look as this [as it] is my first reform file contribution?

The `Trump2016.json` file looks great to me; I like the extensive use of comments at the top of the file.  You could make it even more didactic by adding comments after each policy parameter linking that parameter to the reform provision it is implementing.  This would be easier if you numbered the nine reform provisions in the comments at the top of the file.  Then you could write something like:
```
...
// (8)  New above the line deduction for child and elder care
// (9)  Cap itemized deductions
...
"_ID_c": // part of reform provision (9)
       {"2017": [[100000, 200000, 100000, 100000, 200000, 100000]]}
...
```

In terms of using this reform file with the `inctax.py` command-line interact to Tax-Calculator, you used this command
```
python ../../inctax.py ../../puf.csv 2022 --blowup --weights --reform 'Trump2016.json'
```
which seems to have worked fine.  But there is really no need to put quotes around the name of the reform file.

@feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen @zrisher

**Comment by MattHJensen** [comment]
@martinholmer, thank you for your comments. Please see the latest commit. 

One of your suggestions was:

> You could make it even more didactic by adding comments after each policy parameter linking that parameter to the reform provision it is implementing. This would be easier if you numbered the nine reform provisions in the comments at the top of the file. 

Instead I referenced the names of relevant parameters in the comments at the top of the file:

```
// Title: 2016 Trump Campaign Tax Plan 
// Reform_File_Author: Matt Jensen
// Reform_Reference: https://www.donaldjtrump.com/policies/tax-plan   
// Reform_Description:
// -  New personal income tax schedule (regular/non-AMT/non-pass-through) (1) 
// -  New pass-through income tax schedule (2) 
// -  New long-term capital gains and qualified dividends tax schedule (3) 
// -  Repeal Alternative Minimum Tax (4) 
// -  Repeal Net Investment Income Tax (5) 
// -  Raise the Standard Deduction (6) 
// -  Repeal the Personal Exemption (7) 
// -  New above the line deduction for child and elder care (8)
// -  Cap itemized deductions (9) 
// Reform_Parameter_Map:
// - 1: _II_rt*, II_brk*
// - 2: _PT_*
// - 3: _CG_*
// - 4: _AMT_*
// - 5: _NIIT_rt
// - 6: _STD
// - 7: _II_em
// - 8: _ALD_Dependents*
// - 9: _ID_c
```
I have been wondering lately whether we will eventually settle on some standard information that is included in these reform files. We may then want to store that information in JSON attributes rather than in comments. The style exhibited in this PR may be more natural that style. 

This is also related to @feenberg's suggestion to allow TaxBrain users to specify titles of the reforms on the input pages (see https://github.com/OpenSourcePolicyCenter/webapp-public/issues/275). If we allow users to specify titles on TaxBrain input pages, we may also want them to be able "sign" the pages with their names (or ask an admin to do so for them), add a description of the reform, and provide a reference if any. 

It also relates to your suggestion to implement "a way of saving the reform file associated with TaxBrain run results" (see https://github.com/OpenSourcePolicyCenter/webapp-public/issues/312). If a user is adding a title and other stuff to their TaxBrain input page, it seems that it should be saved in the reform file rather than in some TaxBrain database.

**Comment by martinholmer** [comment]
@MattHJensen said several things:
> One of your suggestions was:
>
>> You could make it even more didactic by adding comments after each policy parameter linking that parameter to the reform provision it is implementing. This would be easier if you numbered the nine reform provisions in the comments at the top of the file.
>
> I addressed this issue by including a mapping between reforms and parameters in the comments at the top of the file:
```
// Title: 2016 Trump Campaign Tax Plan 
// Reform_File_Author: Matt Jensen
// Reform_Reference: https://www.donaldjtrump.com/policies/tax-plan   
// Reform_Description:
// -  New personal income tax schedule (regular/non-AMT/non-pass-through) (1) 
// -  New pass-through income tax schedule (2) 
// -  New long-term capital gains and qualified dividends tax schedule (3) 
// -  Repeal Alternative Minimum Tax (4) 
// -  Repeal Net Investment Income Tax (5) 
// -  Raise the Standard Deduction (6) 
// -  Repeal the Personal Exemption (7) 
// -  New above the line deduction for child and elder care (8)
// -  Cap itemized deductions (9) 
// Reform_Parameter_Map:
// - 1: _II_rt*, II_brk*
// - 2: _PT_*
// - 3: _CG_*
// - 4: _AMT_*
// - 5: _NIIT_rt
// - 6: _STD
// - 7: _II_em
// - 8: _ALD_Dependents*
// - 9: _ID_c
```

That looks good.

> I expect that we will eventually settle on some standard information that is included in these reform files. We may then want to store that information in JSON attributes rather than in comments, and the style exhibited in this PR would work in attributes.

Maybe.  I think we should think carefully about the benefits and costs of imposing additional required JSON information.  I, for one, would be put off by being forced to fill out a lot of JSON information.

> Note that this relates to @feenberg's suggestion to allow TaxBrain users to specify titles of the reforms on the input pages (see OpenSourcePolicyCenter/webapp-public#275). If we allow users to specify titles on TaxBrain input pages, we may also want them to be able "sign" the pages with their names (or ask an admin to do so for them), add a description of the reform, and provide a reference if any.

I can see his interest in this title feature and especially being able to list all his output URLs.  As you can  see in the `taxcalc/taxbrain/file*.json` files, I put the output URL in the comments at the top of each file so I could remember how get back to the TaxBrain output page.  Just a title would not enable that.  Because my workflow involves using only the TaxBrain file upload capability, I can use the comments in the uploaded file to remember all the information that I deem important including the TaxBrain output URL.  My "TaxBrain run list" is all the *.json files in my analysis directory.  Because they are text files, I can `grep` for keywords of interest and I can do detailed comparisons of two reforms using my favorite graphical diff utility.  These abilities are far beyond what TaxBrain offers.  So, whatever is added to the parameter-input TaxBrain page is really not relevant to me.

> It also relates to your suggestion to implement "a way of saving the reform file associated with TaxBrain run results" (see OpenSourcePolicyCenter/webapp-public#312). If a user is adding a title and other stuff to their TaxBrain input page, it seems that it should be saved in the reform file rather than in some TaxBrain database.

After gaining some experience with the new TaxBrain file upload capability, I think it now meets all my needs.  I don't see any value in storing JSON reform files in the TaxBrain database.  It is much better to keep them on my local computer where I can `grep` and `diff` them and copy them to start a new reform file.

@feenberg @talumbau @Amy-Xu @andersonfrailey @GoFroggyRun @zrisher @codykallen

**Comment by MattHJensen** [comment]
This is good now. Merging. We are still thinking about whether and how to store the meta data in json attributes rather than comments, so I am leaving it in comments for now.

**Pull request merged**
