### PR TITLE
Code changes to handle new age variables in puf.csv file

### PR DESCRIPTION
**Pull request by martinholmer**
Read the two "Change code ..." commit messages for details on the code changes.

The main reason for adding the age_head and age_spouse variables to the `puf.csv` file is to be able to implement the EITC-age-eligibility rule for filing units without any EITC-eligible children.  Previously, Tax-Calculator was enforcing the maximum eligibility age of 64, but not the minimum eligibility age of 25.  This problem was identified in pull request #687.

After this pull request is merged into the master branch, a new version of the `puf.csv` file will be distributed.

The changes in this pull request do not change any of the non-pufcsv unit test results and do not change any of the fifteen Internet-TAXSIM validation test results.  However, the changes do affect the two pufcsv unit test results.  Here is an explanation of why that is and the magnitude of the changes (excerpted from the commit message):

```
Use age_head and age_spouse variables to implement the EITC age
eligibility rule for tax filing units with no EITC-eligible children.
The minimum eligibility age of 25 and maximum eligibility age of 64
are hard coded.  A subsequent pull request will replace them with new
policy parameters.

Implementing this EITC age-eligibility rule causes a decline in
refundable tax credits (because some young people were incorrectly
receiving an EITC before these changes were made) and a corresponding
rise in total income tax liabilities.  So, for example, in 2013
refundable credits drop from 114.8 to 111.4 billion, a decrease of 3.4
billion, which represents a decline of about 3.0 percent, while total
income tax liability rises from 1,226.5 to 1,230.3 billion, an
increase of 3.8 billion, which represents a rise of about 0.3 percent.
```

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun

### CODE REVIEW

**Comment by GoFroggyRun** [comment]
@martinholmer: 

Thanks for adding these CPS-matched age variables, and resulting changes in puf test make a lot of sense to me. 

Since I haven't got the updated `puf` yet, I, just to make sure, have one question in mind: what types of variable are `blind_head` and `blind_spouse`? Are they indicator variables? Moreover, it seems to me that your proposed changes would allow the `_extrastd` to be over 2, which I'm not quite sure about. Shall we cap this variable by 2 or 1, according to that unit's `MARS` status? 

Rest of the changes look good to me.

**Comment by martinholmer** [comment]
Sean (@GoFroggyRun) said:
> Since I haven't got the updated puf yet, I just want to make sure and have one question in mind: what types of variable are blind_head and blind_spouse? Are they indicator variables?

Yes, they are zero-one variables indicating whether or not a person is blind.  See the `taxcalc/var_labels.txt` file in pull request #701 for documentation.  The variables are not in the new or old `puf.csv` file.  When not read from the input data file, Tax-Calculator initializes them to zero.

> Moreover, it seems to me that your proposed changes would allow the _extrastd to be over 2 for MARS == 2 and over 1 for the rest [of the filing-unit types], which I'm not quite sure about.  Shall we cap this variable by 2 or 1, according to that unit's MARS status?

I don't think `_extrastd` should be capped.  I'm basing that view on two different bits of information.  First, the `taxcalc.sas` program does not cap the number of extra standard deductions.  And second, the IRS rules do not cap the extra deductions as shown in Table 20-2 of [this IRS document](https://www.irs.gov/publications/p17/ch20.html#en_US_2015_publink1000283783).

**Comment by GoFroggyRun** [comment]
@martinholmer:
>
I don't think _extrastd should be capped. I'm basing that view on two different bits of information. First, the taxcalc.sas program does not cap the number of extra standard deductions. And second, the IRS rules do not cap the extra deductions as shown in Table 20-2 of this IRS document.

I see. Thanks for you explanation. Changes in this PR look all good to me then.

**Comment by MattHJensen** [comment]
LGTM and well documented. Thanks @martinholmer and @GoFroggyRun! Merging. 

@Amy-Xu, could you please distribute the new puf.csv file among the cleared recipients?

**Comment by Amy-Xu** [comment]
@MattHJensen The testing version for EITC was created based on second to the last CPS match. Do we want to distribute that version, or a puf.csv based on March 2015 match?

**Comment by martinholmer** [comment]
@Amy-Xu said:
> The testing version for EITC was created based on second to the last CPS match. Do we want to distribute that version, or a puf.csv based on March 2015 match?

You must distribute the version you sent out last week for testing pull request #701, otherwise none of the test results will be correct.  If we are going to do another (unrelated to #701) enhancement to the `puf.csv` file, that needs to be distributed in association with another pull request that changes all the test results.

@MattHJensen

**Comment by Amy-Xu** [comment]
@martinholmer Got you. Will distribute in a minute.

**Pull request merged**
