### PR TITLE
ignore conda test when running regularly

### LINKED ISSUE #660: conda.recipe\run_test fails when running the standard test suite
Following the [getting started guide](http://taxcalc.readthedocs.org/en/latest/contributor_guide.html), upon running `py.test -m "not requires_pufcsv"` a user is presented with 111 successes and 1 error:

```
conda.recipe\run_test.py:1: in (module)
    import taxcalc
E   ImportError: No module named `taxcalc`
```

I'm not super familiar with pytest and standard setups, but I have to imagine that this test is only meant to be run after Conda follows the recipe to build the package (especially since the above line is the entire test). 

When run from the taxcalc repo itself and not building, it makes sense that this would fail, correct? 

If so, should a contributor use one of pytest's [skipping methods](https://pytest.org/latest/skipping.html) to avoid this test?

### PR DESCRIPTION
**Pull request by zrisher**
Fixes #660

### CODE REVIEW

**Comment by talumbau** [comment]
This looks good to me. +1 for merging.

**Comment by martinholmer** [comment]
Zach (@zrisher),
What is the status of pull request #670.   T.J. has approved it.
If it were merged into the master branch, would it resolve issue #660?

Does anybody have any problems or concerns with pull request #670?
If not, I will merge pull request #670 and close the resolved issue #660 on Wed,4/27.

@MattHJensen @talumbau

**Comment by zrisher** [comment]
@martinholmer Yep, this fixes #660 and I'm good on merging it.

**Comment by martinholmer** [comment]
@MattHJensen,
Everybody seems to agree that pull request #670 should be merged into the master branch.
Do you want to handle that?

**Comment by MattHJensen** [comment]
Merging. Thanks @zrisher, @talumbau, and @martinholmer.

**Pull request merged**
