### PR TITLE
Form tax calculation

### PR DESCRIPTION
**Pull request by zrisher**
**This is a Work In Progress and is posted here for discussion until ready for acceptance.**

This PR is an attempt to enable users to use Tax Form data in JSON format with Tax Calculator. 

It provides a command-line tool for some common tasks:
* ` python formtax.py example -d DST` - writes a set of example tax form files to DST
* ` python formtax.py calc -s SRC -d DST -p POLICY -e ECON` - reads the forms at SRC, calculates each of them for their given filing year with POLICY and ECON config sets, and writes the resulting forms (input + output) to DST.
* Soon it will also provide a `compare` method to write the calculation delta between two calculator config sets.

Full usage information is available with `python formtax.py -h`.

To accomplish this, I made some major changes to the `taxcalc.filings` package. These changes include some elements from https://github.com/open-source-economics/Tax-Calculator/issues/851 and https://github.com/open-source-economics/Tax-Calculator/issues/942. 

The impact to `taxcalc` code is limited to a few new utility methods and an additional `to_df` method on the `Records` class. Please let me know if you think this doesn't belong, but I found it quite helpful, and similar logic is used in both `taxcalc/incometaxio.py` and `taxcalc/simpletaxio.py`.

Remaining tasks for me:
* implement `USFilingCollection.compare_to()`
* add some missing function docstrings, fix some that were copied, and build out any that are lacking
* add a readme.md to the `filings` directory explaining its general architecture 
* implement a sanity-check integration test using a real-life example of form data and its expected results
* reduce the size of the unmapped records variables sets

Tests are fully passing, coverage is unchanged, and tax logic is unaffected.

@martinholmer @martinholmer @PeterDSteinberg
Please let me know what you'd like changed, I'm happy to adjust anything in here.

### CODE REVIEW

**Comment by zrisher** [comment]
My tests failed on Python 2.7 due to `AttributeError: 'list' object has no attribute 'copy'`. I'll fix that.

**Comment by MattHJensen** [comment]
@zrisher, if this is ready for review, could you drop the WIP tag? We use WIP to indicate that a PR is not ready for review yet.

**Comment by zrisher** [comment]
@MattHJensen Yes, sorry for the delay. By "WIP" I meant "likely to need changes from contributors so pending discussion", so I was using it incorrectly. However, the discovered Python 2 incompatibility makes it actually a WIP. I will submit a fix for that (along with the first 3 points above) by this weekend and then remove the tag.

**Comment by martinholmer** [comment]
Pull request #1184, which has been pending for over a year, was part of an effort that generated many valuable ideas and concepts that have been gradually incorporated into Tax-Calculator.  But that effort --- creating a Luca interface to Tax-Calculator --- has been dormant for a year.   Pull request #1184 is being closed now, but it can be reopened if the Luca project is started up again.   Thanks, @zrisher, for all the contributions your Luca effort generated.   They have made Tax-Calculator better than if the Luca project had not been undertaken.

**Pull request closed without merging**
