### PR TITLE
Replace use of two cmbtp_* variables with a single cmbtp variable

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request implements the solution suggested by Dan @feenberg to a problem discussed in issue #1073.  The slightly updated test results that are included in this pull request are generated using the new `puf.csv` file generated by [taxdata pull request 48](https://github.com/open-source-economics/taxdata/pull/48).  After merging this pull request into master, Tax-Calculator will continue to execute without error, but the `requires_pufcsv` unit tests will fail and the reform comparison tests will fail.  After updating to the new `puf.csv` file generated by taxdata pull request 48, all these test failures should be eliminated.

@MattHJensen @Amy-Xu @andersonfrailey

### CODE REVIEW

**Comment by martinholmer** [comment]
Are there any concerns with Tax-Calculator pull request #1077?

If not, I'll merge this pull request now that @Amy-Xu has merged [taxdata pull request 48](https://github.com/open-source-economics/taxdata/pull/48) and @andersonfrailey has made available to the OSPC team the new `puf.csv` file generated by the current taxdata master branch.

@MattHJensen @feenberg @talumbau @GoFroggyRun @codykallen

**Comment by MattHJensen** [comment]
@martinholmer, I'm taking a look now.

**Comment by MattHJensen** [comment]
@martinholmer, is this a fair characterization of the baseline changes?

The _entire_ difference in baseline results between this PR and master is due to the fact that in master we were incorrectly imputing AMT preference items (CMBTP) based on the tax unit's itemization decision in the current year rather than based on the tax unit's itemization decision in the data's base year. Correcting this resulted in new CMBTP values for those some tax units whose filing status changed between base year and current year. 

If so, then I understand everything and am +1

**Comment by martinholmer** [comment]
@MattHJensen wondered if the following was true:
> The entire difference in baseline results between this PR and master is due to the fact that in master we were incorrectly imputing AMT preference items (CMBTP) based on the tax unit's itemization decision in the current year rather than based on the tax unit's itemization decision in the data's base year. Correcting this resulted in new CMBTP values for those some tax units whose filing status changed between base year and current year.

Yes, that seems to be correct.  I was expecting no change in results under current law but there are actually some very small changes.  For example, 2020 income tax liabilities rise about $0.6 billion, which is an increase of less the 0.04 percent.  I assume that the difference in itemizer status in 2009 and in subsequent years is caused by different blowup rates for cmbtp and a few other itemized expense items.

@feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

**Comment by MattHJensen** [comment]
> I assume that the difference in itemizer status in 2009 and in subsequent years is caused by different blowup rates for cmbtp and a few other itemized expense items.

The difference in itemizer status in 2009 and in subsequent years would also be caused by differences in the tax schedule due to unequal indexing of tax law parameters and reforms that have been enacted since 2009. 

I'm +1 on this PR. Thanks @martinholmer.

**Comment by martinholmer** [comment]
@MattHJensen said:
> The difference in itemizer status in 2009 and in subsequent years could also be caused by differences in the tax schedule due to unequal indexing of tax law parameters and reforms that have been enacted since 2009.

Yes, I guess you are right about that.  I'll merge pull request #1077 on Tuesday.

@feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

**Comment by martinholmer** [comment]
Having heard no concerns about pull request #1077, it is being merged into the master branch.
Now the master branch is expecting the 21-Nov-2016 `puf.csv` file distributed by @andersonfrailey to the OSPC team.  The master branch code will "work" with earlier versions of the `puf.csv` file, but several tests will fail.

@MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun @codykallen

**Pull request merged**
