### PR TITLE
Add _CTC_new_for_all policy parameter and associated logic

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request attempts to resolve issue #1594.

There are very few filing units with both a negative AGI and children eligible for the child tax credit.  This means the difference between setting `_CTC_new_for_all` to true or false is quite modest.  Consider this arbitrary reform in the `ctcnew.json` reform file:
```
{"policy": {
    "_CTC_c": {"2013": [0]}, // turn off current-law CTC

    "_CTC_new_c": {"2013": [2000]},
    "_CTC_new_for_all": {"2013": [VALUE]},
    "_CTC_new_rt": {"2013": [9e99]}
}}
```
When **VALUE is false** (which is what the hardwired value is on the master branch), we get the following results:
```
$ tc puf.csv 2017 --reform ctcnew.json --tables
$ cat puf-17-ctcnew-#.tab.text
Weighted Tax Reform Totals by Baseline Expanded-Income Decile
    Returns    ExpInc    IncTax    PayTax     LSTax    AllTax
       (#m)      ($b)      ($b)      ($b)      ($b)      ($b)
 0    17.00    -119.4      -5.5       6.4       0.0       1.0
 1    17.00     152.4     -18.3      14.4       0.0      -3.8
 2    17.01     273.9     -33.1      24.5       0.0      -8.6
 3    17.00     400.6     -25.0      35.8       0.0      10.8
 4    17.01     558.3      -8.3      52.6       0.0      44.3
 5    17.01     754.0      19.5      72.0       0.0      91.5
 6    17.01    1008.8      54.6      97.0       0.0     151.5
 7    17.00    1379.3     108.4     143.2       0.0     251.6
 8    17.01    2054.4     202.5     233.3       0.0     435.8
 9    17.01    6272.4    1315.8     413.3       0.0    1729.1
 A   170.05   12734.6    1610.6    1092.6       0.0    2703.3

Weighted Tax Differences by Baseline Expanded-Income Decile
    Returns    ExpInc    IncTax    PayTax     LSTax    AllTax
       (#m)      ($b)      ($b)      ($b)      ($b)      ($b)
 0    17.00    -119.4      -2.9       0.0       0.0      -2.9
 1    17.00     152.4      -6.1       0.0       0.0      -6.1
 2    17.01     273.9      -8.2       0.0       0.0      -8.2
 3    17.00     400.6      -7.7       0.0       0.0      -7.7
 4    17.01     558.3      -7.4       0.0       0.0      -7.4
 5    17.01     754.0      -6.9       0.0       0.0      -6.9
 6    17.01    1008.8      -6.4       0.0       0.0      -6.4
 7    17.00    1379.3      -7.6       0.0       0.0      -7.6
 8    17.01    2054.4     -12.5       0.0       0.0     -12.5
 9    17.01    6272.4     -23.6       0.0       0.0     -23.6
 A   170.05   12734.6     -89.4       0.0       0.0     -89.4
```
The above results are exactly the same as on the master branch, which is what is expected.

When **VALUE is true**, we get the following results:
```
$ tc puf.csv 2017 --reform ctcnew.json --tables
$ cat puf-17-ctcnew-#.tab.text
Weighted Tax Reform Totals by Baseline Expanded-Income Decile
    Returns    ExpInc    IncTax    PayTax     LSTax    AllTax
       (#m)      ($b)      ($b)      ($b)      ($b)      ($b)
 0    17.00    -119.4      -6.5       6.4       0.0      -0.1
 1    17.00     152.4     -18.3      14.4       0.0      -3.9
 2    17.01     273.9     -33.2      24.5       0.0      -8.6
 3    17.00     400.6     -25.0      35.8       0.0      10.8
 4    17.01     558.3      -8.3      52.6       0.0      44.3
 5    17.01     754.0      19.5      72.0       0.0      91.5
 6    17.01    1008.8      54.6      97.0       0.0     151.5
 7    17.00    1379.3     108.4     143.2       0.0     251.6
 8    17.01    2054.4     202.5     233.3       0.0     435.8
 9    17.01    6272.4    1315.8     413.3       0.0    1729.1
 A   170.05   12734.6    1609.5    1092.6       0.0    2702.1

Weighted Tax Differences by Baseline Expanded-Income Decile
    Returns    ExpInc    IncTax    PayTax     LSTax    AllTax
       (#m)      ($b)      ($b)      ($b)      ($b)      ($b)
 0    17.00    -119.4      -4.0       0.0       0.0      -4.0
 1    17.00     152.4      -6.1       0.0       0.0      -6.1
 2    17.01     273.9      -8.3       0.0       0.0      -8.3
 3    17.00     400.6      -7.7       0.0       0.0      -7.7
 4    17.01     558.3      -7.4       0.0       0.0      -7.4
 5    17.01     754.0      -6.9       0.0       0.0      -6.9
 6    17.01    1008.8      -6.4       0.0       0.0      -6.4
 7    17.00    1379.3      -7.6       0.0       0.0      -7.6
 8    17.01    2054.4     -12.5       0.0       0.0     -12.5
 9    17.01    6272.4     -23.6       0.0       0.0     -23.6
 A   170.05   12734.6     -90.5       0.0       0.0     -90.5
```

The difference in aggregate tax liability is only $1.1 billion.

@MattHJensen @andersonfrailey @evtedeschi3

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey,  I haven't gotten any feedback from @evtedeschi3 on the changes in pull request #1595.
Do you think these changes provide the capability he was asking for in issue #1594?

**Comment by evtedeschi3** [comment]
Apologies, I’ve been slammed all day and haven’t had time to test out. My perusal of your followups suggest that yes, this addresses exactly what I asked. Anderson do you agree?

**Comment by martinholmer** [comment]
@evtedeschi3 said:
> Apologies, I’ve been slammed all day and haven’t had time to test out. My perusal of your followups suggest that yes, this addresses exactly what I asked. Anderson do you agree?

No need for apologies, we're all very busy.  Unless I hear some concerns from @andersonfrailey, we'll add these changes to Tax-Calculator release 0.12.0, which is imminent.

**Comment by MattHJensen** [comment]
The implementation looks good to me. Thanks @martinholmer for the contribution and thanks to @evtedeschi3 for the feature request and review.

**Comment by evtedeschi3** [comment]
Thank you both!

**Pull request merged**
