### PR TITLE
Add five new mtr_valid_income_types

### PR DESCRIPTION
**Pull request by martinholmer**
The valid MTR income types are now as follows:
```
'e00200p', taxpayer wage/salary earnings (which is the default value);
'e00900p', taxpayer (Schedule C) self-employment income;
'e00300',  taxable interest income;
'p23250',  long-term capital gains;
'e01700',  federally-taxable pension benefits; and
'e02400',  social security (OASDI) benefits.
```
Some of these new marginal tax rates can be compared with Internet-TAXSIM marginal tax rates, but that comparison work has not yet been done.

### CODE REVIEW

**Comment by martinholmer** [comment]
@Amy-Xu,  Coincidently, I was working on the mtr() method this morning.  So, I've added the self-employment income (which gets treated a little differently than wage and salary income in the FICA tax calculation).  If this if going to meet the needs of the macro modeling team, then drop the calculate.py changes from your renamed pull request #410 and we will merge this pull request #449 after a quick review.  Does this make sense as a way to proceed.  It appears as if #410 has other changes that are unrelated to this MTR issue.  Go ahead and merge those 'age' changes.

**Comment by martinholmer** [comment]
@MattHJensen,  Can you (and perhaps others) quickly review pull request #449, so that the self-employment income MTR feature can be merged into the master branch for use by the macro modeling team?

**Comment by Amy-Xu** [comment]
@martinholmer This makes a lot sense to me. The code looks good, but I was just wondering have you had a chance to check the MTR results on e00900p? I tried running the code of my PR and saw a lot zeros compared to MTR on e00200p. Not quite sure whether that's normal or not.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> The code looks good, but I was just wondering have you had a chance to check the MTR results on e00900p? I tried running the code of my PR and saw a lot zeros compared to MTR on e00200p. Not quite sure whether that's normal or not.

I'm checking this now.  Be back with some results and comments soon.

**Comment by martinholmer** [comment]
@Amy-Xu,  Here are some results for marginal FICA tax rates with respect to wages+salary ('e00200p') and then with respect to self-employment income ('e00900p') of the taxpayer:
```
> awk '{n[$9]++}END{for(r in n)print r,n[r]}' c13.in.out-simtax-ern
2.90 5516
3.80 13909
15.30 78027
16.20 2548
> awk '{n[$0]++}END{for(r in n)print r,n[r]}' c13.in.out-simtax-sei
2.68 5516
3.51 13909
14.13 78027
14.96 2548
```
**Can team members (who are more familiar with the payroll taxation of Schedule C self-employment income) comment on whether these differeces in marginal FICA tax rates look right?**

If they are correct, I really wonder about the macro model's need for this.  Given all the uncertainties involved in the kind of simulation they are doing, is it important to pay attention to MTR differences between 15.30 and 14.13?

cc @MattHJensen and @jdebacker

**Comment by martinholmer** [comment]
@Amy-Xu said:
> I tried running the code of my PR and saw a lot zeros [for marginal income tax rates] compared to MTR on e00200p.

You are right; this is a problem.  Apparently, the one-cent increase in e00900p income is affecting the FICA tax calculation, but not the income tax calcuation.  Is that because e00900 is used in all other places in the source code other than the FICA calculations?

**Comment by martinholmer** [comment]
@Amy-Xu,  I think the mtr() logic for 'e00900p' is fixed now.  If your testing agrees with my assessment, you could merge this pull request #449 into the master branch.

**Comment by Amy-Xu** [comment]
yep the MTRs make much more sense now. Merging!

cc @MattHJensen

**Pull request merged**
