### PR TITLE
Add _ALD_AlimonyReceived_hc policy parameter and logic

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request attempts to resolve issue #1815, which was raised by @codykallen.

@codykallen (and others) please review these changes to make sure they make sense.

These changes assume the timing of the changes in ALD treatment of alimony received under TCJA are the same as the timing of the changes in ALD treatment of alimony paid.  But I don't really know that.  Can anybody confirm the validity of this assumption?  If that assumption is false, what is the timing of the changes in ALD treatment of alimony received under TCJA?

I would like to merge these changes quickly so these changes can be included in pending pull request #1803.

### CODE REVIEW

**Comment by codykallen** [comment]
@martinholmer, can you clarify what you mean by timing?

**Comment by martinholmer** [comment]
@codykallen,  Just look at the proposed changes to the `TCJA_Reconciliation.json` file.  Are they correct?

**Comment by codykallen** [comment]
@martinholmer, the alimony provisions both take effect beginning in 2019.

**Comment by martinholmer** [comment]
@codykallen said:
> the alimony provisions both take effect beginning in 2019

Good.  That's the way it is in the PR.  Thanks for checking.  So does this PR look OK to you?

**Comment by codykallen** [comment]
Looks good to me.

**Pull request merged**
