### PR TITLE
test.py now calls calc_all()

### PR DESCRIPTION
**Pull request by GoFroggyRun**
This PR deals with issues discussed in #469 and #470 . 
The `test.py` script now calls the `calc_all` function so that we no longer needs to maintain `calc_caal_test`.
The outputs were also truncated and now have the same variables as the previous result (that executed through `calc_caal_test`). 
@martinholmer @MattHJensen Please take a look.

### CODE REVIEW

**Comment by martinholmer** [comment]
Sean @GoFroggyRun,
This revision to test.py look good to me.  Should this pull request also include the deletion of the ```calc_all_test()``` method in the Calculator class?
cc @MattHJensen

**Comment by GoFroggyRun** [comment]
@martinholmer Are you referring to [this part](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/calculate.py#L159-L192) in the `calculate.py`?

**Comment by martinholmer** [comment]
Sean @GoFroggyRun said:
> Are you referring to this part in the calculate.py?

Yes, I think it was the Calculator class calc_all_test method that @MattHJensen wanted to eliminate.

**Comment by martinholmer** [comment]
Sean @GoFroggyRun said:
> It turns out that the calc_all_test () was still referenced while doing py.test, see here. In this case we might also need to modify test_calculate.py as well, or shall we just leave calc_all_test () for testing purpose? 

Oh, I see this test in test_calculate.py is using the faux-PUF with 1991 data.  Once I realized that, I think we should __drop__ Calculator ```calc_all_test()``` and __drop__ the part of test_calculate.py that uses ```calc_all_test()```.
cc @MattHJensen

**Comment by GoFroggyRun** [comment]
@martinholmer Please take a look. `calc_all_test()` now got completely removed. (I'm basically adopting the same strategy as in `test.py` while revising the `test_calculate.py` file)

**Comment by martinholmer** [comment]
Sean @GoFroggyRun said:
> Please take a look.  calc_all_test() now got completely removed.  (I'm basically adopting the same strategy as in test.py while revising the test_calculate.py file.)

Looks good to me.  Shall I merge this @MattHJensen, or do you want to review?

**Comment by MattHJensen** [comment]
Go ahead and merge!


On Nov 19, 2015, at 6:40 AM, Martin Holmer <notifications@github.com<mailto:notifications@github.com>> wrote:


Sean @GoFroggyRun<https://github.com/GoFroggyRun> said:

Please take a look. calc_all_test() now got completely removed. (I'm basically adopting the same strategy as in test.py while revising the test_calculate.py file.)

Looks good to me. Shall I merge this @MattHJensen<https://github.com/MattHJensen>, or do you want to review?

**Pull request merged**
