### PR TITLE
Charity Contribution Parameter Issue

### PR DESCRIPTION
**Pull request by GoFroggyRun**

### CODE REVIEW

**Comment by GoFroggyRun** [comment]
Both [Pub 526](http://www.irs.gov/pub/irs-pdf/p526.pdf) and [IRS Charitable Contribution Deductions](http://www.irs.gov/Charities-&-Non-Profits/Charitable-Organizations/Charitable-Contribution-Deductions) indicate that there's no particular cap for charity cash contribution, while there is a general 50% cap for total charity contribution. Thus I suggest we remove the cap for cash contribution and parametrize the general 50% cap.

**Comment by MattHJensen** [comment]
@GoFroggyRun, what is the status of this PR?

**Comment by GoFroggyRun** [comment]
@MattHJensen:

I just resolved the merging conflicts for this PR. I'm unsure about, however, why the Travis CI is not working.

**Comment by MattHJensen** [comment]
@GoFroggyRun, would you mind reopening this PR off of master with only the relevant changes? Could you also check through the webapp-public code to see whether this will require any changes there?

**Pull request closed without merging**
