### PR TITLE
Eliminate Records.UNUSED_READ_VARS set given new puf.csv file

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request simplifies the logic of creating arrays from the Pandas dataframe that is generated in the Records class by reading the input data file.  There is no change in tax-calculation logic and no change in any of the test results.

However, the code in this pull request will work only when using the new smaller ```puf.csv``` file distributed to the core development team by Amy Xu on March 8, 2016.

And, in addition, there was a need to eliminate close to half of the variables in the puf91taxdata.csv file used in the test suite because almost half of the variables are unused in Tax-Calculator.

### CODE REVIEW

**Comment by martinholmer** [comment]
The reduction in the code coverage statistic is spurious: this pull request just simplifies the code by eliminating four statements.

**Comment by talumbau** [comment]
because this PR would make Tax-Calculator master non-backwards compatible with the existing PUF, can we put a one week hold on this? There are many balls in motion in regards to OSPC work right now and this would be a bad time to introduce a change into master that would break existing users of the current PUF.  cc @MattHJensen

**Comment by martinholmer** [comment]
T.J. said:
> Because this PR would make Tax-Calculator master non-backwards compatible with the existing PUF, can we put a one week hold on this? 

That was exactly my thought.  I was going to reply to everybody who received Amy's email about the new ```puf.csv``` file, to ask them to begin using the new, smaller puf.csv sometime during the next week.  But I can do it via this comment.

Would anybody like to suggest a target date for merging this pull request #638 into the master branch?
A date that gives everybody a chance to finish up what they are now working on using the old, bigger ```puf.csv``` file.

@MattHJensen @talumbau @feenberg @Amy-Xu @GoFroggyRun @rickecon @jdebacker @kerkphil

**Comment by Amy-Xu** [comment]
Martin, we just realized our macro team needs `e01500` in their scripts. I think we need to add it back to the list. It's a bit tricky where to put it, because if we add it to UNUSED_READ_VARS, it's not accessible from records anymore.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> Martin, we just realized our macro team needs e01500 in their scripts. I think we need to add it back to the list. It's a bit tricky where to put it, because if we add it to UNUSED_READ_VARS, it's not accessible from records anymore.

Two questions:
(1) what is e01500?
(2) what does macro model do with a variable that is unused in Tax-Calculator?

**Comment by jdebacker** [comment]
@martinholmer @Amy-Xu,
1) e01500 is total pension income (taxable plus nontaxable)
2) For the macro model we want comprehensive measures of total income and capital income. Hence we need to use information that includes income that is not taxable.

**Comment by martinholmer** [comment]
@jdebacker said:
> 1) e01500 is total pension income (taxable plus nontaxable)
> 2) For the macro model we want comprehensive measures of total income and capital income. Hence we need to use information that includes income that is not taxable.

Seems reasonable; thanks for the explanation.  I'll add e01500 back into the Records.VALID_READ_VARS set in just a few minutes.

Then @Amy-Xu will have to make, and distribute to the core development team, a new version of the ```puf.csv``` file that adds just that e01500 variable.

**Comment by Amy-Xu** [comment]
Thanks @martinholmer! It seems we won't switch to the new puf.csv before next Tuesday. I'll make it as soon as possible.

**Comment by MattHJensen** [comment]
@talumbau and @Amy-Xu, do you feel comfortable moving forward with this PR early next week? @Amy-Xu, do we need a new puf.csv from you first?

**Comment by talumbau** [comment]
@MattHJensen yes I can create a new version and deploy it along with a new PUF as soon as Amy says that she has the new PUF ready that meets Jason's needs.

**Comment by Amy-Xu** [comment]
@talumbau I'm examining how easy it is to add a few healthcare expense related variables to the dataset. Once I figure this out, it won't take long to create a new PUF. Will let you know as soon as possible.

**Comment by Amy-Xu** [comment]
@talumbau I have created a testing version of puf, and asked Martin to review. Should be able to distribute the new version after I hear back from him.

**Comment by martinholmer** [comment]
Amy said:
> I have created a testing version of puf, and asked Martin to review.
Should be able to distribute the new version after I hear back from him.

Do you want me to include the new WEIGHTS.csv file in pull request #638?

**Comment by Amy-Xu** [comment]
That would be convenient! Thanks @martinholmer

**Comment by martinholmer** [comment]
Martin said:
> Do you want me to include the new WEIGHTS.csv file in pull request #638?

And then Amy said:
> That would be great!  Thanks

On second thought, I don't think it is a good idea to include your changes in WEIGHTS.csv in my pull request #638.  PR#638 does not change any test results, while the new WEIGHTS.csv file changes all the puf.csv-related test results.  We should keep them separate to clarify that PR#638 does not change any test results.

So, please create a pull request of your own that includes the new WEIGHTS.csv and the changed test results that are generated by that new file and the new puf.csv file.   Then, after you do that, I'll merge those changes into my PR#638.  Does that make sense?

@Amy-Xu @MattHJensen @talumbau

**Comment by Amy-Xu** [comment]
I'll open that PR soon. It seems I need to examine the difference in the statistics summary before distributing a new PUF or getting that new PR merged. Will let you know as soon as I'm done. @martinholmer @talumbau

**Comment by Amy-Xu** [comment]
@martinholmer There's something wrong in the extrapolation and I have not entirely figured out what happened. @MattHJensen thinks we should stick to the current matched file but the skinner version. I'll just work on that one and distribute in a sec.

**Comment by martinholmer** [comment]
Amy said:
> @martinholmer There's something wrong in the extrapolation and I have not entirely figured out what happened. @MattHJensen thinks we should stick to the current matched file but the skinner version. I'll just work on that one and distribute in a sec.

OK

**Comment by MattHJensen** [comment]
Thank you @martinholmer and @Amy-Xu! Merging. 

@talumbau, @martinholmer, @Amy-Xu, @jdebacker, @GoFroggyRun, @rickecon, @feenberg: 

Please note that we all need to begin using the puf.csv file that Amy emailed at 9:35 pm yesterday. Older versions of the puf.csv will no longer be compatible with tax-calculator/master. There should be no change in results.

**Pull request merged**
