### PR TITLE
Add new unit test to check for taxcalc package

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request adds a new pytest that will fail whenever the unit tests are run when a taxcalc package is installed.  This test is meant to help alert developers to the confusing situation described in issue #1231.

### CODE REVIEW

**Comment by martinholmer** [comment]
Does anybody have any ideas about why the new test in pull request #1435 works on my computer (OSX, Python 2.7) but does not work on the GitHub checkin run of the test?  Here is the new test:
```
def test_for_package_existence():
    """
    Ensure that no conda taxcalc package is installed when running pytest
    """
    out = subprocess.check_output(['conda', 'list', 'taxcalc'])
    if re.search('taxcalc', out.decode('ascii')) is not None:
        assert 'taxcalc package' == 'installed'
```
My understanding is that when run on GitHub the pytest suite is executed from code in the taxcalc-dev environment and that there is no conda taxcalc package involved.  But since things are not working, my understanding must be wrong.

@MattHJensen @PeterDSteinberg

**Comment by hdoupe** [comment]
@martinholmer, I just ran the test on in my local environment (OSX, python 3.6).  I added a print statement so that I could see the contents of `out.decode('ascii')` and got the following ouput:


```
# packages in environment at /anaconda/envs/taxcalc-dev:
#
```
and traceback: 
```

Traceback (most recent call last):
  File "test_4package.py", line 16, in <module>
    test_for_package_existence()
  File "test_4package.py", line 13, in test_for_package_existence
    assert 'taxcalc package' == 'installed'
AssertionError
```

It looks like re.search is finding taxcalc in the string "packages in environment at /anaconda/envs/taxcalc-dev:"  I hope this helps.

**Comment by martinholmer** [comment]
@hdoupe said about problem with pull request #1435:
> It looks like re.search is finding `taxcalc` in the string "packages in environment at /anaconda/envs/taxcalc-dev:" I hope this helps.

Thanks!  And, yes, I think your insight will help.  Back to the drawing board for me.

**Comment by hdoupe** [comment]
@martinholmer No problem, glad I could help!

**Comment by martinholmer** [comment]
@hdoupe,  I tried to factor in your insight on #1435 in the newest version.
The Windows/Python3.6 test passed on GitHub (so that is progress), but
all three of the Linux tests on GitHub failed.
Does the newest version of #1435 pass on your computer?

**Comment by hdoupe** [comment]
@martinholmer, #1435 passes on my computer for python 2.7 and 3.6.

**Comment by martinholmer** [comment]
@hdoupe said:
> [latest version of] #1435 passes on my computer for python 2.7 and 3.6.
Thanks so much for checking.

**Comment by hdoupe** [comment]
@martinholmer, what do you think about doing something like this?

```
def test_for_package_existence():
    """
    Ensure that no conda taxcalc package is installed when running pytest
    """
    installed = True
    try:
        import taxcalc
    except ImportError:
        installed = False

    if installed:
        assert 'taxcalc package' == 'installed'
```

**Comment by martinholmer** [comment]
@hdoupe suggested using `try import taxcalc` construct.

A good idea, but I couldn't get it to work reliably on my computer,
maybe because we're using an absolute-addressing import style that
involves `from taxcalc import ...` statements.

Anyway, the latest version just by-passes the execution of the new test on GitHub.

The whole point of the new test is to help developers discover a mistakenly installed taxcalc package on their own computer, which is a problem I've had in the past (and I think Anderson was also a victim of this problem as described in issue #1231).  So, there really is no reason to run the test on GitHub.

**Pull request merged**
