### PR TITLE
[WIP] Adding Corporate Income Tax Distribution

### PR DESCRIPTION
**Pull request by yuying27**
Besides the function modifications, I write a brief description "CIT_description.pdf" discussing current results and problems.  Also, I create a notebook "Corp_Inc_Tax_Test.ipynb" for testing purpose.

I modify several lines in the test files to pass the py.test.

All the codes in comments within function.py are alternative ways to distribute the tax. Basically, only keeping stock gains and dropping all the loss.

The [TPC paper](http://www.taxpolicycenter.org/publications/how-tpc-distributes-corporate-income-tax/full) I refer to.

### CODE REVIEW

**Comment by Amy-Xu** [comment]
@yuying27 forgot to tell you that you need to install a formatting check tool called pep8. Could you install that and fix the formatting issues you have? It seems your PR has passed all other tests.

**Comment by Amy-Xu** [comment]
This PR is to replace PR #286.

**Comment by yuying27** [comment]
@Amy-Xu Of course. I will figure it out.

**Comment by martinholmer** [comment]
@yuying27,  When I run `py.test` on my computer using your pull request #1479, I get all these errors:
```
============================= test session starts ==============================
platform darwin -- Python 2.7.13, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/mrh/work/OSPC/tax-calculator, inifile: setup.cfg
collected 301 items 

tests/test_4package.py .
tests/test_behavior.py ..F....
tests/test_calculate.py ........FFFFF.F.......
tests/test_consumption.py ......F
tests/test_decorators.py ................
tests/test_dropq.py .FFFFF...FF.......
tests/test_consumption.py .F.....F
tests/test_decorators.py ........F.....F...
tests/test_dropq.py .FFFFFFFF...FFFFFFFFF
tests/test_functions.py ..
tests/test_growdiff.py ....
tests/test_growfactors.py ...
tests/test_macro_elasticity.py F
tests/test_parameters.py .........
tests/test_policy.py ...F....................
tests/test_pufcsv.py FFFFF
tests/test_records.py ..............
tests/test_reforms.py .
tests/test_responses.py .
tests/test_taxcalcio.py .....F
tests/test_functions.py ...
tests/test_growdiff.py ....
tests/test_growfactors.py ...
tests/test_macro_elasticity.py .F
tests/test_parameters.py .........
tests/test_policy.py .......................
tests/test_pufcsv.py .....F.....
tests/test_utils.py .......F...............FF
tests/test_records.py .F.............
tests/test_reforms.py F.....F.
tests/test_responses.py .
tests/test_taxcalcio.py ...F..F..FFFFF...
tests/filings/forms/test_tax_form.py ...............
tests/filings/forms/test_tax_forms.py ..........................................................................
validation/taxsim/test_simpletaxio.py .....................

=================================== FAILURES ===================================
```
That's 39 test failures.

I see on the Tax-Calculator [Network Graph](https://github.com/open-source-economics/Tax-Calculator/network) that you started this PR over three weeks ago, but you haven't merged into your branch any of the many commits to the master branch that have been made by others since then.  So the code in your PR is very out-of-date.  You can fix this by doing: `git checkout corpinc ; git merge master` assuming you are up-to-date with your master branch.  If you don't know how to make your local master branch be up-to-date with what is on GitHub, read the Contributor Guide, a link to which is available in the [README documentation](https://github.com/open-source-economics/Tax-Calculator#developing-tax-calculator).

**Comment by yuying27** [comment]
@martinholmer Thank you for your information! I will update my local master and consolidate the codes.

**Pull request closed without merging**
