### PR TITLE
Calculate taxable OASDI benefits and Schedule R credit

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request contains changes in Tax-Calculator logic that are required for it to pass comprehensive cross-model-validation tests.  These changes involve calculating in all cases the values of the `c02500` variable (OASDI benefits included in AGI) and the `c07200` variable (Schedule R credit).

Prior to these changes, the SSBenefit function set `c02500` equal to `e02500` when MARS was equal to 3 or 6.  This would mean that whenever Tax-Calculator used a cross-model-validation input file that did not include the `e02500` would have incorrect `c02500` values for filing units with MARS equal to 3 or 6.

And also, prior to these changes, the NonEdCr function set `c07200` (the Schedule R credit) equal to `e07200` for all filing units.  This would mean that whenever Tax-Calculator used a cross-model-validation input file that did not include the `e07200` would have incorrect `c07200` values for all filing units that are eligible for a Schedule R credit by virtue of their age.

### CODE REVIEW

**Comment by martinholmer** [comment]
Commit 38d3cbb in pull request #810 causes small changes in the two pufcsv unit test results.  Five of the ten aggregate income tax liability amounts for 2013-2022 change by $0.1 billion, while the other five are unchanged (when rounded to the nearest $0.1 billion).  These five changes involve a relative decline in income tax liability of no more than 0.007 percent.  And there are a few filing units who are now in different marginal tax rate histogram bins.

There are also (beneficial) changes in two of the reform comparison results:
```
 Exclusion of untaxed social security and railroad retirement
 -Tax-Calculator,39.2,41.0,43.6,46.0
 +Tax-Calculator,39.5,41.3,43.9,46.4
  Tax Expenditure,39,42,44,47
  Budget Options,35,37,38,40
```
and
```
Charitable
 -Tax-Calculator,44.4,47.0,49.7,52.5
 +Tax-Calculator,44.4,47.0,49.7,52.4
  Tax Expenditure,46,47,48,50
```

**Comment by martinholmer** [comment]
Commit b54ca19 in pull request #810 does not change any Tax-Calculator results because the default value of the `_calc_sch_r` variable is zero, which means that the new Schedule R code is not used.

**Comment by martinholmer** [comment]
Pull request #810 is ready for review and comment.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @zrisher

**Comment by martinholmer** [comment]
Commit 3836305 in pull request #810 makes Tax-Calculator default logic calculate the Schedule R credit.  These logic changes cause a few rounding-error differences in `tests/pufcsv_agg_expected.txt` results file and in the `comparison/reform_results.txt` results file.  These logic changes also produce more accurate results in the `tests/pufcsv_mtr_expected.txt` results file because Tax-Calculator logic prior to pull request #810 ignored the marginal tax rate effects of the Schedule R credit.

@MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun @zrisher

**Comment by martinholmer** [comment]
Tax-Calculator pull request #810 is ready to merge into the master branch unless there are concerns.

@MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun @zrisher

**Comment by MattHJensen** [comment]
Lgtm. Thanks @Martinholmer.

**Pull request merged**
