### PR TITLE
The tbi run_nth_year_tax_calc_model function now returns full tables

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request standardizes the tables generated by the TaxBrain Interface (tbi) so that the full table is always returned by the `run_nth_year_tax_calc_model` function.  Beginning with this pull request, all the table rows generated by the Calculator create table methods (whether using deciles and bins) are returned by the `run_nth_year_tax_calc_model` function.  TaxBrain can then decide whether to show all of the table or only part of the table.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@hdoupe may want to take a look.

**Comment by hdoupe** [comment]
Thanks for tagging me in this PR.

@martinholmer can you leave this open until the end of day on Monday so that I can run this against PolicyBrain?

**Comment by martinholmer** [comment]
@hdoupe asked the following about Tax-Calculator pull request #1914:
>  Can you leave [1914] open until the end of day on Monday so that I can run this against PolicyBrain?

Sure.  I'm in no rush.  I'm waiting for pull request #1909 to be ready for review.  

While the changes in #1909 and #1914 would, in theory, take just a little programming at your end, it would appear you need to rework the TaxBrain handling of Tax-Calculator tables in a much broader way.  I'm guessing that given the following two observations:  

1. Tax-Calculator has been for many months producing in the **difference table** the percentage-change-in-aftertax-income statistic, but it has never been displayed by TaxBrain.  That statistic is key for any repeal-benefits-and-add-UBI reforms, so you would have needed to do work on the display of tables this month even if pull request #1914 did not exist.  I reported this TaxBrain problem in [PolicyBrain issue 770](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/770) back in December.

2. The **distribution table** is missing key statistics as reported in [PolicyBrain issue 771](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/771).

Here is what the current version of TaxBrain shows for the difference table.

screen shot 2018-03-10 at 6 46 23 pm

@MattHJensen @GoFroggyRun

**Comment by martinholmer** [comment]
@hdoupe, Instead of testing #1914, you should test #1917, which contains all the changes in $1914 plus adds a new row to both the distribution table and the difference table.

**Comment by martinholmer** [comment]
@hdoupe said in [PolicyBrain pull request 846](https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/846):
> This PR updates to the tables specified in open-source-economics/Tax-Calculator#1917. The update is fairly straight forward. The table labels still need to be updated. For now, they are just the variable names.

Pull request #1917 includes all the code changes in #1914.

**Pull request merged**
