### PR TITLE
Revise FLPDYR logic along lines suggested by Dan Feenberg

### PR DESCRIPTION
**Pull request by martinholmer**
When not specifying a start_year in the Records constructor, the current_year and FLPDYR variable are now set to PUF_YEAR, so that ages will be correctly calculated.  Also, remove the increase of FLPDYR by one in the increment_year() method in order to calculate ages correctly.  These changes imply that FLPDYR no longer needs to be included in the MUST_READ_VARS list.

This pull request resolves issue #517 in a way that assumes the Tax-Calculator will always be using the most recently available IRS/SOI PUF data when two of the arguments of the Records class constructor are at their default values: that is, when data='puf.csv' and start_year=None.

As before these changes, data other than the most recent IRS/SOI PUF data can be read by the Records class as long as the name of the file is supplied as the data argument of the Records constructor and the year of the data is specified in the start_year argument of the Records constructor.

cc @MattHJensen @feenberg @Amy-Xu @GoFroggyRun

### CODE REVIEW

**Comment by Amy-Xu** [comment]
The code change looks good to me. I was just wondering whether we should remind users that if they do have a file with different FLPDYR they want to use as _current_year, they have to do that manually for Record object. Do we need to add one line of comment somewhere?

**Comment by martinholmer** [comment]
@Amy-Xu said:
> The code change looks good to me.  I was just wondering whether we should remind users that if they do have a file with different FLPDYR they want to use as _current_year, they have to do that manually for Record object.  Do we need to add one line of comment somewhere?

Probably a good idea.  It seems appropriate to put that comment in the doc-string for the Record class constructor, which is where users would specify a non-PUF filename and a non-PUF start_year.  Does that seem sensible?  If so, I'll do that soon.  Thanks for the suggestion, Amy.

**Comment by martinholmer** [comment]
@Amy-Xu,  I've added comments to Records class constructor documentation as well as point users who want to use their own data to the test_Calculator_using_nonstd_input() function in test_calculate.py file.

**Comment by Amy-Xu** [comment]
Looks good to me. Thanks Martin!! Merging.

**Pull request merged**
