### PR TITLE
add YAML file for RTD

### PR DESCRIPTION
**Pull request by talumbau**

### CODE REVIEW

**Comment by talumbau** [comment]
@MattHJensen it seems that simply adding this file (to trigger building with conda on RTD) fixes the build issues. I pushed this change to a sub-branch of this repo and got a successful build:

https://readthedocs.org/projects/taxcalc/builds/3776604/

So I think we can merge and master will build properly again.

**Comment by MattHJensen** [comment]
Cool. Thanks @talumbau! 

cc @martinholmer

**Comment by MattHJensen** [comment]
Is the [WIP] tag still appropriate?

**Comment by talumbau** [comment]
nope. removed.

**Comment by talumbau** [comment]
Merging.

**Pull request merged**
