### PR TITLE
Simple Reforms using SIMTAX

### PR DESCRIPTION
**Pull request by GoFroggyRun**
@martinholmer Does this PR meet all what we need for testing simple reforms as discussed in #457? Please take a look and let me know what else might be helpful. Thanks!

### CODE REVIEW

**Comment by martinholmer** [comment]
Sean (@GoFroggyRun),
These files look great, but there is one very minor issue you should probably fix having to do with end-of-line character missing at the end of a file.  GitHub is highlighting it, so I imagine that GitHub considers it non-standard.  It's an easy fix: just press the Enter key after the last character in each of the 8 .taxdiffs files and in each of the 4 .json files.

I'm also interested in knowing the size of the out-taxsim.zip file in bytes.

**Comment by GoFroggyRun** [comment]
@martinholmer Sure. New lines have been added to each files. 
The size of the `out-taxsim.zip` file is 30,523,965 bytes. (I have truncated all outputs expect `ovar 1` and `ovar 4`)

**Comment by martinholmer** [comment]
Sean @GoFroggyRun said:
> New lines have been added to each file. 

Thanks.  Now GitHub is happy :)

> The size of the out-taxsim.zip file is 30,523,965 bytes. (I have truncated all variables expect ovar 1 and ovar 4 for those newly-added TAXSIM outputs)

Do you mean you ran ```awk '{print $1,". .",$4}'``` on each file you added to out-taxsim.zip?  There need to be four space-delimited fields in each of those files for the taxdiffs program to work (but the second and third fields are never read, so they can be anything, like a dot, which signifies a missing value in many statistical packages like SAS).

Also, another question: what are the names of the 8 trimmed files you added to out-taxsim.zip?

**Comment by GoFroggyRun** [comment]
@martinholmer 
Yes. I ran `awk '{print $1, ". .", $4}` on each file so that each row of those files look like:
```1. . . 9457.50```.
I also executed `tclsh taxdiffs.tcl` after modifying these TAXSIM outputs, so hopefully I didn't get anything wrong. 

Regarding your second concern, the name of the file reads `c13.in.out-taxsim-reform-18_0.07`, as an example. Do you want me to take out the `reform` and use something like `c13.in.out-taxsim-18_0.07`?

**Comment by martinholmer** [comment]
Sean @GoFroggyRun said:
> Yes. I ran awk '{print $1, ". .", $4}' on each file so that each row of those files look like:
> 1. . . 9457.50.
> I also executed tclsh taxdiffs.tcl after modifying these TAXSIM outputs, so hopefully I didn't get anything wrong.

PERFECT!  Thanks.

> Regarding your second concern, the name of the file reads c13.in.out-taxsim-reform-18_0.07, as an example. Do you want me to take out the reform and use something like c13.in.out-taxsim-18_0.07?

Not a concern, just wanted to know the naming convention you used.  What you have done is perfect.  Thanks.

I'll merge this pull request, and then the ball is in my court.  I'll try to make the changes to the ```tests``` and ```test``` scripts to automate the procedure.

**Pull request merged**
