### PR TITLE
add reform file for TCJA_House_Amended

### PR DESCRIPTION
**Pull request by MattHJensen**
This reform file is for the TCJA House bill with amendments as of 11-9-17. 

The two amendments are described at: 

https://waysandmeansforms.house.gov/uploadedfiles/summary_of_chairman_amendment.pdf
https://waysandmeansforms.house.gov/uploadedfiles/summary_of_chairman_amendment_2.pdf

The only provision that I have identified for us to model is the following. 

> Section 1004 – Maximum rate on business income of individuals (reduced rate for small businesses with net active business income) The amendment provides a 9-percent tax rate, in lieu of the ordinary 12-percent tax rate, for the first $75,000 in net business taxable income of an active owner or shareholder earning less than $150,000 in taxable income through a pass-through business. As taxable income exceeds $150,000, the benefit of the 9-percent rate relative to the 12-percent rate is reduced, and it is fully phased out at $225,000. Businesses of all types are eligible for the preferential 9-percent rate, and such rate applies to all business income up to the $75,000 level. The 9-percent rate is phased in over five taxable years, such that the rate for 2018 and 2019 is 11 percent, the rate for 2020 and 2021 is 10 percent, and the rate for 2022 and thereafter is 9 percent. For unmarried individuals, the $75,000 and $150,000 amounts are $37,500 and $75,000, and for heads of household, those amounts are $56,250 and $112,500.

I made a fairly substantial simplification while modeling this provision. In this reform file, the benefit of the reduced 9% rate is clawed back from pass through income through the bubble rates. As the bill is written, it should also be clawed back from non-pass-through taxable income if non-pass-through taxable income exceeds pass-through income and there is insufficient pass-through income for a full clawback. 

@codykallen, could you please review? 

@martinholmer @GoFroggyRun @evtedeschi3

### CODE REVIEW

**Comment by codykallen** [comment]
@MattHJensen, why did the beginning of the 25% bracket change? Did the amendment change that? Can you explain how the bracket changed, ignoring how the 11/10/9 percent rates are implemented and phased out, and then how the brackets change based on these preferential brackets?

**Comment by MattHJensen** [comment]
> @MattHJensen, why did the beginning of the 25% bracket change? Did the amendment change that? Can you explain how the bracket changed, ignoring how the 11/10/9 percent rates are implemented and phased out, and then how the brackets change based on these preferential brackets?

Looks like I made a mistake. There should be some 25% beneath the bubble rate.

**Comment by MattHJensen** [comment]
@codykallen, I added back the 25% beneath the bubble rate in the latest commit.

**Comment by codykallen** [comment]
@MattHJensen, this looks fine to me.

**Comment by MattHJensen** [comment]
Thanks @codykallen. Merging.

**Pull request merged**
