### PR TITLE
Add policy parameters to impose surtax on high AGI

### PR DESCRIPTION
**Pull request by GoFroggyRun**
In order to measure the effects of one of Clinton's tax proposal that imposes a 4% surtax on filers with AGI over 5mm, two extra parameters are being added, namely `_AGI_surtax_thd` and `_AGI_surtax_rt`. The default value for the threshold is infinite (`9e99`) and the default value for the surtax rare is 0%. 

To impose such surtax in TC, one need to modify both parameters. If any, the surtax is imposed on income tax, which will thus affect succeeding calculations, including AMT.  

Comments, concerns or remarks would be appreciated. 
@martinholmer @MattHJensen @feenberg

### CODE REVIEW

**Comment by martinholmer** [comment]
@GoFroggyRun,  Your pull request #939 needs much more work.  I don't see how the AGI surtax has anything to do with GainsTax; put the logic of the AGI surtax in its own function and call it in between the SchXYZTax and the GainsTax functions.  Also, put the two new policy parameters in the `current_law_policy.json` file approximately in the order they are used in the `functions.py` file.  Also, change the name to comply with our parameter naming conventions: make the parameter name be `_AGI_surtax_trt`.  Also, `_AGI_surtax_trt` is **not** inflation indexed.  And also, you need to improve the wording of the "description" for each of the two new policy parameters.

@MattHJensen

**Comment by GoFroggyRun** [comment]
@martinholmer, thanks for you comments on this issue. I have made modifications to address your concerns. One minor diversion is that, instead of putting the function in between the SchXYZTax and the GainsTax functions, I put the new function in between the GainsTax and the NetInvIncTax functions.

**Comment by martinholmer** [comment]
Pull request #939 looks much better now, but shouldn't the AGI surtax amount be added to the `_surtax` variable?

@MattHJensen

**Comment by martinholmer** [comment]
@GoFroggyRun, I'm going to merge pull request #939 now and I will fix the `_surtax` issue after consultation with @MattHJensen.  Thanks for this useful addition to Tax-Calculator.

**Comment by martinholmer** [comment]
@GoFroggyRun,  Have you estimated the revenue effects of the high-AGI surtax?  It would be useful to compare our estimates with those of others, like @andersonfrailey did in pull request #904.  You could do this by adding another reform to the `taxcalc/comparison/reforms.json` file.

@MattHJensen @feenberg @Amy-Xu

**Comment by GoFroggyRun** [comment]
@martinholmer, yes, that's the plan. I'm currently in the middle of trying to target puf's high-AGI distribution against SOI statistics. I'll work on a reform estimate afterwards.

**Pull request merged**
