### PR TITLE
Break up DependentCredit

### PR DESCRIPTION
**Pull request by codykallen**
This splits the non-refundable dependent credit into two parts, one for children and one for non-child dependents. The original version was intended to implement the Brady-Ryan proposal from 2016, which increased the  CTC cap by $500 (with the new portion non-refundable) and created a $500 non-refundable credit for non-child dependents. 

The new GOP tax plan appears to expand the CTC by $600 and create a $300 non-refundable credit for non-child dependents. If the CTC expansion is non-refundable then it should be implemented with the _DependentCredit_Child_c variable. Otherwise, it should be done by changing the CTC cap.

### CODE REVIEW

**Comment by MattHJensen** [comment]
We should keep the existing unified `_DependentCredit_c` rather than replacing it for the sake of backwards compatibility.

**Comment by codykallen** [comment]
@MattHJensen said

> We should keep the existing unified _DependentCredit_c rather than replacing it for the sake of backwards compatibility. Add the two new parameters.

Fair enough. Modifying now.

**Comment by codykallen** [comment]
@hdoupe @andersonfrailey 

PR in progress now. 

This PR adds the capability to separately implement non-refundable expansions of the child tax credit and credits for non-child dependents.

**Comment by andersonfrailey** [comment]
@codykallen this looks good. My one concern is that a user may be a little confused when the see a dependent credit, a dependent credit for children, and a dependent credit for non-children. Do you think it would be helpful to a small clarification in the description of `_DependentCredit_c` that it is a credit for all dependents. It could read something like this:

>This nonrefundable credit is applied to all dependents (child and non-child) and phases out with the Child Tax Credit. The dependent credit's phaseout begins when the CTC's phaseout ends.

**Comment by codykallen** [comment]
@martinholmer @Amy-Xu 
Can we quickly review and merge this in? It's very relevant for those trying to model the plan coming out today.

**Comment by MattHJensen** [comment]
This lgtm. Merging.

**Pull request merged**
