### PR TITLE
Added paramter for CTC reform

### PR DESCRIPTION
**Pull request by Amy-Xu**
In this PR, parameter '_CTC_additional' is added for a partially refundable Child Tax Credit, on top of all the child/dependents credit available. This credit amount is limited by the sum of total income and payroll tax liabilities.

Here're the baseline table , and the diagnostic table with an additional credit of $2500 for each qualifying child.

Baseline:
master

$2500 credit for each qualifying child:
screen shot 2015-11-11 at 3 29 30 pm

@MattHJensen Could you review?

### CODE REVIEW

**Comment by Amy-Xu** [comment]
Just added the credit to refundable credits row as we did for the existing Additional Child Tax Credit. Here are the updated tables, both Refundable credits and Individual Income tax changed starting from 2015.

Baseline:
screen shot 2015-11-12 at 3 34 28 pm

Reform ($2500 credit for each qualifying child):
screen shot 2015-11-12 at 3 34 40 pm

**Comment by Amy-Xu** [comment]
Just realized the previous baseline was actually different from master because I forgot to eliminate the negatives from the sum of total income and payroll tax liabilities. Add the limit and here're the updated tables:

Baseline:
screen shot 2015-11-12 at 5 49 17 pm

Reform:
screen shot 2015-11-12 at 5 49 26 pm

**Comment by MattHJensen** [comment]
@amy-xu, should only the portion of the credit that takes _iitax liabilities below zero in the refundable credits row and the rest in the nonrefundable credits row (and relevant variables in functions.py)? Are other refundable credits decomposed in some way?

**Comment by Amy-Xu** [comment]
@MattHJensen Maybe I misread the code, but if you take a a look at `c11070`, which is additional child tax credit, it was just added to refundable credits. I didn't see any decomposition for this variable. Did I miss anything?

**Comment by MattHJensen** [comment]
@Amy-Xu, this looks good to me now, but merging #459 created some conflicts.

**Comment by Amy-Xu** [comment]
@MattHJensen just merged with master.

**Comment by MattHJensen** [comment]
Great. Merging.

**Pull request merged**
