### PR TITLE
Revise validation test scripts to handle new reform tests

### PR DESCRIPTION
**Pull request by martinholmer**
Previously the six validation tests all used current-law policy in combination with six different samples of tax filing units.  After Sean Wang's development of eight reform tests, which was merged into the master branch from pull request #460, this pull request revises the test and the tests bash scripts that automate the execution of either a short validation test or a more complete validation test.  The short test consists of two tests: the c13.in sample under current-law policy and the c14.in sample under current-law policy.  The more complete test adds 12 more tests: four different input samples under current-law policy and four different policy reforms with the c13.in sample and the same four policy reforms with the c14.in sample.

Parallel execution of the tests means that the short test executes in roughly two minutes and the more complete test (which involves computing tax liabilities and marginal tax rates for 1.4 million filing units) executes in roughly nine minutes.

### CODE REVIEW

**Comment by martinholmer** [comment]
@MattHJensen, @Amy-Xu, and Sean (@GoFroggyRun) Wang,
Questions, comments, or suggestions are welcome.

**Comment by GoFroggyRun** [comment]
@martinholmer Thanks for revising the `json` files! These changes look good to me.

**Comment by martinholmer** [comment]
@MattHJensen and @Amy-Xu,  Do you see any problems with the changes in pull request #461?  If not, do you want to merge these changes into the master branch?  Or, do you want me to do the merge?

**Comment by MattHJensen** [comment]
These changes look good to me. @martinholmer, do you think this calls for a new step to be added to `docs/source/contributor_guide.rst`? 

@Amy-Xu, if everything looks good to you, could you merge?

**Comment by MattHJensen** [comment]
@martinholmer, I am merging this now as I think it is extremely valuable to safeguard against degrading the tax logic over time. That said, I expect Amy, T.J., me, or other contributors might have some more feedback once we start to incorporate these tests into our development workflow.

**Comment by martinholmer** [comment]
@MattHJensen said:
> do you think this calls for a new step to be added to docs/source/contributor_guide.rst?

I've already added something to item(11) of the Setup Git section, but you are probably suggesting a similar addition to the Workflow section at item(4).  Right?  If I understand your suggestion, I think it is excellent.  I'll take care of that.

**Comment by MattHJensen** [comment]
> but you are probably suggesting a similar addition to the Workflow section at item(4). Right? If I understand your suggestion, I think it is excellent. I'll take care of that.

Yes, that is what I meant. Thanks!

**Pull request merged**
