### PR TITLE
Prepare zrisher PR #1179 for merging into master branch

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request resolves a few conflicts with the master branch that have arisen over the course of the two months since #1179 was submitted by @zrisher.  Many thanks, @zrisher, for the very useful idea and all your implementation work.  See the conversation at #1179 for more details on the rationale for these changes.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen

### CODE REVIEW

**Comment by martinholmer** [comment]
Note that the issues raised by @zrisher in #1179 on Feb 20th will be resolved after #1285 is merged.

**Comment by martinholmer** [comment]
Note that the codecov problem with #1185 is inescapable given that we have not figured out how to test the reading of .csv and .json data from a Python egg.  The basic idea of #1179 is to put Records class variable metadata into a separate JSON file.  And this file will be read from the egg when the Records class is used in a conda package.

**Comment by MattHJensen** [comment]
+1 here. Thanks @martinholmer and @zrisher. Merging now so that we can have these changes in 0.8.1, which I am releasing today.

**Comment by MattHJensen** [comment]
@zrisher, by merging now I don't mean that you shouldn't feel free to look over @martinholmer's additions and suggest any follow ons in a separate PR.

**Pull request merged**
