### PR TITLE
Add scripts for easy comparison

### PR DESCRIPTION
**Pull request by Amy-Xu**
This script generates results for simple reforms and compares OSPC number with Tax Expenditure or Budget Options if any. Currently it covers every parameter available on Tax Brain except growth related ones. 

Adding this script to master would allow developers update the comparison file easily every time they modify master, and see how much the modifications changed major reforms. 

I can see one improvement on current version is to make this a command style, with user input JSON reforms and customized output file names. But not sure whether it's a priority or not at this moment.

Would appreciate any feedback on this PR.

@MattHJensen @martinholmer

### CODE REVIEW

**Comment by martinholmer** [comment]
Amy said:
>  Would appreciate any feedback on this PR #546.

Amy, this looks like an impressive piece of work.  I've haven't done anything to check the logic or the quantitative results, but presumably that will get done over time using the framework you've set up.

What I have done is try to use the script the way you intend it to be used by the core development team.  I had some problems that I'll describe below.  Here is what I did.

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	puf.csv
nothing added to commit but untracked files present (use "git add" to track)
$ git fetch upstream pull/546/head:pr-546
From https://github.com/opensourcepolicycenter/tax-calculator
 * [new ref]         refs/pull/546/head -> pr-546
$ git checkout pr-546
Switched to branch 'pr-546'
$ git status
On branch pr-546
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	puf.csv
nothing added to commit but untracked files present (use "git add" to track)
$ python Generate_comparison_results.py 
Traceback (most recent call last):
  File "Generate_comparison_results.py", line 14, in <module>
    import simplejson
ImportError: No module named simplejson
```

I have the full Anaconda distribution required for Tax-Calculator, but I don't have simplejson.  When I looked on the web, people said it had same capability as the Python standard library json module (but that years ago it was somewhat faster).  So, I changed the imported module from simplejson to json.  Then after another crash, I found you have your personal computer's path to the puf.csv file hard coded into the script.  I edited the name to be simply "puf.csv", which is where we are assuming core developers are going to have the puf.csv file (even though it is not under version control).  I also added in the top-of-the-file docstring the language you suggested to me several weeks ago about what the puf.csv file is and how to get it.  Then I tried again to execute the edited script.  Here's what happened:

```
$ python Generate_comparison_results.py 
You loaded data for 2009.
Your data have been extrapolated to 2013.
You loaded data for 2009.
Your data have been extrapolated to 2013.
$ git diff comparison_results.csv 
diff --git a/comparison_results.csv b/comparison_results.csv
index f33b970..59ec9ee 100644
--- a/comparison_results.csv
+++ b/comparison_results.csv
@@ -118,10 +118,10 @@ CAPITAL GAIN
 OSPC,16.6,17.0,17.6,18.3
 ""
 "Increase long term cap gain and dividends tax rates by 2 percentage, elasticity assumed to be 0.78"
-OSPC,16.6,17.0,17.6,18.3
+OSPC,12.8,9.1,5.4,1.4^M
 ""
 "Increase long term cap gain and dividends tax rates by 2 percentage, elasticity assumed to be 1.2"
-OSPC,16.6,17.0,17.6,18.3
+OSPC,10.7,5.0,-1.0,-7.7^M
 Budget Options,4.6,5,5.3,5.6
 ""
 REGULAR TAXES
@@ -207,11 +207,3 @@ Tax Expenditure,-32.6,-34.7,-36.6,-38.9
 ""
 "Increase Net Investment Income Tax threshold by 10,000"
 OSPC,-0.4,-0.4,-0.4,-0.4
-""
-PERSONAL REFUNDABLE CREDIT
-""
-Increase Personal Refudable credit amount to 1000
-OSPC,-151.4,-156.6,-161.8,-166.5
-""
-"Increase Personal Refudable credit amount to 1000, with phaseout starting AGI 10,000 and phaseout rate at 0.01"
-OSPC,-151.4,-127.3,-131.0,-134.0
$ tail comparison_results.csv 
OSPC,0.0,0.0,0.0,0.0
""
OTHER TAXES
""
"Net investment income tax, total"
OSPC,-33.1,-34.1,-35.7,-37.4
Tax Expenditure,-32.6,-34.7,-36.6,-38.9
""
"Increase Net Investment Income Tax threshold by 10,000"
OSPC,-0.4,-0.4,-0.4,-0.4
$ 
```

So, the comparison_results.csv file I generate on my compute is not the same as what is in your pull request #546.  There seem to be differences when you assume behavior responses to capital gains tax rate changes, and there seem to be reforms that are in the file I generated, but not in the file in your pull request (or is the other way around?; the git diff utility is brain damaged as far as I'm concerned).  My guess is that you have a magic number problem in your script.  Instead of using hard-coded numbers in loop ranges, use the number of reforms [aren't they in a dictionary where you count them using len()?].

And, by the way, why do you call the comparison_results file a CSV file?  It doesn't look like one to me?  But maybe I'm not completely up to speed on the mysteries of CSV file format.  Could just use a .txt extension to indicate it is a simple text file.

After you fix these problems and update the pull request, I will suggest some other things.  But our first priority is to get the script so it will work on the local computers of every core developer (that is, everybody with a legal copy of the puf.csv file).  As you make these changes, can you rename the script to replace the capital G with a lower-case g?  It is common Python practice to use lower-case letters and underscores in module names, and the Tax-Calculator project has been following this convention as far as I can see.

cc @Amy-Xu @MattHJensen @GoFroggyRun

**Comment by Amy-Xu** [comment]
@martinholmer Thank you very much for all these suggestions. Let me address the easy ones first.

- My bad with the hard coded data path. Will change it in a sec.
- I didn't realize until you ran into this error that I probably installed simplejson a while ago using pip instead of anaconda. The reason why I keep using this package instead of json is that simplejson gives a much more specific error message on json format problems, which is very convenient for debugging stuff. I'll switch to json, but I would also add comments about simplejson.

- I ran my script yesterday again and somehow get different results on behavior as well. No clue why this happened at this point. Will get back to you as soon as I figure anything out.

- Regarding CSV output format, it is the first thing I found to export a dictionary. I'll try to see how to export it to a txt file.

**Comment by MattHJensen** [comment]
I can see a case that we should add this script to the requires_pufcsv tests and update the output every time a developer opens a PR. @martinholmer, @Amy-Xu, @talumbau, what do you think? 

The downside is that these are very slow tests to run. After we resolve #528, we might say its ok for core developers to rely on travisCI to run the tests after they open a PR when the developer expects the tests to pass.  

The upside is that many of our policy users are interested in knowing how we stack up against JCT, and we would be able to catch changes to our behavior functions. We could link to `pufcsv_agg_expect.txt`, `pufcsv_mtr_expect.txt` and some now `pufcsv_reform_expect.txt` from the readme and from TaxBrain.

**Comment by martinholmer** [comment]
Amy, the new generate_comparison_results.py has at least two sets of problems:

First, it doesn't work:
```
$ ../pr 546
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 22 (delta 6), reused 5 (delta 5), pack-reused 12
Unpacking objects: 100% (22/22), done.
From https://github.com/opensourcepolicycenter/tax-calculator
 * [new ref]         refs/pull/546/head -> pr-546
Switched to branch 'pr-546'
On branch pr-546
$ python generate_comparison_results.py 
Traceback (most recent call last):
  File "generate_comparison_results.py", line 24, in <module>
    reforms_json = simplejson.load(json_file)
NameError: name 'simplejson' is not defined
$ 
```

And second, its coding style is so inconsistent with widespread Python best practices that pylint gives ```generate_comparison_results.py``` an overall rating of -8.00 out of 10.  Here is the summary of the warnings and errors (notice it finds the coding mistake that causes the crash I reported above):
```
+-----------------------+------------+
|message id             |occurrences |
+=======================+============+
|unused-wildcard-import |103         |
+-----------------------+------------+
|invalid-name           |12          |
+-----------------------+------------+
|trailing-whitespace    |2           |
+-----------------------+------------+
|wildcard-import        |1           |
+-----------------------+------------+
|unused-import          |1           |
+-----------------------+------------+
|undefined-variable     |1           |
+-----------------------+------------+
|missing-docstring      |1           |
+-----------------------+------------+
|bad-whitespace         |1           |
+-----------------------+------------+
```

I stongly suggest you install ```pylint``` and use it.
```
conda install pylint
pylint --disable=locally-disabled --extension-pkg-whitelist=numpy generate_comparison_results.py 
```
I'll be happy to answer any questions you may have about how to change the code to make it more consistent with Python conventions.  My experience with this file is that just a few changes will increase the overall rating by a large amount moving it much closer to the goal of 10.0 out of 10.  For example, eliminating the wildcard import from taxcalc does wonders and is easy to do.  Just replace
```
from taxcalc import *
```
with the following
```
from taxcalc import Policy, Records, Calculator, behavior
```
This change alone increases the codes overall rating to +6.57 out of 10.

**Comment by martinholmer** [comment]
Matt said:
> I can see a case that we should add this script to the requires_pufcsv tests and update the output every time a developer opens a PR. @martinholmer, @Amy-Xu, @talumbau, what do you think?

See my thoughts below.

> The downside is that these are very slow tests to run. After we resolve #528, we might say its ok for core developers to rely on travisCI to run the tests after they open a PR when the developer expects the tests to pass.

This is an enormous negative.  TravisCI already takes forever (30 to 45 minutes in the middle of the day) to run all three sets (2.7, 3.4, and newly 3.5) of pytests.  If this were to be added to pytests, I would expect the TravisCI run times to be unacceptably long (because the generate_comparison_results.py test would be run three times (once under Python 2.7, once under Python 3.4, and once under Python 3.5).

> The upside is that many of our policy users are interested in knowing how we stack up against JCT, and we would be able to catch changes to our behavior functions. We could link to pufcsv_agg_expect.txt, pufcsv_mtr_expect.txt and some now pufcsv_reform_expect.txt from the readme and from TaxBrain.

You could move ```generate_comparison_results.py``` to the taxcalc/tests directory as ```generate_reform_results.py``` and put it and its results file under version control.  Then the core development team can update the results periodically without having to endure excessively long TravisCI run times.  The results file could also be referenced in the TESTING.md or README.md (or both) files.

cc @MattHJensen @feenberg @Amy-Xu @GoFroggyRun @talumbau

**Comment by Amy-Xu** [comment]
> I can see a case that we should add this script to the requires_pufcsv tests and update the output every time a developer opens a PR. 

I can definitely see the upside of updating users with the latest comparison, but it would be too time-consuming to run it on TravisCI, and I don't see there's an easy to cut the time significantly. We can get the upside by asking each developer running the script locally on their machines. Plus, kind of feel it should probably be sufficient to check baseline on TravisCI. 

I'm not quite sure whether this should be incorporated as a part of the test suite. Because in my mind, this script is more about **updating** instead of testing. It makes more sense to me keeping the py.test a pure testing suite from a programmers perspective, and separate the updating from those tests. A lot of times, updating the numbers lies more on the economic side, whether they are sensible changes or not. It would be confusing for new developers (core as well) to see the testing failures when there's actually no bug in the code.

**Comment by Amy-Xu** [comment]
@martinholmer I just installed pylint and updated the script. Other than naming convention, I should have cleaned up all other formatting problems. Also have fixed the simplejson bug as well.

My main concern from last update was, somehow when I run the exporting part twice, the two resulting CSV files were different, which is more than puzzling. I'm digging into this right now. Will keep you posted.

**Comment by Amy-Xu** [comment]
@martinholmer The weird behavior doesn't show up anymore when I made absolutely no change to the script. Have no clue why it didn't work in the first place and no idea how it was fixed either.

Could you try running it again on your end? Much appreciated.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> Could you try running it again on your end? Much appreciated.

Yes, but I need to run an errand right now, so will not be able to do this until later this afternoon.

**Comment by martinholmer** [comment]
@Amy-Xu,
I had a chance to download the latest version of pull request #546.
The tests are running now, but not finished.  I'll let you know if I get the same results on my computer.

The coding-style rating of 8.24 out of 10 is **much** better.

My only remaining quibbles are the name of the script and its results file.  The name doesn't say anything about what kind of comparisons are being generated.  Perhaps something like:
```reform_results.py``` for the script and ```reform_results.txt``` for its results would stress the focus on policy reforms.  The ```generate_``` prefix seems redundant to me because all of our Python scripts are generating some kind of results.   And, finally, I still don't understand why your script is writing the results to a text file that has an ```.csv``` extension when it is clearly not a CSV file.  This is very confusing.  As above, I suggest you name the results file ```reform_results.txt```.

With those minor changes, I would support the idea of moving the script and its results file to the ```taxcalc/tests``` directory (which means you would have to slightly alter the path to the ```puf.csv``` file).

**Comment by martinholmer** [comment]
@Amy-Xu,  the script finished and all the results are the same as in the pull request.

**Comment by Amy-Xu** [comment]
@martinholmer Thank you very much.

Changing the file names would be easy. But exporting the files to txt extension is not as simple as I imagined, purely switching the extension to txt won't work. Instead, google's telling me I need to import anther `pickle` package, and re-write the for loop. If that's not the case, could you give me suggestions how to switch the extensions? Thanks!

**Comment by martinholmer** [comment]
@Amy-Xu said:
> Changing the file names would be easy. But exporting the files to txt extension is not as simple as I imagined, purely switching the extension to txt won't work. Instead, google's telling me I need to import anther pickle package, and re-write the for loop. If that's not the case, could you give me suggestions how to switch the extensions? Thanks!

OK, I'll be happy to review and see if I can suggest an easier way.  Probably will not be able to find time for this task until later this evening or tomorrow morning.

**Comment by martinholmer** [comment]
@Amy-Xu,
It seems like importing the csv module is the thing to do when you are writing a genuine CSV-formatted file.  But in your case, it is more trouble than help.  You can drop the ```import csv``` statement and just use the core-Python file open/write/close methods to write out a text file.  Below is how I revised the end of the script (the part that writes results).  The code below writes the results to a file named ```reform_results.txt```, which seems to contain the same output as your script except for some invisible difference in the end-of-line character(s).  Feel free to ask me any questions about this code.

```
# write all results to a text file
ofile = open('reform_results.txt', 'w')
for i in range(1, num_reforms + 1):
    reform = reforms_json['r' + str(i)]
    ofile.write('""\n')

    if "section_name" in reform:
        ofile.write('{}\n'.format(reform["section_name"]))
        ofile.write('""\n')

    reform_name = reform["name"]
    ofile.write('{}\n'.format(reform_name))

    value = results[reform_name]
    ofile.write('OSPC')
    ofile.write(',{:.1f},{:.1f},{:.1f},{:.1f}\n'.format(value[0], value[1],
                                                        value[2], value[3]))

    if "Tax Expenditure" in reform["compare_with"]:
        comp = reform["compare_with"]["Tax Expenditure"]
        ofile.write('Tax Expenditure')
        ofile.write(',{:.0f},{:.0f},{:.0f},{:.0f}\n'.format(comp[0], comp[1],
                                                            comp[2], comp[3]))

    if "Budget Options" in reform["compare_with"]:
        comp = reform["compare_with"]["Budget Options"]
        ofile.write('Budget Options')
        ofile.write(',{:.0f},{:.0f},{:.0f},{:.0f}\n'.format(comp[0], comp[1],
                                                            comp[2], comp[3]))
ofile.close()
```

**Comment by martinholmer** [comment]
@Amy-Xu,
Sorry I forgot to mention this issue before, but a while back Matt insisted (quite reasonably) that all references to OSPC in the source code be replaced with Tax-Calculator, in order to give the model a more independent status appropriate for an open-source project.  We do not want to reintroduce something we spent time getting rid of earlier.  So, look over the ```reform_results.py``` script and remove all references to OSPC.  In particular, in the write section replace OSPC with Tax-Calculator.   Thanks.

cc @MattHJensen

**Comment by Amy-Xu** [comment]
@martinholmer Thank you very much for the snippet! That comes really handy. I changed this part of script, rename both the script and the output file names, and moved them to the taxcalc/tests folder.

But as I mentioned in my previous comment, I reserve my opinion that I don't think taxcalc/tests is the most proper place for this kind of scripts and files, because they look more like updates than tests to me.
@MattHJensen @talumbau

**Comment by martinholmer** [comment]
Amy said:
> @martinholmer Thank you very much for the snippet! That comes in really handy. I changed this part of script, renamed both the script and the output file names, and moved them to the taxcalc/tests folder.
>
> But as I mentioned in my previous comment, I reserve my opinion that I don't think taxcalc/tests is the most proper place for this kind of scripts and files, because they look more like updates than tests to me.

Well, I can see what you're saying, but these files could be construed as a reform comparison test versus two establish sources of tax information.  Just because they are not part of the pytest suite of tests doesn't mean they are not "tests" in some sense of the word.  Do you think these three files (by the way, the reforms.json file seems to gotten lost in your latest version of the pull request) should be put in their own directory?  Perhaps ```taxcalc/comparison```?  I'd be OK with that approach.  What do you think?

@Amy-Xu @MattHJensen @feenberg @GoFroggyRun @talumbau

**Comment by Amy-Xu** [comment]
@martinholmer That sounds more reasonable to me! I got tied up with another issue (still trapped now), and will come back to this asap.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> @martinholmer That sounds more reasonable to me! I got tied up with another issue (still trapped now), and will come back to this asap.

Fine, no rush.  Maybe you've done this already but it seems to me that we would want to keep all three of the reform files (INPUT: .json; SCRIPT: .py; OUTPUT: .txt) together in the same directory.  Does that make sense to you?

**Comment by Amy-Xu** [comment]
@martinholmer I made a new folder `comparison` in taxcalc and moved all three files to that folder. Could you take a look? This PR is ready to be merged if it looks good to you.

**Comment by martinholmer** [comment]
@Amy-Xu,
I like the location of all three files in the taxcalc/comparison directory.  But the script crashed for at least two different reasons: couldn't find taxcalc package and couldn't find puf.csv file.  Also, we can remove the unused import of the csv package.  Here is what I did after putting puf.csv file in the top-level directory to get the crashes:
```
cd taxcalc/comparison
python reform_results.py
```
Here is a slightly revised top of your script that fixes all three problems.
```
"""
This script generates policy experiment results,
and compare them with JCT Tax Expenditure or Budget Options if available.

It uses reforms stored in 'reforms.json',
and export and save all results and comparisons in a txt file

puf.csv needs to be in the top level of Tax-calculator.
Otherwise replace the file name with full path

USAGE: python reform_results.py
"""

import json
import copy
import pandas as pd
import os
import sys
CUR_PATH = os.path.abspath(os.path.dirname(__file__))
sys.path.append(os.path.join(CUR_PATH, "..", ".."))
from taxcalc import Policy, Records, Calculator, behavior
PUF_PATH = os.path.join(CUR_PATH, "..", "..", "puf.csv")


# import all reforms from this JSON file
with open("reforms.json") as json_file:
    reforms_json = json.load(json_file)
num_reforms = len(reforms_json)

# create two calculators, one for baseline and the other for reforms
tax_dta1 = pd.read_csv(PUF_PATH)
records1 = Records(tax_dta1)
policy1 = Policy(start_year=2013)
calc1 = Calculator(records=records1, policy=policy1)

tax_dta2 = pd.read_csv(PUF_PATH)
records2 = Records(tax_dta2)
policy2 = Policy(start_year=2013)
calc2 = Calculator(records=records2, policy=policy2)
```
After using the above code, the script ran just fine, but did not produce the same results as in your reform_results.txt file.  Have you run this script using the most recent version of the Tax-Calculator?

Why don't you copy and paste the code above into the script and see if it runs on your computer.  Also, be sure to merge recent changes on the master branch into this branch.  If the script runs OK with the most recent master changes, check that the new estimates in the reform_results.txt file look correct (given the newest version of the Tax-Calculator logic).  If script runs without crashing and if the new results seem sensible, then commit both the code and results changes.  After than I'll be happy to merge this pull request into the master branch.

**Comment by Amy-Xu** [comment]
@martinholmer Thank you very much for the advices. Just updated the script and results accordingly.

**Comment by martinholmer** [comment]
@Amy-Xu, looks good! Thanks for the contribution.  Merging into master branch.

**Pull request merged**
