### PR TITLE
Update Tax-Calculator testing/build environments

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request does the following things:
1. Updates minimum required version of pandas from 0.18.0 (released on 13-Mar-2016) to 0.20.1 (released on 05-May-2017).  Notice that this higher minimum version is required only for the tests, not for the execution of Tax-Calculator.  But this pull request changes both `environment.yml` and `conda.recipe/meta.ymal` in order to get the taxcalc package execution speed-up provided by the newest version of pandas.
2. Raises the minimum required version of numpy from 1.11.2 to 1.12.1 in order to ensure we get he taxcalc package execution speed-up.
3. Removes several requirements because they are required by pandas and will be automatically upgraded whenever pandas is upgraded.
4. Revises the Contributor Guide instructions about what to do when tests fail so as to eliminate unnecessary step per the conversation of issue #1350.
5. Drops testing in Python 3.4 environments and adds testing in Python 3.6 environments on Linux and Windows.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen @zrisher 
@PeterDSteinberg @brittainhard

### CODE REVIEW

**Comment by martinholmer** [comment]
I see the check-in tests failed on Linux under Python 3.4 because pandas 0.20.1 is not (yet or ever?) available for Python 3.4.  Here is the message generated by Travis-CI:
```
$ python --version
Python 3.4.2
[... SNIP...]
$ conda env update -f environment.yml
Fetching package metadata .........
Solving package specifications: .
UnsatisfiableError: The following specifications were found to be in conflict:
  - pandas >=0.20.1 -> python 3.5*
  - python 3.4*
Use "conda info <package>" to see the dependencies for each package.
The command "conda env update -f environment.yml" failed and exited with 1 during .
Your build has been stopped.
```
The pandas documentation says they support Python 3.4, so I don't understand this result.
Perhaps Continuum Analytics has not yet created a conda package for pandas 0.20.1 under Python 3.4 or maybe they have no plans to create such a package because Python 3.4 is fairly out-of-date with Python 3.6 is being offered on the Anaconda download page.
```
Python version release dates
-------------------------------
Python 3.4 - March 16, 2014
Python 3.5 - September 13, 2015
Python 3.6 - December 23, 2016
```

Does anybody from Continuum Analytics know what's going on here?

@MattHJensen @PeterDSteinberg @brittainhard

**Comment by martinholmer** [comment]
Pull request #1361 updates the GitHub check-in **test** environments for Tax-Calculator.  We are now testing under Python 2.7, 3.5, and 3.6 on Linux and under Python 3.6 under Windows.  All the tests pass in each of those four environments.

What is left to do is to change the **build** process so that we generate taxcalc packages for each of the three operating systems for Python 2.5, 3.5, and 3.6.  I see two bash shell scripts in the tax-calculator/distribution directory that seem to do that, but I have my doubts and there is no documentation (no README.md file, for example).  Here is why I have doubts these scripts are being used: the scripts do a `conda convert` command on the `taxcalc-$1-np110py27_0.tar.bz` file, but we haven't been using numpy 1.10 for some time.  All the taxcalc 0.8.3 packages available for download are described as `np111pyXX_0`.

What process controls the build of the nine taxcalc packages?

And if the two bash scripts in the tax-calculator/distribution directory are no longer used, can they be removed?

@MattHJensen @PeterDSteinberg @GoFroggyRun

**Comment by PeterDSteinberg** [comment]
The ./distribution folder can now be removed, @martinholmer  - that old code is causing confusion here.  We have not used that for ~4 months.  Now we use:

https://github.com/open-source-economics/policybrain-builder

And the Jenkins job around that runs the bash script in that repo.

**Comment by martinholmer** [comment]
@PeterDSteinberg said in pull request #1361:
> The ./distribution folder can now be removed, @martinholmer - that old code is causing confusion here. We have not used that for ~4 months. Now we use:
>
> https://github.com/open-source-economics/policybrain-builder
>
> And the Jenkins job around that runs the bash script in that repo.

Thanks for the quick response!  I'll add the delete of these obsolete scripts to #1361.

**Comment by martinholmer** [comment]
The discussion at [policybrain-builder issue 31](https://github.com/open-source-economics/policybrain-builder/issues/31) has concluded that the best way forward is to stop all conda package builds for Python 3.4.  Tax-Calculator pull request #1361 is consistent with that decision.

@MattHJensen @PeterDSteinberg

**Pull request merged**
