### PR TITLE
Child Care Expense

### PR DESCRIPTION
**Pull request by GoFroggyRun**
Per discussion in #675 regarding issues with Child Care Expense, this PR resolves the inconsistency against presumed output from Internet TAXSIM. 
More precisely, when `e32750` is set to zero and `e32800` remains the same, the outputs for simple tax payers in c13, c14 and c15 remain unchanged: 
( with setting `recs.e32800[idx] = ivar[17]     recs.e32750[idx] = 0` )
```
ITs-MacBook-Air:validation Sean.Wang$ ./tests
STARTING WITH VALIDATION TESTS : Mon Apr  4 16:48:35 EDT 2016
. c14
. c13
. c15
FINISHED WITH VALIDATION TESTS : Mon Apr  4 16:51:47 EDT 2016
============ ALL EXECUTED VALIDATION/TESTS PASS
```

I'm, however, somewhat surprised by the changes from the puf output. The only part got changed in `functions.py` is 
```
        c32800 = min(max(0., _dclim - c32840),
                     max(0., e32750 + e32775 - c32840, c32800 - c32840))
```

I'm also not quite sure whether we should keep 'e32750' and 'e32775' since they are not in 09 puf at all. And, moreover, as @feenberg mentioned in #675, 
>We should not be using E32750 or E32775 at all. We should use E32700 for
child care expenses.

Although I'm not quite sure what's `e32700` (maybe he meant `e32800`), I thought it might be a good idea to remove 'e32750' and 'e32775' in `functions.py` and anywhere else in tax-calculator. 

@martinholmer @MattHJensen @Amy-Xu @feenberg 
Any comments, concerns or remarks would be appreciated.

### CODE REVIEW

**Comment by feenberg** [comment]
On Mon, 4 Apr 2016, Sean.Wang wrote:

> 
> Per discussion in #675 regarding issues with Child Care Expense, this PR resolves the
> inconsistency against presumed output from Internet TAXSIM.
> More precisely, when e32750 is set to zero and e32800 remains the same, the outputs
> for simple tax payers in c13, c14 and c15 remain unchanged:
> ( with setting recs.e32800[idx] = ivar[17] recs.e32750[idx] = 0 )
> 
> ITs-MacBook-Air:validation Sean.Wang$ ./tests
> STARTING WITH VALIDATION TESTS : Mon Apr  4 16:48:35 EDT 2016
> . c14
> . c13
> . c15
> FINISHED WITH VALIDATION TESTS : Mon Apr  4 16:51:47 EDT 2016
> ============ ALL EXECUTED VALIDATION/TESTS PASS
> 
> I'm, however, somewhat surprised by the changes from the puf output. The only part got
> changed in functions.py is
>
>         c32800 = min(max(0., _dclim - c32840),
>                      max(0., e32750 + e32775 - c32840, c32800 - c32840))
> 
> I'm also not quite sure whether we should keep 'e32750' and 'e32775' since they are
> not in 09 puf at all. And, moreover, as @feenberg mentioned in #675,
>
>       We should not be using E32750 or E32775 at all. We should use E32700 for
>       child care expenses.
> 
> Although I'm not quite sure what's e32700 (maybe he meant e32800), I thought it might
> be a good idea to remove 'e32750' and 'e32775' in functions.py and anywhere else in
> tax-calculator.

E32700 is "all child care expenses"

E32800 is "child care expenses not paid by employer and limited by the 
$3,000 or $6,000 limitation"

dan

**Comment by martinholmer** [comment]
Sean,  Thanks for pull request #677.  I can confirm that the one-line change you made fixes the Internet-TAXSIM validation question.  Now the SimpleTaxIO class needs to set only e32800 equal to the child-dependent-care expenses.  But I have two questions about your pull request.

First, can you explain in words what is happening in the logic after the one-line code change, and how that differs from the logic on the master branch?

Second, you said:
> it might be a good idea to remove 'e32750' and 'e32775' in functions.py and anywhere else

That sounds reasonable to me.  Why don't you add those changes to this pull request?  It seems as if removing those two variables might simplify the code.

@GoFroggyRun @feenberg @MattHJensen @Amy-Xu

**Comment by martinholmer** [comment]
Dan said:
> E32700 is "all child care expenses"
>
> E32800 is "child care expenses not paid by employer and limited by the $3,000 or $6,000 limitation" 

OK.  It does seem as if it would be ideal to have E32700 (rather than E32800) as the input variable into any tax simulation model, but E32700 is not a variable in the 2009 IRS-SOI PUF.   So, how do we get the uncapped expense from the capped expense?

@feenberg @MattHJensen @Amy-Xu @GoFroggyRun

**Comment by GoFroggyRun** [comment]
@martinholmer:

Sure. So that line is actually dealing with [form 2441](https://www.irs.gov/pub/irs-pdf/f2441.pdf), line 30 to be specific. Line 30 says that:
```
Complete line 2 on the front of this form. Do not include in column (c) any benefits shown
on line 28 above. Then, add the amounts in column (c) and enter the total here
```
where line 3 is 
```
Add the amounts in column (c) of line 2. Do not enter more than $3,000 for one qualifying
person or $6,000 for two or more persons. If you completed Part III, enter the amount
from line 31
```
Notice that `c32800` is just the sum of column (c) of line 2, Qualifying Individuals' Expenses. This yields the change.

**Comment by feenberg** [comment]
On Mon, 4 Apr 2016, Sean.Wang wrote:

> 
> @martinholmer:
> 
> Sure. So that line is actually dealing with form 2441, line 30 to be specific. Line 30
> says that:
> 
> Complete line 2 on the front of this form. Do not include in column (c) any benefits s
> hown
> on line 28 above. Then, add the amounts in column (c) and enter the total here
> 
> where line 3 is
> 
> Add the amounts in column (c) of line 2. Do not enter more than $3,000 for one qualify
> ing
> person or $6,000 for two or more persons. If you completed Part III, enter the amount
> from line 31
> 
> Notice that c32800 is just the sum of column (c) of line 2, Qualifying Individuals'
> Expenses. This yields the change.

That works if part III is not completed, but it often is.

dan

**Comment by martinholmer** [comment]
@GoFroggyRun,  Thanks for this bug fix.

**Pull request merged**
