### PR TITLE
[DO NOT MERGE] update for Python 3.6

### PR DESCRIPTION
**Pull request by MattHJensen**
As far as I can tell, the only change in this PR was to update from python 2.7 to python 3.6, which I needed to do to handle some bugs in my WIP PR #1614. Yet that Python update appears to have influenced tax-calculator results. Has anyone else run the `requires_pufcsv` tests on master on a machine running Python 3.6?

cc @martinholmer @hdoupe @GoFroggyRun @andersonfrailey 

Here is my conda env:

```
# packages in environment at /Users/Matt.Jensen/anaconda3/envs/taxcalc-dev:
#
astroid                   1.5.3            py36h1333018_0  
bokeh                     0.12.10          py36hfd5be35_0  
ca-certificates           2017.08.26           ha1e5d58_0  
certifi                   2017.7.27.1      py36hd973bb6_0  
coverage                  4.4.1                    py36_0  
execnet                   1.3.0                    py36_1  
intel-openmp              2018.0.0             h68bdfb3_7  
isort                     4.2.15           py36hceb2a01_0  
jinja2                    2.9.6            py36hde4beb4_1  
lazy-object-proxy         1.3.1            py36h2fbbe47_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
llvmlite                  0.20.0                   py36_0  
markupsafe                1.0              py36h3a1e703_1  
mccabe                    0.6.1            py36hdaeb55d_0  
mkl                       2018.0.0             h5ef208c_6  
mock                      2.0.0            py36hd48142b_0  
ncurses                   6.0                  hd04f020_2  
numba                     0.35.0              np113py36_6  
numpy                     1.13.3           py36h2cdce51_0  
openssl                   1.0.2m               h86d3e6a_1  
pandas                    0.21.0           py36hfed917e_1  
pbr                       3.1.1            py36h1bc6f65_0  
pep8                      1.7.0            py36hc268eb1_0  
pip                       9.0.1            py36h1555ced_4  
py                        1.4.34           py36hecf431b_1  
pylint                    1.7.4            py36hdee9077_0  
pytest                    3.2.1            py36h9963153_1  
pytest-cache              1.0                      py36_0  
pytest-pep8               1.0.6                    py36_0  
pytest-xdist              1.17.1                   py36_0  
python                    3.6.3                h5ce8c04_4  
python-dateutil           2.6.1            py36h86d2abb_1  
pytz                      2017.2           py36h2e7dfbc_1  
pyyaml                    3.12             py36h2ba1e63_1  
readline                  7.0                  hc1231fa_4  
setuptools                36.5.0           py36h2134326_0  
six                       1.11.0           py36h0e22d5e_1  
sqlite                    3.20.1               h7e4c145_2  
tk                        8.6.7                h35a86e2_3  
toolz                     0.8.2            py36h7b95164_0  
tornado                   4.5.2            py36h468dda9_0  
wheel                     0.29.0           py36h3597b6d_1  
wrapt                     1.10.11          py36hc29e774_0  
xz                        5.2.3                h0278029_2  
yaml                      0.1.7                hc338f04_2  
zlib                      1.2.11               hf3cbc9b_2  
```

### CODE REVIEW

**Comment by MattHJensen** [comment]
All tests pass as expected, which shows that our automated testing would not catch this discrepancy.

**Comment by martinholmer** [comment]
@MattHJensen said in #1690:
> As far as I can tell, the only change in this PR was to update from python 2.7 to python 3.6, which I needed to do to handle some bugs in my WIP PR #1614. Yet that Python update appears to have influenced tax-calculator results. Has anyone else run the `requires_pufcsv` tests on master on a machine running Python 3.6?

I'm using Python 2.7, but I thought other developers were using Python 3.6.  No?

Travis-CI uses 2.7 and 3.6 for GitHub check-in testing, but skips the `requires_pufcsv` tests.
We now have plenty of tests that use `cps.csv` input and the results of those tests are not different between 2.7 and 3.6.

Why are the **order** of the variables (never mind the values of the variables) in the `taxcalc/tests/puf_var_wght_means_by_year.csv` file so different on Python 2.7 and Python 3.6?

@hdoupe @GoFroggyRun @andersonfrailey

**Comment by MattHJensen** [comment]
(This is semi-relevant for thinking about solutions, if it is confirmed that this is indeed a problem: https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst)

**Comment by martinholmer** [comment]
@MattHJensen, I have enormous reservations about pull request #1690.
See my comment to your pull request #1614.

**Comment by MattHJensen** [comment]
> See my comment to your pull request #1614.
That was very helpful. Thanks. 

> I have enormous reservations about pull request #1690.
Agreed. I certainly _do not_ think we should merge #1690 (hence the WIP --- I will change that to DO NOT MERGE), but I do think we need to figure out what is causing the discrepancy between the `requires_pufcsv` tests in 2.7 and 3.6 and fix it. Let's call this a bug report in PR form. Thinking about this more, I will open an issue to report a bug and link to this PR.

**Comment by martinholmer** [comment]
@MattHJensen,  I suggest you merge the current master branch (that includes the changes in #1695) into your `update-3.6` development branch and re-run the test suite.

When you do this, do the 2.7 vs 3.6 differences in the following files go away?

`taxcalc/tests/puf_var_correl_coeffs_2016.csv`

`taxcalc/tests/puf_var_wght_means_by_year.csv`

**Comment by MattHJensen** [comment]
@martinholmer, thanks very much for the changes in #1695. All differences go away in `taxcalc/tests/puf_var_correl_coeffs_2016.csv` and major differences go away in `taxcalc/tests/puf_var_wght_means_by_year.csv` but there are still minor 'rounding' differences in `taxcalc/tests/puf_var_wght_means_by_year.csv` and `/pufcsv_agg_expect.txt`. Aiming to add the commit tomorrow.

**Comment by MattHJensen** [comment]
Closing in favor of #1715.

**Pull request closed without merging**
