### PR TITLE
Revise Records read logic to resolve issue #425

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request implements a new way of reading Records data in an attempt to resolve issue #425.

Some minor revisions to the structure of the fake-data ```tax_all1991_puf.gz``` file and to the unit tests were necessary to make the unit test data and logic consistent with the new Records read logic.  See the commit messages for details.

These code changes do not have any effect on the output generated by test.py or test_mtr.py or inctax.py or the validation/tests, and all the py.tests continue to pass after the minor revisions mentioned above.  The test.py and test_mtr.py and inctax.py tests all use a new ```puf.csv``` file generated using the  enhanced ```puf-csv-processing.py``` logic in the pending taxdata pull request 12.

### CODE REVIEW

**Comment by martinholmer** [comment]
@MattHJensen @feenberg @Amy-Xu @GoFroggyRun, 
Any comments, concerns, or questions on pull request #510?

**Comment by GoFroggyRun** [comment]
@martinholmer 
I definitely agree that we should retain those upper-case variables so that we don't have to worry about modifying `functions.py`. So we will need to execute `puf-names.awk` prior to reading the data, is that correct?

**Comment by martinholmer** [comment]
Sean Wang @GoFroggyRun said:
> So we will need to execute ```puf-names.awk``` prior to reading the data, is that correct?

Actually, no.  The ```puf-names.awk``` script was just something used during the development of the records0 branch.  It was mistakenly included in pull request #510, but now I have removed it from the pull request.

@Amy-Xu will be distributing a new ```puf.csv``` file on Tuesday (Dec 22) that is exactly the same as the old one except that the variable names are consistent with the uppercase/lowercase usage in the Tax-Calculator ```functions.py``` code.

cc @MattHJensen @feenberg

**Comment by GoFroggyRun** [comment]
@martinholmer 
Great. Looks good to me then!

**Comment by martinholmer** [comment]
In the ```taxdata``` repository @Amy-Xu has merged pull request 12, which changed some variable names from lowercase to uppercase (in order to be consistent with SOI PUF variable names and with Tax-Calculator code variable names).  And she has used the new ```puf-cps-processing.py``` script to generate a new ```puf.csv``` file, which has been used along with the code in this pull request #510 to run a set of tests.  All the tests (which are enumerated in the lead comment in this conversation) continue to produces the same results as on the master branch using the old ```puf.csv``` file.

@Amy-Xu will post the diagnostic table produced by the new ```puf.csv``` and the code in this pull request #510.  Assuming the diagnostic table results are unchanged, it would seem as if this pull request would be ready to be merged into the master branch.

cc @MattHJensen @feenberg @GoFroggyRun @talumbau 

Note that once pull request #510 is merged into the master branch, use of the new ```puf.csv``` file will be necessary for all development work and for TaxBrain operation.

**Comment by Amy-Xu** [comment]
The diagnostic remains the same as Tax-calculator master.

screen shot 2015-12-22 at 1 17 23 pm

**Comment by Amy-Xu** [comment]
Looks good to me. Just sent everyone a link to the new puf.csv. Merging. Thanks @martinholmer!

**Pull request merged**
