### PR TITLE
Personal nonrefundable credit

### PR DESCRIPTION
**Pull request by econ02**
Solves #1420 

This pull request adds a nonrefundable personal credit. The variables are as follows:

`_II_credit_nr `: Personal nonrefundable credit maximum amount (specified by filing type)
`_II_credit_nr_ps `: Personal nonrefundable credit phaseout start (AGI determined; by filing type)
`_II_credit_nr_prt `: Personal nonrefundable credit phaseout rate

Please let me know if you have other variable name suggestions.

### CODE REVIEW

**Comment by martinholmer** [comment]
@econ02,  Thanks for your contribution in pull request #1427. 
I have a request and a question about the code you're suggesting.

First the suggestion.  How about changing  `per_credit` and `preper` to something a little more explanatory?  Perhaps, `personal_credit` and `max_personal_credit`.  The shorter names are meaningful to you now, but they might not be in six months and the variable names need to be immediately recognizable to anybody working on Tax-Calculator code.

Next the question.  I don't understand the following line in your new PersonalTaxCredit function:
```
   preper = max(0., preper - II_credit_nr_prt * excess)
```
Maybe I missed something, but it looks like `preper` has never been assigned a value when this statement is executed.  Is that your intention?

@MattHJensen

**Comment by econ02** [comment]
@martinholmer 

I will fix the issue with `preper` and rename those variables. 

I agree that making them descriptive is helpful, but I wasn't sure if there was more of a premium placed on keeping current naming conventions.

**Comment by martinholmer** [comment]
@econ02, There are no conventions when naming variables in `records_variables.json` that don't correspond to any feature in current law.  The conventions @MattHJensen was discussing are for policy parameters in the `current_law_policy.json` file.

**Comment by martinholmer** [comment]
@econ02,  The current version looks much better.  Thanks.
Just one final question:

Shouldn't the PersonalTaxCredit function's docstring say something like this?
```
PersonalTaxCredit function computes maximum and actual personal_credit amount
```
Fix that docstring to be more complete and review the new function's comments,
and I'll be happy to merge #1427 into the master branch.

Thanks again for the contribution.

**Comment by econ02** [comment]
@martinholmer All set, thanks for your help!

**Comment by martinholmer** [comment]
Oops!  My suggested docstring is a few characters too long.
Maybe 
```
  PersonalTaxCredit function computes maximum & actual personal_credit amount
```
will squeeze it onto one line.  Or you could use two lines in the docstring.

@econ02

**Comment by econ02** [comment]
@martinholmer 

I should have caught that. Anyway, good to go now.

**Comment by martinholmer** [comment]
@econ02,  Thanks for all the quick responses wrt pull request #1427.  It's merged now.

**Comment by martinholmer** [comment]
@econ02,  I'd like to add your #1427 contribution to the `RELEASES.md` documentation, but because we haven't been formally introduced face-to-face, I'm embarrassed to say I don't know your real name (which is what we're using in the `RELEASES.md` file).

**Comment by econ02** [comment]
@martinholmer 

My name is William Ensor. I apologize for my poor GitHub handle.

**Comment by martinholmer** [comment]
@econ02 said:
> My name is William Ensor.

Would you rather have the `RELEASES.md` document use "Bill Ensor" or
does everybody call you "William"?

**Comment by econ02** [comment]
William or Will is fine (indifferent between the two). Never Bill.

Thanks for asking!

@martinholmer

**Pull request merged**
