### PR TITLE
[WIP] Update EITC Threshold

### PR DESCRIPTION
**Pull request by GoFroggyRun**
This PR updates the EITC threshold for 1 kid and more.

### CODE REVIEW

**Comment by martinholmer** [comment]
Sean,  This change in an EITC parameter reduces the number of differences by 16 (from 604 to 588), but the largest difference is now a little larger than before.  I'm wondering what source of information leads you to believe the parameter value needed to be changed.

Maybe we should list all 2015 EITC-related parameter values (from the current_law_policy.json file) so that Dan can compare what values TAXSIM is using for the same parameters.

Thanks for pursuing this issue.

cc @GoFroggyRun @MattHJensen @feenberg

**Comment by GoFroggyRun** [comment]
@martinholmer :
So, as discussed in #572, record with id 74480 indicates different results for two calculators, where current master yields an EITC amount of $148.22, while TAXSIM approximates the amount to be $146.11. After looking at the table, I found that, since the EITC begins to phase out, it would make more sense to get an estimate lower than the actual value, $147.
And thus I modified the threshold a bit, and, currently, for that particular record, two calculators agree on the EITC amount, which is $146.11.But I'm surprised to see the largest difference gets larger.

**Comment by martinholmer** [comment]
Sean said:
> So, as discussed in #572, record with id 74480 indicates different results for two calculators, where current master yields an EITC amount of $148.22, while TAXSIM approximates the amount to be $146.11. After looking at the table, I found that, since the EITC begins to phase out, it would make more sense to get an estimate lower than the actual value, $147.
And thus I modified the threshold a bit, and, currently, for that particular record, two calculators agree on the EITC amount, which is $146.11.

Sean,  Thanks for your continued work on this issue.  The more results you report, the more it looks to me as if Tax Calculator and Internet TAXSIM may have slightly different 2015 EITC parameters (particularly the phase-out-related parameters).

Do you think it makes sense for you to extract from the ```current_law_policy.json``` file all the 2015 EITC parameters and send them to Dan Feenberg at NBER, asking him to compare them with the 2015 EITC parameters that Internet TAXSIM is using.  If they are the same, then we can attribute the few-dollar cross-model-validation differences in EITC amounts to different rounding rules, I guess. 

What do you think is the most efficient way to resolve this issue?

cc @GoFroggyRun @feenberg @MattHJensen

**Comment by GoFroggyRun** [comment]
@martinholmer 
Sure. I'll extract those parameters and get in touch with him.

**Comment by martinholmer** [comment]
Sean said:
> Sure. I'll extract those parameters and get in touch with him.

Thanks.

**Comment by feenberg** [comment]
Can you send me the thresholds you use for the EITC clawback?

dan

**Comment by martinholmer** [comment]
Sean,  See pull request #605 for the correct EITC phaseout start values for 2015.  Just look at the source mentioned in the ```current_law_policy.json``` file to see what the 2015 IRS documents say are the parameter values.

**Comment by martinholmer** [comment]
Closing pull request #604 because 2015 EITC validation problems have been resolved by pull requests #605 and #613.

**Pull request closed without merging**
