### PR TITLE
Add Renacci reform

### PR DESCRIPTION
**Pull request by hdoupe**
Close #1376

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Thanks for the contribution @hdoupe, taking a second look at the reforms and the proposal, there are three things that need fixing.

First, can you change the year of these reforms to 2017.

Second, in your file, you eliminate the additional standard deduction for aged and blind. Was this mentioned in the proposal? I only remember seeing an increase in the base standard deduction.

Finally, there is one more provision you can account for. You can use the `_ID_BenefitCap_Switch` and `_ID_c` provisions to implement the $500K limit on mortgage interest deductions.

From page 6:
>SATS eliminates all itemized deductions except two, charitable contributions and mortgage interest up to $500,000 of debt

After you've applied the haircut to each of the eliminated itemized deductions, you can set a cap on itemized deductions of $500k and exempt charitable deductions from that cap.

Once you've made those changes this should be ready to merge.

**Comment by MattHJensen** [comment]
@hdoupe, when you open a PR, in the top comment, include "closes #1373" so that everyone can see which issue you are addressing. GH will also automatically close the referenced issue when the PR is merged.

**Comment by MattHJensen** [comment]
@andersonfrailey, the cap you are suggesting would limit the amount of mortgage interest deducted every year to $500,000, whereas the proposal calls for "limiting mortgage interest up to $500,00 of debt."

What do you think about something like setting the cap as the prevailing APR on mortgage interest debt multiplied by $500,000?

Interested to also hear what @codykallen and @feenberg think about this.

**Comment by hdoupe** [comment]
@andersonfrailey, I made the first two changes that you suggested.  I'll follow this feed to see what the final word is on the itemized deductions.

@MattHJensen, thanks for the heads up on closing the issue.

**Comment by MattHJensen** [comment]
@hdoupe, you can also do some digging to see if you can find any other organization who has modeled a similar cap on mortgage interest deduction. Check TPC, Tax Foundation, CBO Budget Options

**Comment by codykallen** [comment]
@hdoupe, there is an easier way to tax capital gains and dividends as ordinary income. You can simply set
`"_CG_nodiff": {"2018": [true]}`

@MattHJensen said

> The proposal calls for "limiting mortgage interest up to $500,00 of debt." What do you think about something like setting the cap as the prevailing APR on mortgage interest debt multiplied by $500,000?

That is not an unreasonable approach, but it raises an interesting issue over the correlation between income and borrowing costs. A high-income individual would have a lower mortgage interest rate than a low-income or middle-income individual. Thus a cap on the debt usable for the interest deduction would  allow low and middle-income individuals to deduct more than high-income individuals, although deductions are relatively more valuable for high-income individuals. So this reform would actually make the mortgage interest deduction more progressive than under current law. 

That being said, I think @MattHJensen's approach is reasonable. Does anyone have a good idea of what interest rate should be used? Especially if rates are set to rise over the 3 years or more.

**Comment by hdoupe** [comment]
I think I understand.  Renacci wants to limit the deduction for interest on a mortgage to $500,000 of debt.  So the actual limit is the APR*500000.  The current APR is 3.946% ([https://www.usbank.com/home-loans/mortgage/mortgage-rates.aspx](url)).  

Then, as @andersonfrailey suggested, the reform would be

`"_ID_BenefitCap_Switch": {
	"2017": [[false, false, true, false, false, false, false]]
},
"_ID_c": {
	"2017": [[19730.0, 19730.0, 19730.0, 19730.0, 19730.0]]
}`

Is this what you all are thinking?
@MattHJensen @codykallen 

I tried to find a similar example, but I didn't have much luck.  The Tax Foundation analyzed this plan.  However, it's not very transparent. ([https://taxfoundation.org/details-and-analysis-rep-jim-renacci-s-tax-reform-proposal/](url))

**Comment by codykallen** [comment]
@hdoupe, I think that is a good approach. 

Also, check your indentation in the JSON. It looks off for the _ID_* variables. Also, as I mentioned earlier, you can replace the 7 _CG_* variables in your JSON with just _CG_nodiff.

**Comment by andersonfrailey** [comment]
@hdoupe, can you add a note in the file about your approach for setting the interest deduction? Other than that, if there's no other objection, this looks ready to merge.

@MattHJensen

**Comment by MattHJensen** [comment]
Thanks for the contribution @hdoupe. Merging. 

Please update https://github.com/open-source-economics/Tax-Calculator/issues/1364 with your contribution.

**Pull request merged**
