### PR TITLE
Fix non-filer weights

### PR DESCRIPTION
**Pull request by Amy-Xu**
In the previous version of extrapolation, I made the mistake of dividing the original non-filers weights by 100 when the weights are as shown. This problem's fixed in this PR. Currently, non-filers total numbers are as following (in millions):

screen shot 2016-01-25 at 1 51 11 pm

Baseline's slightly moved downward. 
screen shot 2016-01-25 at 1 44 11 pm

@MattHJensen Could you review?

### CODE REVIEW

**Comment by Amy-Xu** [comment]
Not sure why the diff looks like this, but the changes should be more than 1 addition and 1 deletion.

**Comment by MattHJensen** [comment]
Do you have a good sense for why the baseline was affected?

**Comment by Amy-Xu** [comment]
Because we change how social security income was targeted right? Previously there was about 1.75 billion (my mistake) added to the sum of total benefits, and now it's removed.

**Comment by martinholmer** [comment]
Amy said:
> Baseline's slightly moved downward. 

But, Amy, you have not executed all the pytests (including the ones marked ```requires_pufcsv```) on your local computer, otherwise you would have revised one or both of the taxcalc/tests/pufcsv_*_expected.txt files.

cc @Amy-Xu @MattHJensen @GoFroggyRun

**Comment by Amy-Xu** [comment]
Thanks @martinholmer! Could you kindly point me to the issue/documentation of this test? Does this have anything to do with travis CI failure here?

**Comment by martinholmer** [comment]
Amy said:
> Thanks @martinholmer! Could you kindly point me to the issue/documentation of this test?

Read tax-calculator/TESTING.md on GitHub (so that the markdown is correctly rendered).

> Does this have anything to do with travis CI failure here?

I doubt it, but better to check with T.J.  Looks like the Travis-CI problem was only with Python 3.5, which is a recent addition to the Travis-CI testing for this project.  Perhaps the code coverage test failed.  I'm not too good at deciphering the Travis-CI detailed output.  Again, check with T.J.

cc @Amy-Xu @MattHJensen @talumbau @GoFroggyRun

**Comment by MattHJensen** [comment]
@martinholmer, I am about to open another PR that modifies the calculators results and will fail the requires_pufcsv tests. I did not see in TESTING.md a suggestion for how to proceed when this happens. Could you please advise?

**Comment by Amy-Xu** [comment]
...........I didn't do anything......it fixed itself?

**Comment by Amy-Xu** [comment]
@martinholmer Is there any reason you removed your script generating updated aggregate results? It seems to be very useful. I added it back here in this PR. Let me know what you think.

**Comment by martinholmer** [comment]
Amy said:
> @martinholmer  Is there any reason you removed your script generating updated aggregate results?

Yes, because it was moved to the pytest suite as one of the two ```requires_csv``` tests.

> It seems to be very useful. I added it back here in this PR. Let me know what you think.

Yes, it is useful, which is why we have moved it into the py.tests suite of tests.
So, what I think is that you **remove** the testagg.py file from this pull request #550.

I'll respond to your question about how to fix the failing ```requires_pufcsv``` test later.

@Amy-Xu @MattHJensen @talumbau @GoFroggyRun

**Comment by Amy-Xu** [comment]
Thanks @martinholmer. Just removed that script. 

I have already fixed the requires_pufcsv test for this PR. Previously I didn't see any function in the test suite update those expected aggregates, so I went to the script you used in a previous PR #525. Sorry about that.

**Comment by martinholmer** [comment]
Amy said:
> Thanks @martinholmer. Just removed that script.
>
> I have already fixed the requires_pufcsv test for this PR. Previously I didn't see any function in the test suite update those expected aggregates, so I went to the script you used in a previous PR #525. Sorry about that.

Yes, whatever you did worked fine because when I download this pull request #550 onto my computer
and run the pytests (including the ```requires_pufcsv``` tests) they all pass.

I'll update the TESTING.md documentation to explain how to use ```git diff``` results to update the ```pufcsv_???_expected.txt``` files after a test failure.  I hope pull request #554 is not as far along as you got, so I can test my intended edits to TESTING.md.

Everything looks good to me with this pull request #550.  Do other people want to review, or should it be merged into the master branch now?

@Amy-Xu @MattHJensen @GoFroggyRun

**Comment by Amy-Xu** [comment]
That would be awesome! Thanks @martinholmer 

cc @MattHJensen

**Comment by MattHJensen** [comment]
@Amy-Xu and @martinholmer, just to confirm, I have reviewed this and will merge now. 

@martinholmer, looking forward to your `TESTING.md` updates; I'll give you feedback after I use them for #554.

**Pull request merged**
