### PR TITLE
Rewording in Tax-Calculator source code tree

### PR DESCRIPTION
**Pull request by martinholmer**
@MattHJensen,  Is this better?

### CODE REVIEW

**Comment by MattHJensen** [comment]
Looks good. Thanks!

**Comment by martinholmer** [comment]
@MattHJensen,  I agree that it is good to give the Tax-Calculator a separate identity from the OSPC, since the whole point of the project is to make it a public resource via the open-source approach to software development.

Given my agreement with that point, I've made several more edits to the comments in the Tax-Calculator source code tree.  They are part of this pull request.

But there was one usage of OSPC in the source code that I felt you should change:
```
iMac2:tax-calculator mrh$ grep -r --include="*py" OSPC .
./taxcalc/calculate.py:        OSPC_TAX(self.policy, self.records)
./taxcalc/calculate.py:        add_df(all_dfs, OSPC_TAX(self.policy, self.records))
./taxcalc/functions.py:def OSPC_TAX(c09200, c59660, c11070, c10960, c11600, c10950, _eitc, e11580,
iMac2:tax-calculator mrh$ grep -r --include="*md" OSPC .
iMac2:tax-calculator mrh$ 
```

**Comment by MattHJensen** [comment]
Thanks @martinholmer. 

Are there better alternatives for `OSPC_TAX()` and `_ospctax` than `IIT_TAX()` and `_iit`? 

cc @Amy-Xu, @feenberg

**Comment by martinholmer** [comment]
@MattHJensen said:
> Are there better alternatives for ```OSPC_TAX()``` and ```_ospctax``` than ```IIT_TAX()``` and ```_iit```?

These sound fine to me, but you need to wait for reactions from @Amy-Xu and Dan @feenberg.

If they are OK with those changes, I would be happy to do the search-and-replace work as part of this pull request.  If you want to do the changes yourself, then my work on this pull request is finished and you can merge these changes after you review.

**Comment by martinholmer** [comment]
@MattHJensen said:
> Are there better alternatives for OSPC_TAX() and _ospctax than IIT_TAX() and _iit?

Actually, after further though and purusal of the source code, I think ```_iitax``` is better than ```_iit```.

**Pull request merged**
