### PR TITLE
Add _EITC_indiv policy parameter and associated logic

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request adds the `_EITC_indiv` policy parameter that causes the current-law, filing-unit-based and number-of-kids-based EITC to be replaced by an individual-based EITC that does not vary by the number of kids.  These code changes cause no change in current-law tax results or in reform comparison results.

Here is a description of this reform provision:
```
Replace the Earned Income Tax Credit (EITC) with a credit specifically focused on 
workers (without an additional calculation for children in a household).
   This reform would create a subsidy for workers who earn less than $35,000
in wage income. The maximum subsidy would be $1000 and would be phased
in at a rate of 10% starting with the first dollar in wage income and hitting the
maximum subsidy at $10,000 in earned income.  Other tax provisions aside,
this feature would create a 10% negative income tax bracket up to the $10,000
earnings level.
   The subsidy would phase out at a 10% rate beginning at $25,000 with the 
credit fully phased out by the time a worker earns $35,000 in wages. 
   The subsidy would be calculated on a per-worker income basis rather than
on a household income basis like the current EITC. 
   Under the proposal, if a family has more than one wage earner, each would 
be eligible for the wage subsidy up to $35,000 in wages. This could result in
a married couple earning a total of $50,000 ($25,000 each) with $2,000 wage
subsidy.
```
Subsequent discussion confirmed that in the above description the phrase
"wage income" is the same concept as used in the current EITC: 
```
[We will not] be changing the definition of income for the redesigned EITC.
It should continue to include wage and salary income along with self-
employment income minus half the payroll tax [on self-employment income].
```

Please review these code changes to see if you think they capture the logic of this reform.

I'm assuming the property income eligibility rule under current law is not part of
this reform proposal because there is no way (with available information) to allocate
property income between the taxpayer and spouse.

See below for some preliminary results on the 2018 income tax revenue effects of this reform provision considered in isolation.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen

```
$ cp ../tax-calculator-data/puf.csv .

$ python inctax.py puf.csv 2018 --blowup --weights
You loaded data for 2009.
Your data have been extrapolated to 2018.

$ awk '{r+=$4*$29}END{print r}' puf-18.out-inctax
1.564e+12

$ cat ind-eitc.json 
{
    // This reform replaces current filing-unit EITC with an individual EITC
    "_EITC_indiv": {"2018": [1]},  // replace current EITC beginning in 2018
    // Note that individual (rather than filing-unit) EITC uses only the
    // first, EIC=0, parameter values:
    "_EITC_rt": {"2018": [[0.10, 0, 0, 0]]},  // phase-in rate
    "_EITC_c": {"2018": [[1000, 0, 0, 0]]},   // maximum individual credit
    "_EITC_ps": {"2018": [[25000, 0, 0, 0]]}, // phase-out start earnings level
    "_EITC_prt": {"2018": [[0.10, 0, 0, 0]]}  // phase-out rate
}

$ python inctax.py puf.csv 2018 --blowup --weights --reform ind-eitc.json
You loaded data for 2009.
Your data have been extrapolated to 2018.

$ awk '{r+=$4*$29}END{print r}' puf-18.out-inctax-ind-eitc 
1.57722e+12

Notice that this reform provision, in isolation, causes an increase in
2018 aggregate income tax revenue --- i.e., a decline in credits ---
of about $13.2 billion.
```

### CODE REVIEW

**Comment by MattHJensen** [comment]
@martinholmer, thanks for this PR. I just left one comment on the diff, and otherwise all looks good.

**Comment by martinholmer** [comment]
The latest version of this pull request #1028 allows the basic EITC parameters to vary by the number of eligible children in the individual-based calculation (as they do in the filing-unit-based calculations under current law).

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @codykallen @talumbau

**Comment by martinholmer** [comment]
@MattHJensen,  Shall I merge pull request #1028 wrt individual-based EITC?  Or do you want to review the latest version of the pull request?

**Comment by MattHJensen** [comment]
LGTM. Thanks @martinholmer

**Comment by MattHJensen** [comment]
Merging.

**Pull request merged**
