### PR TITLE
Streamline growth.py code and move location of rates-consistency test

### PR DESCRIPTION
**Pull request by martinholmer**
The growth.py code has been changed to do the following three things:
(1) remove unused inflation_rates argument from Growth class constructor;
(2) make default_real_GDP_growth_rate a static method; and
(3) streamline code in the global function target().

The test comparing three sets of default rates with those implied by the Records blowup factors has been moved from test_calculate.py to test_records.py because there was no use of the Calculator class in the test.

@Amy-Xu, does all this make sense?

### CODE REVIEW

**Comment by Amy-Xu** [comment]
Yep looks good to me!

**Comment by MattHJensen** [comment]
@amy-xu, could you go ahead and merge if all looks good?

**Comment by martinholmer** [comment]
@Amy-Xu,  Have you had a chance to review this again?  Any suggestions for improvement?

**Comment by Amy-Xu** [comment]
Sorry somehow I thought this was a different PR I had reviewed and merged. Apparently it wasn't. Even though a bit late, LGTM! Thanks @martinholmer for refactoring this messy section.

**Comment by martinholmer** [comment]
@Amy-Xu you had reviewed this earlier and I figured you were really busy.

**Pull request merged**
