### PR TITLE
Add IncomeTaxIO class for cross-model validation using PUF

### PR DESCRIPTION
**Pull request by martinholmer**
The IncomeTaxIO class is a more complex version of the SimpleTaxIO class.  This initial version reads csv-formatted PUF data and writes Internet-TAXSIM output.  All the FICA-related output variables are set to zero to accomodate situations where the input PUF data do not include information about the split between head and spouse earnings.  There are two unit tests of this new class in the test_incometaxio.py file.  This pull request also includes a command-line interface to the IncomeTaxIO class called inctax.py.

When using puf.csv as input, the results generated by this inctax.py script, and the new test.py script, will help guard against performance regressions as we make progress on Issues #425, #436, and #452.

### CODE REVIEW

**Comment by martinholmer** [comment]
@MattHJensen, @Amy-Xu, Sean @GoFroggyRun,
Do you want to look this over before it gets merged?  There is nothing here the affects the logic of the Tax-Calculator itself, but sometimes it is easier to see what code is being added in the context of a pull request.  Any questions, comments or suggestions would be welcome.

**Comment by GoFroggyRun** [comment]
@martinholmer The IncomeTaxIO class looks good to me. It might be hard for me to get any suggestions offhand, by looking at the code. We can definitely figure out further improvements afterwards though.

**Comment by MattHJensen** [comment]
This looks great and I plan to merge it. @Amy-Xu, any objections? 

@martinholmer, my next step will be to run the same data through this and SimpleTaxIO (modifying headers as needed) to make sure that I understand everything well enough to get the same output.

**Comment by Amy-Xu** [comment]
No objections.

**Comment by MattHJensen** [comment]
Merging. Thanks @martinholmer!

**Comment by martinholmer** [comment]
@MattHJensen said:
> my next step will be to run the same data through this and SimpleTaxIO (modifying headers as needed) to make sure that I understand everything well enough to get the same output.

That's an interesting idea I hadn't thought about.  As you work with these two capabilities remember that (right now, at least) the IncomeTaxIO class calls the impute_variables() method in the Records class, while SimpleTaxIO does not call the impute_variables() method.  I'll be interested in what your experience is like.

**Comment by MattHJensen** [comment]
> As you work with these two capabilities remember that (right now, at least) the IncomeTaxIO class calls the impute_variables() method in the Records class, while SimpleTaxIO does not call the impute_variables() method.

Thanks for this reminder. I'll set consider_imputations = False in IncomeTaxIO when testing against SimpleTaxIO. For our initial round of cross-model validation with TPC we'll likely want to skip the imputations as well.

**Comment by martinholmer** [comment]
@MattHJensen said:
> Thanks for this reminder. I'll set consider_imputations = False in IncomeTaxIO when testing against SimpleTaxIO. For our initial round of cross-model validation with TPC we'll likely want to skip the imputations as well.

It will be interesting to see how that goes, but my initial impression was that there was not an easy and sensible way to skip the impute_variables() method.  Mostly it is an issue of the ```_numextra``` variable being a key parameter and not being in the IRS-SOI-PUF file.  Maybe I'm confused about what you mean by "use any subset of the PUF data."  Do you mean any subset of the IRS-SOI-PUF data or any subset or the OSPC-generated ```puf.csv``` file (which is actually a PUF-CPS merge)?

**Comment by MattHJensen** [comment]
> Do you mean any subset of the IRS-SOI-PUF data or any subset or the OSPC-generated puf.csv file (which is actually a PUF-CPS merge)?

Ideally this distinction shouldn't matter. When I say "use any subset of the PUF data," I suppose I really mean "use any subset of input data." It could be that we need to specify some minimum set of variables that could possibly include `_numextra,`  but I haven't yet confirmed that there is a problem with having `_numextra` as all zeroes, which is how we've talked about treating missing variables.

**Pull request merged**
