### PR TITLE
Releases.md and docs 0.13.0

### PR DESCRIPTION
**Pull request by MattHJensen**
Thanks to @martinholmer, @codykallen, @andersonfrailey, and @hdoupe for contributions to 0.13.0. Please let me know if you have any objections to the descriptions of your work in this PR. I plan to merge this after about 30 minutes.

### CODE REVIEW

**Comment by MattHJensen** [comment]
This PR also attempts to resolve the docs issue pointed out by @martinholmer's comment: https://github.com/open-source-economics/Tax-Calculator/issues/1627#issuecomment-342495153

**Comment by martinholmer** [comment]
@MattHJensen,  This PR should not include the `./taxcalc/docs/index.html` file.

**Comment by martinholmer** [comment]
@MattHJensen,  Perhaps I've not been clear, so let me say it again:

> The command `python make.py` reads the ./taxcalc/docs/index.htmx` skeleton file and
writes the fleshed-out `./docs/index.html` file, which is the one that needs to be updated in a pull request.

So it looks like you edited the wrong file to reflect the new headings.  Edit the `index.htmx' and **remove** the `./taxcalc/docs/index.html` file.

**Comment by martinholmer** [comment]
@MattHJensen,  "add index.htmx rm index.html" commit looks great.
Don't forget the rerun `python make.py` so as to generate the new `./docs/index.html` file, the updates to which should be part of this PR.

**Comment by MattHJensen** [comment]
> So it looks like you edited the wrong file to reflect the new headings. Edit the index.htmx file and remove the ./taxcalc/docs/index.html file.

I added the wrong file to the commit rather than edited the wrong file. See the latest commit.

**Comment by MattHJensen** [comment]
@martinholmer said:

> Don't forget the rerun python make.py so as to generate the new ./docs/index.html file, the updates to which should be part of this PR.

Those changes are in [this commit](https://github.com/open-source-economics/Tax-Calculator/pull/1632/commits/f489ca8a9756ed017da59951bc0ab2874cb5aa06).

**Comment by martinholmer** [comment]
@MattHJensen,
Did you decide not to include the chained CPI reform in `TCJA_Nov3.json` and release 0.13.0?

**Comment by MattHJensen** [comment]
@martinholmer said:

> Did you decide not to include the chained CPI reform in TCJA_Nov3.json and release 0.13.0?

@codykallen, do you think it would make sense to include in TCJA_Nov3.json:

"growdiff_response": {
    	"_ACPIU": {"2017": [-0.0025]}
    	}

I am also hoping for a resolution of #1621 and release of 0.13.1 soon so that the chained CPI change can be incorporated in the policy reform. @martinholmer, are you working on #1621?

**Comment by codykallen** [comment]
@MattHJensen suggested applying
`"growdiff_response": {
"_ACPIU": {"2017": [-0.0025]}
}`

The proposal does not apply the switch to chained CPI to all parameters at the same time. Until more flexibility is built into Tax-Calculator regarding the inflation adjustment to different parameters, I'd rather not apply such a generalization.

**Comment by MattHJensen** [comment]
> The proposal does not apply the switch to chained CPI to all parameters at the same time. Until more flexibility is built into Tax-Calculator regarding the inflation adjustment to different parameters, I'd rather not apply such a generalization.

Thanks. Could you update #1621 with a description of what is needed? Right now, #1621 only requests for a user to be able to do `"growdiff_response": { "_ACPIU": {"2017": [-0.0025]} }` except with a policy parameter.

**Comment by MattHJensen** [comment]
@codykallen, as far as I can tell, the majority of important provisions adopt the new chained cpi in 2018 -- this was updated in the [chairmans mark](https://waysandmeans.house.gov/wp-content/uploads/2017/11/20171106-Amendment-in-the-Nature-of-a-Substitute-to-H.R.-1.pdf) last Friday. I expect it is more accurate to apply C-CPI to all CPI-adjusted parameters immediately than not to apply it to any of them (except for the manually adjusted CTC stuff). Am I missing something?

**Comment by MattHJensen** [comment]
It was actually me, not @codykallen, that said:

> the majority of important provisions adopt the new chained cpi in 2018 

Waiting for @codykallen for his agreement/disagreement with that.

**Comment by codykallen** [comment]
@MattHJensen, yes, most of the provisions switch to chained CPI-based adjustment in 2018. If you want to implement that, go ahead.

**Comment by MattHJensen** [comment]
The intent of @martinholmer's bolding just dawned on me:

> So, then the assumption file that is paired with the reform file could include:

The point is that we (smartly) don't include assumptions and reforms in the same file, and so we would need to add an additional assumption file. I would rather communicate this option to users verbally to users who ask rather than author a default assumption file and then have to explain how it is really an additional reform and doesn't include what I think the other assumptions should be. 

Back to waiting on #1621 and 0.13.1 for c-cpi changes in the reform file.

**Comment by martinholmer** [comment]
@MattHJensen said:
> Back to waiting on #1621 and 0.13.1 for c-cpi changes in the reform file.

I'm fine with this strategy, but am mystified at why adding a chained-CPI option to `current_law_policy.json` would be a bug fix.  Sounds more like a major enhancement to Tax-Calculator to me.  So, why not include that enhancement in the 0.14.0 release?

**Comment by MattHJensen** [comment]
@martinholmer said:

> I'm fine with this strategy, but am mystified at why adding a chained-CPI option to current_law_policy.json would be a bug fix. Sounds more like a major enhancement to Tax-Calculator to me. So, why not include that enhancement in the 0.14.0 release?

If we were beyond version 1.0.0, we would increment `x` for major releases (breaking backwards compatibility), `y` for minor releases (adding new functionality), and `z` for bug fixes.

Given that we are before 1.0.0, we only have `y` and `z` to work with (`0.y.z`), and we are forced to combine two types of releases (major update, minor update, bug fix) into either `y` or `z`. 

We have chosen to combine both bug fixes and minor updates into `z`, so that y can uniquely denote backwards incompatible updates with `y`. 

The new `current_law_policy.json` would be a minor update, and therefore if it is the only change, the new version should be 0.13.1

Examples:

https://github.com/open-source-economics/Tax-Calculator/blob/master/RELEASES.md#2017-07-06-release-091

https://github.com/open-source-economics/Tax-Calculator/blob/master/RELEASES.md#2017-07-26-release-092

**Comment by martinholmer** [comment]
@MattHJensen said:
> We have chosen to combine both bug fixes and minor updates into z, so that y can uniquely denote backwards incompatible updates with y.

Actually, you have espoused this view, which I don't agree with.  It's way too confusing to mix "bug fixes" and "minor enhancements".    What if we need to fix a bug in 0.13.0?  Then we should fix that in release 0.13.1, which is based off the original 0.13.0 (not off the HEAD of the master branch).
And if another bug is found in 0.13.1, then that release needs to be fixed in 0.13.2.
This is not hypothetical; this is exactly what happend with 0.10.0 --> 0.10.1 --> 0.10.2.

And in CPI indexing case, the enhancement hardly seems "minor" to me.   But maybe you view it as "minor".  If so, it's just another way your notion of release numbering is vague and subject to different interpretations by different contributors.

**Comment by MattHJensen** [comment]
@martinholmer, I am just using the notion of major release, minor release, and bug fix from [semver.org](http://semver.org/).  Do you disagree that adding a new parameter to current_law_policy.json would qualify for a minor release based on the terminology used by the official semantic versioning documentation? 

The examples that I gave were both releases that you issued. 

I am confused.

**Comment by martinholmer** [comment]
@MattHJensen asked:
> Do you disagree that adding a new parameter to `current_law_policy.json` would qualify for a minor release based on the terminology used by the official semantic versioning documentation?

Here is what semver.org says:
> Given a version number MAJOR.MINOR.PATCH, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.

And my understanding is that when at MAJOR=0, then all releases that are not exclusively bug fixes involve a MINOR change.

@MattHJensen, is that your understanding?

I view adding a new policy parameter as not a bug fix, so the next release would increment Y and be Y.0.
So, if we are at 0.13.0 and we add a new policy parameter, we move to the 0.14.0 release.  And this would be the case even if we have to issue a bug fix to 0.13.0 in a 0.13.1 release.

**Comment by MattHJensen** [comment]
> And my understanding is that when at MAJOR=0, then all releases that are not exclusively bug fixes involve a MINOR change.

No, that is not my view, it does not reflect what I have written above, and it does not describe what we have already been doing as evidence by the examples I provided above. If you think that there is a better approach than what we are currently doing, then I would recommend opening a new issue to propose a new approach to versioning -- I expect everyone in the tax-calculator project, certainly including myself, would be happy to discuss the merits of a new approach.

**Comment by martinholmer** [comment]
@MattHJensen said:
> If we were beyond version 1.0.0, we would increment x for major releases (breaking backwards compatibility), y for minor releases (adding new functionality), and z for bug fixes.
>
> Given that we are before 1.0.0, we only have y and z to work with (0.y.z), and we are forced to combine two types of releases (major update, minor update, bug fix) into either y or z.
>
> We have chosen to combine both bug fixes and minor updates into z, so that y can uniquely denote backwards incompatible updates with y.
>
> The new `current_law_policy.json` would be a minor update, and therefore if it is the only change, the new version should be 0.13.1

If we do what you propose above and we find a bug in 0.13.1 that needs immediate fixing, what will we call the release that is exactly the same as 0.13.0 except that the bug is fixed?

**Comment by MattHJensen** [comment]
> If we do what you propose above and we find a bug in 0.13.1 that needs immediate fixing, what will we call the release that is exactly the same as 0.13.0 except that the bug is fixed?

We would add that to the changes in 13.1 and include it in 13.2. Note that this is the exact same approach as including bug fixes to 0.11.0 (or earlier) in a 0.12.0 release, which is what we [just did](https://github.com/open-source-economics/Tax-Calculator/blob/master/RELEASES.md#2017-10-20-release-0120). 

Also note that this is the same approach that Pandas used before 1.0.0 days. See, for example, [0.18.1](https://github.com/pandas-dev/pandas/releases/tag/v0.18.1). 

But I _really_ think this discussion would be better off in a new issue.

**Pull request merged**
