### PR TITLE
Add filer credit

### PR DESCRIPTION
**Pull request by codykallen**
This PR adds a new non-refundable credit for the filer and their spouse as structured in the Tax Cuts and Jobs Act. The relevant portions of the act increase the child tax credit by $600, but this increased amount is nonrefundable. This is implemented with existing capabilities by setting `'_DependentCredit_Child_c': [600]`

It also creates a $300 nonrefundable credit for non-child dependents. This is implemented using existing capabilities by setting `'_DependentCredit_Nonchild_c': [300]`. It phases out as though part of the child tax credit. 

It also creates a $300 nonrefundable credit for the filer and their spouse, which phases out as though part of the child tax credit. This phase-out structure means that it cannot be properly implemented using the personal nonrefundable credit. This PR adds the capability to accurately model this, by setting `'FilerCredit_c': [[300, 600, 300, 300, 300]].

### CODE REVIEW

**Comment by codykallen** [comment]
@MattHJensen @andersonfrailey @hdoupe @martinholmer @Amy-Xu 

This PR adds another capability for modeling the Tax Cuts and Jobs Act.

**Comment by MattHJensen** [comment]
This looks right to me. @andersonfrailey, could you confirm?

**Comment by andersonfrailey** [comment]
Looks good to me as well

**Comment by MattHJensen** [comment]
Thanks @codykallen for the contribution and @andersonfrailey for the review. Merging.

**Pull request merged**
