### PR TITLE
added time_it.py timing file

### PR DESCRIPTION
**Pull request by jlyons871**
Added a script, similar to test.py, but for timing instead of accuracy usage.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@jlyons871, what is the status on this PR? I still view this as a potentially useful tool, so I am hesitant to close it. 

From @martinholmer  in #322 
>The last commit to the func_timer branch was on Dec 19, 2014.
Is it really still active? If not, perhaps it should be deleted?

**Comment by MattHJensen** [comment]
@talumbau, do you have any advice on this PR? We obviously haven't been using this feature, but do you think it would be helpful to clean it up? Otherwise I'll close it.

**Comment by talumbau** [comment]
Ah, yes I think this has been abandoned and now what it is timing is not representative of what the code actually does. I'm more inclined to handle a timing measurement with a decorator style so that it is forwards compatible with future changes to Tax-Calculator. We can discuss details if desired. Closing for now.

**Comment by MattHJensen** [comment]
Thanks @talumbau

**Pull request closed without merging**
