### PR TITLE
Update stats summary script

### PR DESCRIPTION
**Pull request by Amy-Xu**
This script has been updated to work with the latest version of Tax-Calculator. Output files get updated as well. Thanks to Martin for pointing out in issue #1562.

### CODE REVIEW

**Comment by Amy-Xu** [comment]
@martinholmer this PR fixed the `stats_summary.py` in comparison. Could you review?

**Comment by martinholmer** [comment]
@Amy-Xu said in #1566:
> This PR fixed the `stats_summary.py` in comparison. Could you review?

Thanks.  Yes.  I'll try to review it no later than tomorrow morning.

**Comment by martinholmer** [comment]
@Amy-Xu,  When I download pull request #1566 to my computer and do the two runs, I get the same results in the `variable_stats_summary.csv` file, but I don't get the same results in the `correlation.csv` file.  My suspicion is that this is caused by you showing excessive floating-point precision in the `correlation.csv` file.  We already have other evidence that floating point calculations are not exactly the same on Python 2.7 and Python 3.x.  And besides, telling users that the correlation coefficient between two variables has a value of, say, `-0.0050643581807` is not sensible.  Not only is is hard to read a fraction with that many digits, it assigns way too much precision.  Why not round the correlation coefficients to three decimal points, so that instead of `-0.0050643581807`, you show `-0.005`?  Is there any practical difference between those two values?

**Comment by martinholmer** [comment]
@Amy-Xu,  I haven't studied the code in the `stats_summary.py` script, but I was wondering whether it is possible to have that script produce **both** output files at the same time.  Would it be possible to do that without an excessive amount of work?

**Comment by Amy-Xu** [comment]
@martinholmer Thanks for the review. I'll round all results to three decimal points. 

In terms of generating both files at the same time, the original thought was simply that users may just be interested in one of them so it would be the most convenient for users to produce one a time. Since we also need to update the files, it makes sense to me producing both at the same time. I'll revise the code accordingly.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> Thanks for the review. I'll round all results to three decimal points.
>
> In terms of generating both files at the same time, the original thought was simply that users may just be interested in one of them so it would be the most convenient for users to produce one a time. Since we also need to update the files, it makes sense to me producing both at the same time. I'll revise the code accordingly.

Thanks.

**Comment by martinholmer** [comment]
@Amy-Xu, Thanks for this update.  Look good, so I'll merge it now.
I already updated the `RELEASES.md` info to describe your enhancement.

**Pull request merged**
