### PR TITLE
Switch to new weights file and associated changes

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR updates `WEIGHTS.csv` and `StageIFactors.csv` after the changes made in TaxData PR [#52](https://github.com/open-source-economics/taxdata/pull/52), which updated the data used during the extrapolation process to include the latest data from the CBO and IRS. It also updates other files throughout the package as needed. Here are all of the changes made:

1. New weights file
2. New `StageIFactors.csv` to be used as blowup factors
3. In `growth.py`: change `REAL_GDP_GROWTH_RATES` list to match new GDP and inflation values
4. In `growth.json`: change values in `_factors_target` to reflect new real GDP growth rates
5. In `test_growth.py`: change the first two values of the `_factor_target` array used in `test_update_growth` to match new default real GDP rates
6. In `policy.csv`: change `__pirates` and `__wgrates` to reflect new values
7. In `pufcsv_agg_expect.txt`: change expected aggregate totals to be consistent with calculations using new weights
8. In `'pufcsv_mtr_expect.txt`: change MTR histogram counts to match values calculated with new weights

Some of the changes to aggregate totals can be seen in the files changed, but to make the comparison easier [here](http://nbviewer.jupyter.org/github/andersonfrailey/Tax-Calculator/blob/NotebookUpload/TaxCalc%20CBO%20Comparisons.ipynb) is a python notebook that compares the new calculations with the old, and the new tax liability projections to CBO revenue projections from 2016 to 2026.

It should be noted that CBO revenue projections are by fiscal year and project **all** revenue, including things such as taxes from previous years being paid late, while tax-calc only calculates tax liability and is by calendar year.

@codykallen asked how this updates affected the distribution of various sources of income. [Here](http://nbviewer.jupyter.org/github/andersonfrailey/Tax-Calculator/blob/NotebookUpload/Distribution%20Tests.ipynb) is another notebook that takes a look at this for 2014 (the latest year available for SOI data). The comparison breaks each income source up by AGI bin and plots both aggregate totals per bin and what percentage of the total is in each bin. The comparison is between current tax-calc numbers, numbers with the new weights, and [SOI tax stats](https://www.irs.gov/uac/soi-tax-stats-individual-statistical-tables-by-size-of-adjusted-gross-income).

Overall there wasn't too much change in the distributions with this update. It appears the worst distribution for tax-calc is in taxable interest. I spent much of this past weekend trying to correct this by adding a variety of targets to our LP model in stage 2 of the extrapolation process, but so far have had no luck. 

If it appears I have missed something, made an error in my updates, or you want to see some other comparison between old and new, please let me know. 

Also, The notebooks don't always load for some reason. If you're having trouble with them I'm happy to email the files to you.

@MattHJensen @martinholmer @Amy-Xu @codykallen @feenberg @GoFroggyRun

### CODE REVIEW

**Comment by andersonfrailey** [comment]
@martinholmer just wanted to let you know I've seen your comment. I got caught up in some other work yesterday and earlier today, but I'm looking into your question now and will address the merge conflict and missing tests as well.

**Comment by martinholmer** [comment]
@andersonfrailey said:
>  I got caught up in some other work yesterday and earlier today, but I'm looking into your question now and will address the merge conflict and missing tests as well.

No rush!  I'll be out of the office from this afternoon through next Tuesday (12/20).

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>Why do payroll tax revenues drop when moving to the new CBO assumptions even as income tax revenues rise substantially?

Looking at the targets used in the extrapolation process for wages and capital gains, whose growth is based in part on CBO projections, both of your thoughts on why income tax liability increased while payroll tax liability decreases (shift from labor income to capital income, shift from lower labor incomes to higher labor incomes) could be correct.

Overall, projected wages and salaries income decreases. Along with that, the percentage of total wages and salaries earned by those with higher AGI increases. The biggest upward shift is seen by those with AGI at $1M or more. Their share of total wages and salaries goes from 5.35% to 6.02%.  [CBO's 10-year economic projections](https://www.cbo.gov/about/products/budget-economic-data#4) also shows a decrease in wage and salary income between the August 2014 and August 2016 releases, but does not offer specifics on how the distribution changes, if they assume any changes.

Additionally, for every year after 2014, capital gains in AGI sees an increase. This can all be seen [here](http://nbviewer.jupyter.org/github/andersonfrailey/taxdata/blob/Notebooks/Stage%20II/Target%20Comparison.ipynb).

[The CBO](https://www.cbo.gov/about/products/budget-economic-data#4) also shows a reduction in payroll tax revenue projections between their August 2014 and August 2016 releases, but it is accompanied by a decrease in income tax revenue as well:

| Tax         | 2015   | 2016    | 2017    | 2018    | 2019    | 2020    | 2021    | 2022    | 2023    | 2024     | 
|-------------|--------|---------|---------|---------|---------|---------|---------|---------|---------|----------| 
| Income Tax  | 15.098 | -69.121 | -68.531 | -54.768 | -54.161 | -66.368 | -72.203 | -82.298 | -93.903 | -102.555 | 
| Payroll Tax | 0.638  | 12.49   | 3.451   | -5.289  | -21.392 | -41.961 | -44.493 | -51.901 | -58.842 | -65.539  | 

That being said, the increase in income tax liability seen in this PR results in income and combined tax liabilities that are closer to the tax revenues projected by the CBO. However, the decrease in payroll tax liabilities moves us further away from CBO projections.

**Comment by martinholmer** [comment]
@andersonfrailey said about the `puf.csv` changes proposed in PR #1105:
> That being said, the increase in income tax liability seen in this PR results in income and combined tax liabilities that are closer to the tax revenues projected by the CBO. However, the decrease in payroll tax liabilities moves us further away from CBO projections.

Thanks for the discussion of my question, but even after all the helpful information you have provided, we are still in the dark about why the payroll tax revenues go down and are further away from the CBO projections than before the changes in PR #1105.  This seems like a problem, especially because of the discussion in issue #1110, which is reasonable but will cause payroll tax revenue to decline even more than it does in #1105.  This will mean that our payroll tax projections will be even further away from CBO projections.  It is important to understand why this is so.  If we understand it, then we can either improve our own methods or feel confident that CBO projections don't make as much sense as our own new projections.

@MattHJensen @feenberg @Amy-Xu @codykallen

**Comment by andersonfrailey** [comment]
I believe I can provide a little more insight into why payroll tax liabilities decrease and why they are further away from CBO projections than our current calculations.

In the full [CBO report](https://www.cbo.gov/sites/default/files/114th-congress-2015-2016/reports/51129-2016Outlook_OneCol-2.pdf), it is stated that they expect wages and salaries to grow faster for higher-income earners resulting in a larger share of income subject to higher income tax rates and above the payroll tax cap. From page 23:

> Individual income taxes are projected to generate increasing revenues… Also, earnings from wages and salaries are expected to continue the recent trend of increasing faster for higher-income people than for others, causing a larger share of income to be subject to higher income tax rates, and, therefore, further increasing revenues.
> 
> Because of the changing wage distribution, however, a growing share of people’s wages and salaries moves above the maximum annual amount that is subject to the Social Security tax… That trend will reduce receipts from payroll taxes relative to GDP—by about three-fifths of the increase in income taxes stemming from the changing distribution. 

TaxCalc assumes the distribution of wages stays the same after 2014 rather than continuing to skew towards higher earners, which could explain some of the difference between CBO and TaxCalc. As for why payroll tax liability drops, after updating to the latest [IRS data](https://www.irs.gov/uac/soi-tax-stats-individual-statistical-tables-by-size-of-adjusted-gross-income) for the stage 2 targets, there is a slight shift in wages and salaries towards the top of the distribution that would move more wages and salaries above the taxable cap. Here is a comparison of the distribution:

| AGI Bin                                           | Original | New     | 
|---------------------------------------------------|----------|---------| 
| Zero or Less                  | 0.324%   | 0.286%  | 
| $1 Less Than $10,000          | 1.478%   | 1.399%  | 
| $10,000 Less Than $20,000     | 4.161%   | 3.861%  | 
| $20,000 Less Than $30,000     | 5.897%   | 5.619%  | 
| $30,000 Less Than $40,000     | 6.480%   | 6.169%  | 
| $40,000 Less Than $50,000     | 6.211%   | 6.166%  | 
| $50,000 Less Than $75,000     | 14.327%  | 13.510% | 
| $75,000 Less Than $100,000    | 12.669%  | 12.389% | 
| $100,000 Less Than $200,000   | 25.387%  | 25.930% | 
| $200,000 Less Than $500,000   | 12.799%  | 14.080% | 
| $500,000 Less Than $1 Million | 4.113%   | 4.574%  | 
| $1 Million and Over           | 6.154%   | 6.017%  | 

CBO also lowered their projections for total wages and salaries (in billions):

| Year | 2014 Projections | 2016 Projections | Difference | 
|------|------------------|------------------|------------| 
| 2016 | 8155             | 8121             | -35        | 
| 2017 | 8568             | 8470             | -98        | 
| 2018 | 8980             | 8828             | -152       | 
| 2019 | 9385             | 9154             | -231       | 
| 2020 | 9799             | 9482             | -317       | 
| 2021 | 10227            | 9843             | -383       | 
| 2022 | 10672            | 10230            | -442       | 
| 2023 | 11131            | 10634            | -498       | 
| 2024 | 11608            | 11053            | -554       | 

Which resulted in lower wages and salaries in TaxCalc after 2019 (in billions):

| Year | WAS: New | WAS: Original | Difference | 
|------|-----------|----------------|------------| 
| 2016 | 7,483.80  | 7,461.80       | 22.00      | 
| 2017 | 7,810.10  | 7,790.80       | 19.30      | 
| 2018 | 8,128.10  | 8,118.00       | 10.10      | 
| 2019 | 8,423.50  | 8,428.80       | -5.30      | 
| 2020 | 8,728.00  | 8,749.60       | -21.60     | 
| 2021 | 9,065.20  | 9,102.30       | -37.10     | 
| 2022 | 9,421.80  | 9,477.60       | -55.80     | 
| 2023 | 9,794.00  | 9,873.00       | -79.00     | 
| 2024 | 10,179.90 | 10,284.70      | -104.80    | 
| 2025 | 10,580.50 | 10,711.90      | -131.40    | 
| 2026 | 10,996.80 | 11,157.20      | -160.40    | 

Finally, both before and after the changes in this PR, TaxCalc's total wages and salaries were below CBO's latest projections, but they are further off with this update. The change in error is especially large after 2020/2021, which is also when the error in payroll tax liability increases the most.

| Year | CBO Projections | New - CBO | Old - CBO | Change in Error | 
|------|-----------------|-----------|-----------|-----------------| 
| 2016 | 8121            | -636.70   | -658.70   | -22.00          | 
| 2017 | 8470            | -659.80   | -679.10   | -19.30          | 
| 2018 | 8828            | -699.90   | -710.00   | -10.10          | 
| 2019 | 9154            | -730.40   | -725.10   | 5.30            | 
| 2020 | 9482            | -754.10   | -732.50   | 21.60           | 
| 2021 | 9843            | -777.90   | -740.80   | 37.10           | 
| 2022 | 10230           | -808.10   | -752.30   | 55.80           | 
| 2023 | 10634           | -839.70   | -760.70   | 79.00           | 
| 2024 | 11053           | -873.20   | -768.40   | 104.80          | 
| 2025 | 11488           | -907.50   | -776.10   | 131.40          | 
| 2026 | 11940           | -943.50   | -783.10   | 160.40          | 

@martinholmer @MattHJensen @Amy-Xu

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for all the helpful explanation of Tax-Calculator-vs-CBO differences in the conversation about pull request #1105.  Given your explanation, I could see why Tax-Calculator payroll tax revenue would be higher than CBO's because they have more wage growth above the maximum taxable earnings level and less below.

But do we understand why Tax-Calculator has less total wage-and-salary income than CBO?  This is what you're saying in this statement, right?
```
Finally, both before and after the changes in this PR, TaxCalc's 
total wages and salaries were below CBO's latest projections, 
but they are further off with this update. The change in error 
is especially large after 2020/2021, which is also when the error
in payroll tax liability increases the most.
```
Are we comfortable with this difference?  Do we know why this difference occurs?  Does it have anything to do about the wages and salaries of those CPU-derived units who are not part of the IRS-SOI PUF?

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun

**Comment by codykallen** [comment]
@andersonfrailey, I wonder how much of the difference is due to different GDP growth rates. Considering the our growth rates in growth.json are substantially lower than the CBO's August 2016 projections, could you rerun with new growth rates to see how much of the difference in payroll taxes is due to the different GDP growth rates?

**Comment by andersonfrailey** [comment]
@martinholmer asked:
> But do we understand why Tax-Calculator has less total wage-and-salary income than CBO? This is what you're saying in this statement, right?

Yes, that is correct. I believe what might explain part of the difference is that in the 2009 matched PUF we are using, there is a total of $5.848 trillion in wages and salaries, whereas in their [2010 economic outlook report](https://www.cbo.gov/sites/default/files/111th-congress-2009-2010/reports/01-26-outlook.pdf), CBO estimates 2009 wages and salaries at $6.329 trillion. So while we use growth rates determined using CBO data, the gap does not close.

@codykallen asked:
> I wonder how much of the difference is due to different GDP growth rates. Considering the our growth rates in growth.json are substantially lower than the CBO's August 2016 projections, could you rerun with new growth rates to see how much of the difference in payroll taxes is due to the different GDP growth rates?

Using the real GDP growth rates from the 2016 CBO projections did slightly raise payroll tax calculations:

| 2016            | 2017       | 2018       | 2019       | 2020       | 2021       | 2022       | 2023       | 2024       | 2025       | 2026       |           | 
|-----------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|------------|-----------| 
| New Weights     | 1,064.10   | 1,118.30   | 1,170.90   | 1,219.50   | 1,270.00   | 1,323.50   | 1,380.80   | 1,441.70   | 1,505.00   | 1,569.50   | 1,637.20  | 
| Current Weights | 1,045.30   | 1,093.80   | 1,141.10   | 1,186.20   | 1,232.80   | 1,283.10   | 1,337.10   | 1,394.30   | 1,454.00   | 1,516.10   | 1,580.70  | 
| CBO             |  1,114.00  |  1,149.00  |  1,188.00  |  1,228.00  |  1,267.00  |  1,315.00  |  1,364.00  |  1,414.00  |  1,465.00  |  1,521.00  |  1,579.00 | 

It should be noted that I only applied the different growth rates to the calculator with the new weights not current rates. Those are just listed for comparison.

I think it's worth discussing switching the default real GDP rates in growth.py and growth.json to those in the CBO economic projections, but that should probably be brought up in a separate issue.

**Comment by martinholmer** [comment]
@andersonfrailey said:
>> But do we understand why Tax-Calculator has less total wage-and-salary income than CBO? This is what you're saying in this statement, right?
>
> Yes, that is correct. I believe what might explain part of the difference is that in the 2009 matched PUF we are using, there is a total of $5.848 trillion in wages and salaries, whereas in their 2010 economic outlook report, CBO estimates 2009 wages and salaries at $6.329 trillion. So while we use growth rates determined using CBO data, the gap does not close.

So, you are saying that in 2009 before we start any blowup logic, `puf.csv` has $5.848 trillion in wages and salaries while CBO has $6.329 trillion.  That means that before any blowup in the years after 2009 that we are 7.6 percent below the CBO estimate. 

In my experience comparing projections  from different models, this is an **enormous difference**.  Has anyone ever looked into the cause of this difference?  How much confidence do we have in the number of CPS records and those record's earnings we've added to represent non-filers?  How does the 2009 $5.848 compare with other (non-CBO) projections for 2009?  What do historical economic statistics (National Income Accounts, for example) say aggregate earnings were in 2009?  Does SSA have statistics on all earnings in 2009 because they are required to compute the average wage index?

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @zrisher @codykallen

**Comment by Amy-Xu** [comment]
@martinholmer I would like see more specifics from Anderson, but I tried comparing all three sources of historical estimate (not projections) - SOI, CBO and National Income Accounts - they all different from each other at 100+ billion level. I didn't dig into much details, but Alex suggested it might be an issue of wage and salaries definition.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> I would like see more specifics from Anderson, but I tried comparing all three sources of historical estimate (not projections) - SOI, CBO and National Income Accounts - they all different from each other at 100+ billion level. I didn't dig into much details, but Alex suggested it might be an issue of wage and salaries definition.

Thanks for this helpful information.  I can understand definitions causing differences of 100 or 200 billion, but we are looking at a 2009 OSPC-vs-CBO difference of $481 billion.  Seems more than definitional.

@MattHJensen @feenberg @andersonfrailey @GoFroggyRun @zrisher @codykallen

**Comment by codykallen** [comment]
It appears that there is a large, sustained discrepancy in wage and salary data between BEA and the IRS SOi data. The following years have the BEA and SOI total amounts of wage and salary income (in trillions of dollars).

Year     BEA         IRS
2009:   6.251       5.707
2010:   6.378       5.837
2011:   6.633       6.055
2012:   6.930       6.301
2013:   7.117       6.475
2014:   7.476       6.785

This is an average difference of $604 billion, and the gap between the BEA numbers and the IRS numbers is increasing.

**Comment by Amy-Xu** [comment]
@martinholmer 

> I can understand definitions causing differences of 100 or 200 billion, but we are looking at a 2009 OSPC-vs-CBO difference of $481 billion. Seems more than definitional.

I wouldn't say it's OSPC-vs-CBO difference. More precisely, it's SOI-vs-CBO difference if you compare 2009 SOI full file aggregate and CBO 2013 economic projections in which 09 should be historical number already. 

I'm not quite sure I fully understand your logic here, but my intuition is that it is exactly because it is definitional so the difference is this huge -- some items CBO counted as wage and salaries but SOI didn't. If it's accounting errors, then the difference is horrific. It also has nothing to do with modeling assumptions in that they both are historical numbers.

**Comment by feenberg** [comment]
On Thu, 5 Jan 2017, codykallen wrote:

> 
> It appears that there is a large, sustained discrepancy in wage and salary
> data between BEA and the IRS SOi data. The following years have the BEA and
> SOI total amounts of wage and salary income (in trillions of dollars).
> 
> Year BEA IRS
> 2009: 6.251 5.707
> 2010: 6.378 5.837
> 2011: 6.633 6.055
> 2012: 6.930 6.301
> 2013: 7.117 6.475
> 2014: 7.476 6.785
> 
> This is an average difference of $604 billion, and the gap between the BEA
> numbers and the IRS numbers is increasing.

Are these number surprising in the light of

    https://www.bea.gov/scb/pdf/2007/11%20November/1107_pi_agi.pdf


dan

**Comment by martinholmer** [comment]
Thanks for all the comments.  Perhaps I'm confused, but isn't the CBO earnings amount an economy-wide total?  And isn't the IRS-SOI earning amount the earnings among income tax filers only?  If so, comparing those numbers is nonsense.  If my understanding of the scope of the CBO and IRS-SOI statistics is correct, then we probably have too little earnings among the the CPS records that have been added to the IRS-SOI PUF sample.  Please correct me if I have misunderstood the scope of the two statistics.

@MattHJensen @feenberg @Amy-Xu @codykallen @andersonfrailey

**Comment by andersonfrailey** [comment]
@martinholmer you're understanding of the scope of the CBO and IRS-SOI stats is correct and after reading the comments and thinking through it more I agree comparing CBO and IRS-SOI numbers isn't the best strategy.

>  If my understanding of the scope of the CBO and IRS-SOI statistics is correct, then we probably have too little earnings among the the CPS records that have been added to the IRS-SOI PUF sample.

Total wages and salaries for filers in 2014 was $6.784 trillion according to the IRS-SOI data and TaxCalc with the new weights produces $6.819 trillion (up from $6.795 trillion) for filers,  so I believe this diagnosis could be correct because all of the non-filers on the record would be coming from the CPS and they only add $1.3 billion in wages, but I haven't had any luck yet in finding other projections of wages and salaries to explore this further.

**Comment by martinholmer** [comment]
@andersonfrailey responded to my comment as follows:
> You're understanding of the scope of the CBO and IRS-SOI stats is correct and after reading the comments and thinking through it more I agree comparing CBO and IRS-SOI numbers isn't the best strategy.
>
>> If my understanding of the scope of the CBO and IRS-SOI statistics is correct, then we probably have too little earnings among the the CPS records that have been added to the IRS-SOI PUF sample.
>
> Total wages and salaries for filers in 2014 was $6.784 trillion according to the IRS-SOI data and TaxCalc with the new weights produces $6.819 trillion (up from $6.795 trillion) for filers, so I believe this diagnosis could be correct because all of the non-filers on the record would be coming from the CPS and they only add $1.3 billion in wages, but I haven't had any luck yet in finding other projections of wages and salaries to explore this further.

Thanks for the useful 2014 statistics on earnings for those who file an income tax return.  We are very close to the actual 2014 IRS numbers: the new weights imply a filer earnings total that is only 0.5 percent above the IRS number you quote.

Earlier in this conversation, you mentioned a CBO earnings total.  I've been assuming that this total is for **all earners** whether or not they file an income tax return.  Is that assumption correct?
If correct then my earlier statement, is correct (right?):

> So, you are saying that in 2009 before we start any blowup logic, `puf.csv` has $5.848 trillion in wages and salaries while CBO has $6.329 trillion. That means that before any blowup in the years after 2009 that we are 7.6 percent below the CBO number.

Now we see that more than all of this total earnings underestimate is caused by the fact that the CPS records in the `puf.csv` file have earnings far below what CBO thinks non-filers have.  Which means we need to review how these added CPS records have been selected.  If we want to be in line with CBO, then we need to fix the massive understatement of non-filer earnings in the `puf.csv` file.

Does this seems like the correct way to frame this issue?

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @zrisher @codykallen

**Comment by andersonfrailey** [comment]
@martinholmer asked:
> I've been assuming that this total is for all earners whether or not they file an income tax return. Is that assumption correct?

This is correct. From page 46 of CBO's [budget and economic outlook](https://www.cbo.gov/sites/default/files/114th-congress-2015-2016/reports/51908-2016outlookupdateonecol-2.pdf):

> Economic activity and  tax revenues depend on aggregate income... and on its distribution among various categories... CBO therefore projects income in those categories over the next 10 years, estimating each categories share of gross domestic income.

This statement is also correct:

>So, you are saying that in 2009 before we start any blowup logic, puf.csv has $5.848 trillion in wages and salaries while CBO has $6.329 trillion. That means that before any blowup in the years after 2009 that we are 7.6 percent below the CBO number.

With regards to this:

> If we want to be in line with CBO, then we need to fix the massive understatement of non-filer earnings in the `puf.csv` file.

This is how I am understanding the issue. I'd like to talk to John to get his opinion as well, but yes, I believe it is possible the earnings of non-filers are being understated in the puf and we should look into ways to increase them.

**Comment by MattHJensen** [comment]
This table from TPC may be relevant: http://www.taxpolicycenter.org/statistics/salary-and-wages

image

**Comment by martinholmer** [comment]
@MattHJensen said:
> This table from TPC may be relevant: http://www.taxpolicycenter.org/statistics/salary-and-wages

How is this table relevant?  Unless I'm confused this table includes only those who file an income tax return.  @andersonfrailey and I are now in agreement that the `puf.csv` underestimate of economy-wide earnings is caused exclusively by an underestimate of earnings among people who do not file an income tax return.

**Comment by feenberg** [comment]
On Mon, 9 Jan 2017, andersonfrailey wrote:

> 
> @martinholmer asked:
>
>       I've been assuming that this total is for all earners whether or
>       not they file an income tax return. Is that assumption correct?
> 
> This is correct. From page 46 of CBO's budget and economic outlook:
>
>       Economic activity and tax revenues depend on aggregate income...
>       and on its distribution among various categories... CBO
>       therefore projects income in those categories over the next 10
>       years, estimating each categories share of gross domestic
>       income.
> 
> This statement is also correct:
>
>       So, you are saying that in 2009 before we start any blowup
>       logic, puf.csv has $5.848 trillion in wages and salaries while
>       CBO has $6.329 trillion. That means that before any blowup in
>       the years after 2009 that we are 7.6 percent below the CBO
>       number.
> 
> With regards to this:
>
>       If we want to be in line with CBO, then we need to fix the
>       massive understatement of non-filer earnings in the puf.csv
>       file.
> 
> This is how I am understanding the issue. I'd like to talk to John to get
> his opinion as well, but yes, I believe it is possible the earnings of
> non-filers are being understated in the puf and we should look into ways to
> increase them.
>

Whatever the problem is, I don't think that non-filers are a very big part 
of it. Looking at

   https://www.bea.gov/scb/pdf/2007/11%20November/1107_pi_agi.pdf

back in 2005 non-filer wages are a portion of line 9 under the heading 
"Wage and salary disbursements" That cell is 149b out of a total of 5667b, 
or about 3% of total wages. According to text 89% of wage and salary 
misreporting addjustment was do to "filer adjustments". So portion of the 
149b due to non-filers is very small.

I don't really understand what is going on here. Is it the case that we 
are trying to bridge the gap between SOI and CBO wages entirely on backs 
of non-filers? That doesn't seem likely at all.

dan feenberg

**Comment by martinholmer** [comment]
@feenberg said:
> I don't really understand what is going on here.  Is it the case that we are trying to bridge the gap between SOI and CBO wages entirely on backs of non-filers? That doesn't seem likely at all.

Maybe not, but what do you make of this finding reported by @andersonfrailey?
> Total wages and salaries for filers in 2014 was $6.784 trillion according to the IRS-SOI data and TaxCalc with the new weights produces $6.819 trillion (up from $6.795 trillion) for filers, so I believe this diagnosis could be correct because all of the non-filers on the record would be coming from the CPS and they only add $1.3 billion in wages, but I haven't had any luck yet in finding other projections of wages and salaries to explore this further.

So, according to @andersonfrailey, non-filers have hardly any earnings in the `puf.csv` file:  $1.3 **billion** is a tiny fraction of $6.819 **trillion**.

@MattHJensen @Amy-Xu

**Comment by feenberg** [comment]
On Mon, 9 Jan 2017, Martin Holmer wrote:

> 
> @MattHJensen said:
>
>       This table from TPC may be relevant:
>       http://www.taxpolicycenter.org/statistics/salary-and-wages
> 
> How is this table relevant? Unless I'm confused this table includes only
> those who file an income tax return. @andersonfrailey and I are now in
> agreement that the puf.csv underestimate of economy-wide earnings is caused
> exclusively by an underestimate of earnings among people who do not file an
> income tax return.

I know you agree, but what is the argument for that position?

dan feenberg

**Comment by feenberg** [comment]
On Mon, 9 Jan 2017, Martin Holmer wrote:

> 
> @feenberg said:
>
>       I don't really understand what is going on here. Is it the case
>       that we are trying to bridge the gap between SOI and CBO wages
>       entirely on backs of non-filers? That doesn't seem likely at
>       all.
> 
> Maybe not, but what do you make of this finding reported by
> @andersonfrailey?
>
>       Total wages and salaries for filers in 2014 was $6.784 trillion
>       according to the IRS-SOI data and TaxCalc with the new weights
>       produces $6.819 trillion (up from $6.795 trillion) for filers,

>       so I believe this diagnosis could be correct because all of the
>       non-filers on the record would be coming from the CPS and they
>       only add $1.3 billion in wages, but I haven't had any luck yet
>       in finding other projections of wages and salaries to explore
>       this further.
> 
> So, according to @andersonfrailey, non-filers have hardly any earnings in
> the puf.csv file: $1.3 billion is a tiny fraction of $6.819 trillion.

So the difference to be explained is $3b? Why is that amount interesting? 
Why do we compare 1.3b to 6.819t? Why not compare 1.3b to 3b? Doesn't the 
CPS omit the institutionalized population? Could those people have 1.7b in 
wages?


dan

**Comment by martinholmer** [comment]
@feenberg said:
> So the difference to be explained is $3b?  Why is that amount interesting?  Why do we compare 1.3b to 6.819t? Why not compare 1.3b to 3b? 

Sorry, Dan, but I'm not understanding your questions.  What does the $3 billion refer to?

**Comment by feenberg** [comment]
On Mon, 9 Jan 2017, Martin Holmer wrote:

> 
> @feenberg said:
>
>       So the difference to be explained is $3b? Why is that amount
>       interesting? Why do we compare 1.3b to 6.819t? Why not compare
>       1.3b to 3b?
> 
> Sorry, Dan, but I'm not understanding your questions. What does the $3
> billion refer to?

Sorry, $6.819-$6.784 trillion is 25 billion. I am off by an order of 
magnitude.

Still, if the BLS reconciliation says that 11% of 149b is non-filer 
earnings for 2005, the overall descrepancy doesn't seem to be "material", 
and ascribing it all to CPS persons probably isn't justified.

If the discussion is to be pursued, the first place to look is "what are 
the criteria for classifying a person as a non-filer in the CPS"? Is it 
possible that NIPA includes income from illegal activities of non-filers 
(some of whom are obliged to file, but ignore the law) and we do not?


dan

**Comment by martinholmer** [comment]
@feenberg said:
> Sorry, $6.819-$6.784 trillion is 25 billion.

But more importantly, you seem to have missed this earlier finding in the #1105 conversation:
> So, [@andersonfrailey] you are saying that in 2009 before we start any blowup logic, `puf.csv` has $5.848 trillion in wages and salaries while CBO has $6.329 trillion. That means that before any blowup in the years after 2009 that we are 7.6 percent below the CBO number [for all earners].

So, Dan, the 2009 pre-blowup gap in earnings is 6.329 minus 5.848, which is $481 billion or a 7.6 percent difference.  Given that @andersonfrailey has found the 2014 earnings for **filers** in the `puf.csv` file and in the SOI 2014 aggregate tabulations for filers are very close, the simple logic of the matter would seem to point to non-filers as the cause of the massive overall earnings underestimate in the `puf.csv` file.

@MattHJensen @Amy-Xu @GoFroggyRun @zrisher @codykallen

**Comment by feenberg** [comment]
On Mon, 9 Jan 2017, Martin Holmer wrote:

> 
> @feenberg said:
>
>       Sorry, $6.819-$6.784 trillion is 25 billion.
> 
> But more importantly, you seem to have missed this earlier finding in the #1105
> conversation:
>
>       So, [@andersonfrailey] you are saying that in 2009 before we start any
>       blowup logic, puf.csv has $5.848 trillion in wages and salaries while CBO
>       has $6.329 trillion. That means that before any blowup in the years after
>       2009 that we are 7.6 percent below the CBO number [for all earners].
> 
> So, Dan, the 2009 pre-blowup gap in earnings is 6.329 minus 5.848, which is $481
> billion or a 7.6 percent difference. Given that @andersonfrailey has found the 2014

The last AGI-NIPA reconciliation I can find is for 2005:

    https://www.bea.gov/scb/pdf/2007/11%20November/1107_pi_agi.pdf

and it "explains" a gap of 149b between NIPA and SOI wages. That is only a 
third of the comparison to CBO, but it does raise the question of how does 
CBO explain their deviation from SOI? I wonder if the difference is in 
the treatment of proprietor's income. I CBO alocates some of that to 
wages, and some to capital, but the SOI allocates all to business.

dan

**Comment by MattHJensen** [comment]
Given that it looks like: 

1. We know this PR contains useful updates. 
2. While reviewing this PR, we've begun to suspect that both before and after this PR we aren't picking up enough wages and salaries from the CPS match or elsewhere. 

I propose that @andersonfrailey opens a separate issue in TaxData with the key information for discussion the second point. 

In the meantime, we can move forward w this PR. 

Does that make sense to others?

**Comment by andersonfrailey** [comment]
I'm on board with @MattHJensen 's suggestions. I can aggregate the main points made in this PR regarding point 2 in his post and open up an issue.

In the meantime I've solved the merge conflict for this PR and run all of the tests in the [testing procedures](https://github.com/open-source-economics/Tax-Calculator/blob/master/TESTING.md).

**Comment by martinholmer** [comment]
@andersonfrailey said:
> In the meantime I've solved the merge conflict for this PR and run all of the tests in the testing procedures.

You may have resolved the merge conflict with respect to #1105, but the tests don't pass on my computer.  Here is what happens when I download your pull request and run the tests:
```
E           ValueError: PUFCSV MTR RESULTS DIFFER
E           -------------------------------------------------
E           --- NEW RESULTS IN pufcsv_mtr_actual.txt FILE ---
E           --- if new OK, copy pufcsv_mtr_actual.txt to  ---
E           ---                 pufcsv_mtr_expect.txt     ---
E           ---            and rerun test.                ---
E           -------------------------------------------------

tests/test_pufcsv.py:227: ValueError
----------------------------- Captured stdout call -----------------------------
You loaded data for 2009.
Your data have been extrapolated to 2013.
==================== 1 failed, 309 passed in 239.76 seconds ====================
```
When I compare the actual mtr test results with the contents of the `pufcsv_mtr_expect.txt` file that is in your pull request #1105, I get these differences:
```
iMac2:tests mrh$ diff pufcsv_mtr_actual.txt pufcsv_mtr_expect.txt
51,54c51
< 219814 :      0      0      0      0  53480  69398  46183  28411  21647    695
< PTAX and ITAX mtr histogram bin counts for e19800:
< 219814 : 219814      0      0      0      0      0      0      0      0      0
< 219814 :  33314  29291  18172   5035 134002      0      0      0      0      0
---
> 219814 :      0      0      0      0  53480  69398  46183  28411  21647    695
\ No newline at end of file
```
My guess is that the master branch on your computer is very much out-of-date because the test results for the mtr wrt `e19800` were added by @codykallen in commit 58785b on Dec 14, 2016.  Am I right that you've not updated the master branch on your computer for over a month?

We can't merge your pull request #1105 until this problem gets fixed.

**Comment by andersonfrailey** [comment]
@martinholmer my mistake. It didn't occur to me to make sure this branch was up-to-date before running all the tests. I've updated and re-run the tests.

**Comment by martinholmer** [comment]
@andersonfrailey, Thanks for all the good work updating the blowup/weighting factors!
Merging #1105 now per @MattHJensen plan.

@feenberg @Amy-Xu @GoFroggyRun @zrisher @codykallen

**Comment by martinholmer** [comment]
@MattHJensen said in the conversation of pull request #1105:
> Given that it looks like:
>
> (1) We know this PR [#1105] contains useful updates.
>
> (2) While reviewing this PR, we've begun to suspect that both before and after this PR we aren't picking up enough wages and salaries from the CPS match or elsewhere.
>
> I propose that @andersonfrailey opens a separate issue in TaxData with the key information for discussing the second point.
>
> In the meantime, we can move forward w this PR [which was merged into taxcalc master].

In response, @andersonfrailey said:
> I'm on board with @MattHJensen 's suggestions. I can aggregate the main points made in this PR regarding point 2 in his post and open up an issue.

@andersonfrailey,  Where is that new issue?

**Comment by andersonfrailey** [comment]
@martinholmer it is on my to-do list. Some of my other work has taken longer than I expected and it slipped off my radar. I'll set aside some time today to get it up. Sorry about the delay.

**Pull request merged**
