### PR TITLE
Add support for numpy v1.10

### PR DESCRIPTION
**Pull request by talumbau**
I don't know if this is too "ugly" of a fix. I should probably also show the distribution tables for master and this branch as a double check that the math hasn't changed.

### CODE REVIEW

**Comment by talumbau** [comment]
Actually, I ran `test.py` with the latest PUF for this branch (with numpy 1.10 and numba 0.22 for numpy 1.10) and against master (with numpy 1.9.3 and numba 0.22 for numpy 1.9.3) and got the exact same results. Therefore, if this change is stylistically acceptable, it is good to be merged.

**Comment by talumbau** [comment]
cc @Amy-Xu @MattHJensen. The urgency on this is not high yet, but in terms of integrating the micro/macro calculations, I think the best case scenario for deployment is to support numpy v1.10. Therefore, we should have a solution of some kind ready to go, if not the solution I propose in this PR.

**Comment by MattHJensen** [comment]
I must admit that I haven't completely kept up with this issue. Could you let us know why the proposed solution is preferred:

    self.e00200 = self.e00200 + self.e00200*self.BF.AWAGE[year]

**Comment by talumbau** [comment]
I think you mean:

```
self.e00200 = self.e00200*self.BF.AWAGE[year]
```

correct? Assuming that's what you meant, there are two differences between:

```
self.e00200 = self.e00200*self.BF.AWAGE[year]
```

and

```
a = self.e00200
b = self.BF.AWAGE[year]
np.multiply(a, b, out=a, casting='unsafe')
```

1. if `e00200` has a dtype in the `int` family (e.g. `int64`), which is the case upon first reading in the PUF, the second style retains the `int64` dtype, whereas the first calculation would product a new array with a floating point dtype, and that new array would be assigned to the attribute `e00200` on `self`.

2. (I think this one is more important) There are some values that are 'aliased', so two attributes that refer to the same value. If you use the first style above, the aliasing would be broken, because a new value is created and then assigned as an attribute. If you use the second style, the aliasing remains intact. I can't remember which values @Amy-Xu was concerned about in regards to the aliasing, but this was the original motivation to begin writing the operations as `a *= b`.

**Comment by MattHJensen** [comment]
> I think you mean:
> self.e00200 = self.e00200*self.BF.AWAGE[year]

Yes. That's what I meant. 

>  the first calculation would produce a new array with a floating point dtype, and that new array would be assigned to the attribute e00200 on self.

This is actually somewhat preferred because of https://github.com/open-source-economics/Tax-Calculator/issues/397#issuecomment-148507440.

> If you use the second style, the aliasing remains intact. I can't remember which values @Amy-Xu was concerned about in regards to the aliasing, but this was the original motivation to begin writing the operations as a *= b. 

Ahhh, yes, this does seem more important than the previous point. 

-----

I suppose it is worth adding that if anything happens with #436, this issue will be revisited in the taxdata repo.

**Comment by talumbau** [comment]
Seems like we do have competing concerns here. As we are building toward the microsim-dynamic model integration, the easiest thing from a deployment perspective is to move to numpy 1.10 for everything. I can work around this, but if we can live with the changes in this PR, it will make things easier. One thing is that the change is fairly localized, so one wouldn't have to look very hard for all of the occurrences of the issue if a different technique was desired later on.

**Comment by MattHJensen** [comment]
I'm fine proceeding with this approach. We'll have an opportunity to revisit later during potential work on #436. 

@Amy-Xu, could you look this over and merge if it looks good to you?

**Comment by Amy-Xu** [comment]
@talumbau I was concerned about p23250 and e23250 and just checked they are the same in this PR. Looks good to me. Merging.

Thanks @talumbau @MattHJensen

**Pull request merged**
