### PR TITLE
Add TCJA Senate chairman modified mark reform file

### PR DESCRIPTION
**Pull request by GoFroggyRun**
The reform file is for the TCJA Senate Chairman Modified Mark as of 11-14-17. Since most provisions will expire after 2025, I used values that are under the chained CPI inflation when retaining them. These values are rounded to nearest $50. 

@martinholmer @MattHJensen @codykallen @evtedeschi3

### CODE REVIEW

**Comment by MattHJensen** [comment]
@GoFroggyRun, I suggest dropping the $50 rounding -- I don't think those are exactly what IRS uses, and since we don't use the exact rounding rules in Tax-Calculator, there's no reason to give the appearance of using them here.

**Comment by GoFroggyRun** [comment]
@MattHJensen so you are suggesting adopting the inflated values without rounding, right?

**Comment by MattHJensen** [comment]
> so adopting the inflated values without rounding, right? 

Right. Just round to the dollar.

**Comment by martinholmer** [comment]
@GoFroggyRun,  Please keep with the naming conventions for all the TCJA reform files.  Your proposed file in #1678 doesn't indicate whether its House or Senate.   Things are complicated enough without confusing file names.  Can you change this now?

**Comment by martinholmer** [comment]
@GoFroggyRun, Why not use the new `_cpi_offset` variable in the JSON reform file?

**Comment by GoFroggyRun** [comment]
@martinholmer said: 
>Your proposed file in #1678 doesn't indicate whether its House or Senate.

Thanks for noticing. How does the name look right now. 

@martinholmer also said: 
>Why not use the new _cpi_offset variable in the JSON reform file?

Ahh. This variable wasn't quite there when I was preparing the PR. I have added it to the reform now.

**Comment by martinholmer** [comment]
@GoFroggyRun,  Thanks for the rename and use of `_cpi_offset`, but I have a question.  Perhaps I don't understand the details of the bill, but if the "reform goes away" beginning in 2026, then shouldn't the chained CPI indexing also go away?  If so, shouldn't the `_cpi_offset` line in the JSON file be like this?
```
        "_cpi_offset": {"2018": [-0.0025], "2026": [0.0]},
```
@MattHJensen @codykallen

**Comment by MattHJensen** [comment]
(Hoping to have a review of this by @codykallen before it is merged since his name is on it alongside Sean's.)

**Comment by martinholmer** [comment]
@MattHJensen said in #1678:
> Hoping to have a review of this by @codykallen before it is merged since his name is on it alongside Sean's.

And, in addition, shouldn't the name of the JSON file be changed to conform to your naming scheme?

@GoFroggyRun

**Comment by codykallen** [comment]
@martinholmer asked

> Perhaps I don't understand the details of the bill, but if the "reform goes away" beginning in 2026, then shouldn't the chained CPI indexing also go away? If so, shouldn't the _cpi_offset line in the JSON file be like this?

According to the text of the modified Chairman's mark: 

> Under the modification, all of the proposals contained in Title I will expire after December 31, 2025. This does not apply to the proposal that requires the use of the chained CPI-U (“C-CPI-U”) to index tax parameters currently indexed by the CPI-U. 

So the chained CPI indexing does not go away after a decade.

**Comment by codykallen** [comment]
@GoFroggyRun, @MattHJensen, this seems fine to me.

**Comment by martinholmer** [comment]
@codykallen said:
> According to the text of the modified Chairman's mark:
>
>> Under the modification, all of the proposals contained in Title I will expire after December 31, 2025. This does not apply to the proposal that requires the use of the chained CPI-U (“C-CPI-U”) to index tax parameters currently indexed by the CPI-U.
>
> So the chained CPI indexing does not go away after a decade. 

Thanks for the clarification.

**Comment by martinholmer** [comment]
@GoFroggyRun,  So looks like we can merge this after you change the file name to `TCJA_Senate_111417.json`.

**Comment by MattHJensen** [comment]
It would be helpful to add a note somewhere that explains that we do not apply the IRS rounding rules to the 2026 parameters.

**Comment by GoFroggyRun** [comment]
Thanks @MattHJensen @martinholmer and @codykallen for all your inputs. 

@martinholmer this PR should be good to go. Could you review?

**Comment by evtedeschi3** [comment]
I'm getting a series of "> max" errors for `_II_brk2_4` & `_II_brk3_4` in 2026 & 2027 using this file that prevent a run.

**Comment by martinholmer** [comment]
@GoFroggyRun,  As the author of pull request #1678, it's **your responsibility to test** the submission.
If you had done that, you would have discovered your mistakes (as @evtedeschi3 already did).   Here's a list of the things I've noticed that are wrong with this JSON reform file:

- no mention of chained CPI indexing reform provision in either the Reform_Description section or in the Reform_Parameter_Map section.

- illegal values for the `_II_brk2/3` and `_PT_brk2/3` policy parameters

Here is what @evtedeschi3 was talking about when he tried to use this JSON reform file with taxcalc 0.13.2:
```
$ conda list taxcalc
# packages in environment at /Users/mrh/anaconda2:
#
taxcalc                   0.13.2                   py27_0    ospc

$ tc cps.csv 2018 --reform TCJA_Senate_111417.json 
ERROR: 2026 _II_brk2_4 value 91502.0 > max value 84571.0 for _II_brk3_4
ERROR: 2027 _II_brk2_4 value 93469.29 > max value 86389.28 for _II_brk3_4
ERROR: 2026 _II_brk3_4 value 84571.0 < min value 91502.0 for _II_brk2_4
ERROR: 2027 _II_brk3_4 value 86389.28 < min value 93469.29 for _II_brk2_4
ERROR: 2026 _PT_brk2_4 value 91502.0 > max value 84571.0 for _PT_brk3_4
ERROR: 2027 _PT_brk2_4 value 93469.29 > max value 86389.28 for _PT_brk3_4
ERROR: 2026 _PT_brk3_4 value 84571.0 < min value 91502.0 for _PT_brk2_4
ERROR: 2027 _PT_brk3_4 value 86389.28 < min value 93469.29 for _PT_brk2_4
USAGE: tc --help

$
```
So, it is not really true that `this PR should be good to go`, as you said.

You need to test your pull requests, which, in the case of adding a new JSON reform file, means checking that it is a valid reform.  The first thing users are going to do is something like this:
```
tc cps.csv 2018 --reform new_reform.json
```
So the person proposing `new_reform.json` for inclusion in the  repository needs to make sure it's a valid reform.

**Comment by codykallen** [comment]
@evtedeschi3 found an error:

> I'm getting a series of "> max" errors for _II_brk2_4 & _II_brk3_4 in 2026 & 2027 using this file that prevent a run.

It appears that the value for the entry for qualifying widows in `_II_brk3` and `_PT_brk3` is incorrectly specified for 2026 as 84571 instead of 184571. Because this is less than the value of `_II_brk2` and `_PT_brk2` for 2026 for qualifying widows (91502), this produces the error shown above.

**Comment by GoFroggyRun** [comment]
Thanks @martinholmer and @evtedeschi3 for your inputs. I realized that there're a few 1s missing, making the reform file invalid. Fixes have been made in the most recent commit. 

The strange thing is, when I was using the old file (that is the file pre commit [bac4c62](https://github.com/open-source-economics/Tax-Calculator/pull/1678/commits/bac4c62d73f82f4bed5b52e839baad3b7186f4db)), the tax calculator doesn't stop me from implementing the reform. See the screenshot below: 

screen shot 2017-11-18 at 5 19 17 pm

No error message occurred when this reform is implemented. The fifth item in `_II_brk2` is larger than the fifth item in `_II_brk3`, which is why @evtedeschi3's having the error message.

**Comment by martinholmer** [comment]
@GoFroggyRun said:
> No error message occurred when this reform is implemented. 

What actually happened is that you didn't bother to check for an error message after you called `implement_reform`.
```
print policy_reform.reform_errors
```
would have shown you exactly what @evtedeschi3 saw when he used the CLI.

**Comment by GoFroggyRun** [comment]
@martinholmer Sorry. My bad. I wasn't expecting the errors to be stored in `reform_errors`.

**Comment by GoFroggyRun** [comment]
After taking another look at this PR. I have one last concern regarding what year should the `_cpi_offset` be set.

If we do `"2018": [-0.0025]` for `_cpi_offset`, then the result would look like the following:

screen shot 2017-11-21 at 3 21 06 pm

Instead, `"2017": [-0.0025]` would yield something like:

screen shot 2017-11-21 at 3 21 31 pm

Here the base calculator stands for standard indexing, while the reform stands for chained CPI one. And the first row represents values for year 2017.

When the start year is set to '2018', those chained CPI values won't be different from "standard" indexed figures until 2019. So, if we were to adopt chained CPI inflation starting year 2018, we would have to set the `_cpi_offset` parameter to desired value starting in year 2017? 

I am not quite familiar with the indexing process. So before making changes to the file (change `_cpi_offset` reform to start in year 2017), I'd like to make sure this is the way how (chained) CPI indexing supposed to work. 

@MattHJensen @martinholmer @codykallen @andersonfrailey

**Comment by MattHJensen** [comment]
@GoFroggyRun, I recommend setting the _cpi_offset in 2017. (See further discussion in https://github.com/open-source-economics/Tax-Calculator/issues/1687)

**Comment by MattHJensen** [comment]
@GoFroggyRun, I also recommend adding `DependentCredit_before_CTC` to this PR

**Comment by GoFroggyRun** [comment]
@MattHJensen thanks for the suggestions. This PR is ready for review.

**Pull request merged**
