### PR TITLE
Add FHEADIDX to CPS

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR complements TaxData PR [#136](https://github.com/open-source-economics/taxdata/pull/136). It adds the `fheadidx` variable to the CPS file, as requested by @evtedeschi3 and @MattHJensen.

### CODE REVIEW

**Comment by martinholmer** [comment]
@andersonfrailey,  I'm not very knowledgeable about the CPS, but shouldn't this description
```
"desc": "Index to persons record of family reference person",
```
be like this?
```
"desc": "Index to person record of family reference person",
```
It's the family reference person's `person record` your pointing to, right?

**Comment by andersonfrailey** [comment]
@martinholmer, you're correct that it is pointing to the person record of the family reference person. The CPS documentation uses both "index to persons record of family reference person" and "index to person record of family head." I'm indifferent to which we use, but I think we should stick to one of the conventions used in the official CPS documentation.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> you're correct that it is pointing to the person record of the family reference person. The CPS documentation uses both "index to persons record of family reference person" and "index to person record of family head." I'm indifferent to which we use, but I think we should stick to one of the conventions used in the official CPS documentation.

It seems to me that "index to person record of family head" is better English.  It's a record for a person, not a record for persons (that's the family record, right?).

**Comment by andersonfrailey** [comment]
@martinholmer, I agree that it's better English. The CPS documentation uses both "person" and "persons" so I don't think which one we choose will make much of a difference. I can change the spelling in my next commit.

**Comment by MattHJensen** [comment]
@evtedeschi3, does this look like what you need?

**Comment by evtedeschi3** [comment]
I’m still not clear on why PULINENO isn’t possible, but if this is the most detail available it will certainly help with CPS matching.

**Comment by martinholmer** [comment]
@andersonfrailey, Why are you adding a variable that was not requested?

**Comment by andersonfrailey** [comment]
`PULINEO` is not listed in the [CPS documentation](http://www.nber.org/cps/cpsmar2014.pdf).

@evtedeschi3 is it possible that `A_LINENO` is the variable you're looking for? It's listed under the person record variables as simply described as "line number". I looked at the raw data and it ranges from 1 to 16. It's possible that it refers to what line in the family or household a record is from.

**Comment by martinholmer** [comment]
There has been an upgrade in both the CPS file and the PUF file used as Tax-Calculator input data since this pull request was opened.  So, I'm assuming that the initiative in #1750 is now moot.  If not, then a new pull request can be opened.

**Pull request closed without merging**
