### PR TITLE
Add test that shows bug in GainsTax function and fix bug

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request adds a test to illustrate a bug in the GainsTax function and then fixes that bug.  This bug was reported by @codykallen in issue #977.  The fix for this bug in this pull request is logically equivalent to the code revision suggested by @codykallen in pull request #979, but eliminates the duplication of code inherent in #979.  Thank you, @codykallen, for your helpful bug report in #977 and your correct diagnosis of the bug's cause in #979.

As an aside for other Tax-Calculator contributors, the bug report in #977 is an example to be emulated: it describes the problem and provides a simple test to demonstrate the problem.  #979 goes the extra mile by actually suggesting how to fix the bug reported in #977.

What I have done in this pull request is two things:
(1) created a new unit test based on the bug report in #977, and
(2) fixed the bug (that is, revised the code so that the new test does not fail).

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @zrisher

### CODE REVIEW

**Comment by martinholmer** [comment]
Before the bug-fix code change in the `functions.py` file, the result of the new `test_Calculator_mtr_when_PT_rates_differ` test were as follows:
```
>       assert np.allclose(mtr1, mtr2, rtol=0.0, atol=1e-06)
E       assert <function allclose at 0x102f93410>(array([ 0.188]), array([ 0.438]), rtol=0.0, atol=1e-06)
E        +  where <function allclose at 0x102f93410> = np.allclose
```
So, before the bug fix, the marginal tax rate on LTCG (`p23250`) was different before and after the reform that made pass-through tax rates different from tax rates on non-pass-through income: instead of being the same the mtr on LTCG was 0.188 (the 15% CG rate plus the 3.8% NIIT rate) when II and PT tax rates were identical and 0.438 (the 40% II rate plus the 3.8% NIIT rate) after the reform that made all II rates equal to 40% and all PT rates equal to 30%.

After the bug fix, the mtr on LTCG is 0.188 both before and after the reform that makes II and PT rates different.

@MattHJensen @feenberg @Amy-Xu @GoFroggyRun @andersonfrailey @zrisher

**Comment by MattHJensen** [comment]
@martinholmer, this looks good to me. @codykallen, thanks a lot for the bug report and suggested fix! 

@martinholmer, do you think it is ok to merge this now? I think it deserves a TC version bump and redeploy to TaxBrain asap given that I know there are currently users on TB who would be affected. 

cc @talumbau

**Comment by martinholmer** [comment]
@MattHJensen said:
> @martinholmer, this [#981] looks good to me. @codykallen, thanks a lot for the bug report and suggested fix!
>
> @martinholmer, do you think it is ok to merge this now? I think it deserves a TC version bump and redeploy to TaxBrain asap given that I know there are currently users on TB who would be affected.

Yes, I'm comfortable with the changes in pull request #981, but was hoping to get a thumbs up from @codykallen before doing the merge.  But I haven't heard anything from his this morning.

**Comment by martinholmer** [comment]
Merged pull request #981 resolves issue #977 and incorporates the bug-fix strategy (but not tactics) of pull request #979.

**Pull request merged**
