### PR TITLE
Add scripts to automate version and release

### PR DESCRIPTION
**Pull request by talumbau**
This pull requests adds two BASH scripts that aid in the versioning and release of `taxcalc`. The scripts accomplish the following goals:

1. Add a version "tag" to the GitHub repo for the release number
2. Package and upload the code to PyPI so that one can `pip install` taxcalc
3. Build and upload packages to anaconda.org so that taxcalc can be downloaded through `conda install`.

### CODE REVIEW

**Comment by martinholmer** [comment]
T.J.,
I don't understand the purpose of pull request #602, "Add scripts to automate version and release."
What are you automating?
Are you automating things related to the **first way** or the **third way** of [Getting Started](http://github.com/open-source-economics/Tax-Calculator#getting-started)?

cc @MattHJensen @talumbau

**Comment by talumbau** [comment]
These scripts are the answer to the question, "How does one create a new version and release of the `taxcalc` package?" The answer is basically "execute `version_and_release.sh` and then `upload.sh`" with the desired release tag. These scripts automate the process of creating a tagging a new version and releasing it on PyPI and anaconda.org. There is some additional documentation to do here to explain what to do, so I'm marking this as WIP and will add additional commits.

**Comment by martinholmer** [comment]
T.J. said:
> These scripts are the answer to the question, "How does one create a new version and release of the taxcalc package?" The answer is basically "execute version_and_release.sh and then upload.sh" with the desired release tag. These scripts automate the process of tagging a new version and releasing it on PyPI and anaconda.org. There is some additional documentation to do here to explain what to do, so I'm marking this as WIP and will add additional commits.

So, I'm still guessing because you didn't answer my question, but it sounds as if you are automating the **third way** of [Getting Started](https://github.com/open-source-economics/Tax-Calculator#getting-started), is that right?  So, pull request #602 has nothing to do with the **first way** of [Getting Started](https://github.com/open-source-economics/Tax-Calculator#getting-started), is that right?

**Comment by talumbau** [comment]
Oh I see. I'll be more clear. These scripts are not involved in any of the methods for "Getting Started" listed at that link. I suppose it's most closely related to the "third way" in that link, but I've never really understood or agreed with the verbiage of that section, but it seemed like a minor issue and it hasn't really prohibited anyone from moving forward with contributing to the package. It's related to the second in the sense that TaxBrain uses particular releases of taxcalc. But to directly answer your queries, these scripts have nothing to do with the first way of getting started.

**Comment by talumbau** [comment]
I have added a Wiki page here to describe the purpose behind these scripts. It might make more sense to put these scripts somewhere other than at the top of the repository, inside `doc/` or perhaps create a new directory called `dist/`.

https://github.com/open-source-economics/Tax-Calculator/wiki/How-to-create-and-release-a-new-version-of-Tax-Calculator

**Comment by talumbau** [comment]
I removed the `[WIP]` as I think with the new wiki documentation this can be merged. Thoughts on the location of the scripts?

**Comment by MattHJensen** [comment]
@talumbau, creating a `dist/` directory makes sense to me. 

Anyone else have views on this?

**Comment by talumbau** [comment]
ok I will push another commit here that moves the scripts to a new top-level directory called `dist/`

**Comment by MattHJensen** [comment]
@talumbau said: ok I will push another commit here that moves the scripts to a new top-level directory called `dist/`

Thanks @talumbau. @martinholmer, do you have any remaining questions about this PR after that change is made?

**Comment by martinholmer** [comment]
@MattHJensen said:
>>@talumbau said: ok I will push another commit here that moves the scripts to a new top-level directory called dist/
>
>Thanks @talumbau. @martinholmer, do you have any remaining questions about this PR after that change is made?

I have no more questions.

**Comment by MattHJensen** [comment]
Ok. Thanks @martinholmer. @talumbau, why don't you go ahead and merge whenever it is ready.

**Comment by talumbau** [comment]
@MattHJensen @martinholmer I moved the scripts to `distribution/` because `dist/` is in the `.gitignore` which is probably correct because the built-in Python build/release tools will store a version of a release in this folder. Better to use something like `distribution/` so it will not be confused.

**Pull request merged**
