### PR TITLE
Replace StageIFactors.csv with growfactors.csv and simplify logic

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request simplifies Tax-Calculator logic by moving data-preparation work from Tax-Calculator code (where is executes every time Tax-Calculator is run) to the taxdata code (where it is executed just once).  The forthcoming change in taxdata logic is described in [taxdata issue 60](https://github.com/open-source-economics/taxdata/issues/60).  The desirability of moving this data-preparation code into the taxdata repo (where it logically belongs) was identified in issue #1175.

These changes cause minor differences in some tax results (even with the new `grow_factors.csv` file containing rates that are expressed with six decimal places of precision).  For example, in 2022 income taxes are now $2033.2 billion, which is up from $2032.7 billion, a rise of $0.5 billion, which is an increase of about one-fourth of one-tenth of a percent.  There is no change in the payroll tax total for any year in the 2013-2022 period.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey @GoFroggyRun @codykallen

### CODE REVIEW

**Comment by MattHJensen** [comment]
> These changes cause minor differences in some tax results (even with the new puf_factors.csv file containing rates that are expressed with six decimal places of precision). For example, in 2022 income taxes are now $2033.2 billion, which is up from $2032.7 billion, a rise of $0.5 billion, which is an increase of about one-fourth of one-tenth of a percent. There is no change in the payroll tax total for any year in the 2013-2022 period.

@martinholmer, why does this change influence results?

**Comment by martinholmer** [comment]
@martinholmer said:
> These changes cause minor differences in some tax results (even with the new puf_factors.csv file containing rates that are expressed with six decimal places of precision). For example, in 2022 income taxes are now $2033.2 billion, which is up from $2032.7 billion, a rise of $0.5 billion, which is an increase of about one-fourth of one-tenth of a percent. There is no change in the payroll tax total for any year in the 2013-2022 period.

Then @MattHJensen asked:
> Why does this change influence results?

First, the results changes are very small: one-fourth of one-tenth of a percent is tiny.
Second, the results changes are caused by the fact that the factors (which will be generated once in the taxdata repository --- see [taxdata issue 60](https://github.com/open-source-economics/taxdata/issues/60)) are rounded to six decimal digits of precision (rather than the 14 significant digits currently being held in memory using the logic on the master branch).

I created an alternative version of the factor CSV file in which the factors have nine decimal digits of precision.  That file is bigger: 3913 bytes rather than 3017 bytes when factors have six decimal digits of precision.  But the extra precision has no effect on income tax or payroll tax liability (because they are rounded to the nearest one-tenth of a billion dollars).  The extra precision does cause changes in some intermediate income tax results.  For example, the AMT liability in 2022 is $57.8 billion, which is the same as on master and down from $57.9 billion in this pull request.  Another example: adding three extra decimal points of precision causes taxable income to rise by $0.2 billion, which is a change of one-fifth of one-tenth of a percent.

Does that information answer your question?

**Comment by MattHJensen** [comment]
> Does that information answer your question?

Yes, thanks a lot. +1 on the change.

**Comment by martinholmer** [comment]
@MattHJensen,  @andersonfrailey and I are working together on some changes to the taxdata repo that we want to put in place before we commit pull request #1178.

**Comment by martinholmer** [comment]
@martinholmer said:
> @andersonfrailey and I are working together on some changes to the taxdata repo that we want to put in place before we commit pull request #1178.

We have made enough progress in that taxdata work to make it sensible to merge #1178 now.

@MattHJensen

**Pull request merged**
