### PR TITLE
Omit certain files from test coverage consideration

### PR DESCRIPTION
**Pull request by talumbau**
Omits functions.py (due to @iterate_jit considerations) and all JSON
files

### CODE REVIEW

**Comment by MattHJensen** [comment]
Nice new score!

**Comment by MattHJensen** [comment]
Do you think we should implement a policy of maintaining coverage?

**Comment by talumbau** [comment]
I looked at the latest report with this PR:

https://codecov.io/github/open-source-economics/Tax-Calculator/taxcalc?ref=72fffb9812735da9e1064c6fad47c3138106dce6

and the remaining files we consider and resulting statistics look legitimate to me. The coverage report now looks to me like if someone were to decrease coverage, it would very likely be adding untested code. This would lead me to support the idea that all future PRs would be expected to have non-decreasing coverage reports from codecov.

**Comment by MattHJensen** [comment]
@martinholmer, could you merge this if it seems like the right way to proceed to you?

**Pull request merged**
