### PR TITLE
Make Travis CI test env come from environment.yml

### PR DESCRIPTION
**Pull request by talumbau**

### CODE REVIEW

**Comment by talumbau** [comment]
This seems like a trivial PR, but it is actually the proper solution for the less than ideal fix from #418. In #418, the .travis.yml was modified to no longer create the test environment from the environment.yml file because it was discovered that every test environment (Python 2.7, Python 3.4, and Python 3.5) were all actually running the tests with Python 3.5! This was happening silently, so the only way the problem was discovered was when a change was made that should have failed on Python 2.7 but Travis CI still passed. So, in #418 we started creating the test environment directly using the `TRAVIS_PYTHON_VERSION` and then explicitly specifying the required packages. This led to duplicate package specification in the environment.yml and the .travis.yml. A colleague recently had this same issue and told me the correct fix: remove `python` from the environment.yml only and create the environment from the `TRAVIS_PYTHON_VERSION`. So, now we test with exactly what is in the environment.yml. This is one step on the path towards a solution to the issues that @zrisher and @salimfurth have found (e.g. #1086, #1095). I think the next step will be to add AppVeyor.

**Comment by talumbau** [comment]
If there are no additional comments, I'd like to merge in this change sometime tomorrow (Wednesday)

**Comment by zrisher** [comment]
Looks great, big :+1:

**Comment by zrisher** [comment]
@talumbau I think this is a very positive change, thanks for taking care of it.

**Pull request merged**
